

		_arsenalHeadgear = [
		
			"BWA3_OpsCore_Fleck",
			"BWA3_OpsCore_Fleck_Patch",
			"BWA3_OpsCore_Fleck_Camera",
			"BWA3_CrewmanKSK_Fleck",
			"BWA3_CrewmanKSK_Fleck_Headset",
			"BWA3_Knighthelm",
			"BWA3_M92_Fleck",
			"BWA3_Booniehat_Fleck",
			"FIR_ScorpionHMCS"

		];
		
		
		_arsenalGoggles = [

			"G_AirPurifyingRespirator_01_F",
			"G_Balaclava_blk",
			"G_Balaclava_combat",
			"G_Balaclava_lowprofile",
			"G_Balaclava_oli",
			"G_Balaclava_TI_blk_F",
			"G_Balaclava_TI_G_blk_F",
			"G_Balaclava_TI_G_tna_F",
			"G_Balaclava_TI_tna_F",
			"G_Combat",
			"G_Combat_Goggles_tna_F",
			"G_B_Diving",
			"G_Lowprofile",
			"G_Tactical_Black",
			"G_Tactical_Clear"
			
		];
		
		
		_arsenalUniforms = [

			"BWA3_Uniform_Fleck",
			"BWA3_Uniform_tee_Fleck",
			"BWA3_Uniform_sleeves_Fleck",
			"BWA3_Uniform_Crew_Fleck",
			"BWA3_Uniform_Helipilot",
			"BWA3_Uniform2_Fleck",
			"BWA3_Uniform2_sleeves_Fleck"

		];

		
		_arsenalVests = [

			"BWA3_Vest_Fleck",
			"BWA3_Vest_Rifleman_Fleck",
			"BWA3_Vest_MachineGunner_Fleck",
			"BWA3_Vest_Grenadier_Fleck",
			"BWA3_Vest_Medic_Fleck",
			"BWA3_Vest_Marksman_Fleck",
			"BWA3_Vest_Leader_Fleck",
			"BWA3_Vest_JPC_Rifleman_Fleck",
			"BWA3_Vest_JPC_Leader_Fleck",
			"BWA3_Vest_JPC_Radioman_Fleck"

		];
		
		

		_arsenalBackpacks = [

			"BWA3_AssaultPack_Fleck",
			"BWA3_AssaultPack_Fleck_Medic",
			"BWA3_AssaultPack_Fleck_Ammo",
			"BWA3_Kitbag_Fleck",
			"BWA3_Kitbag_Fleck_Medic",
			"BWA3_Kitbag_Fleck_CG",
			"BWA3_Kitbag_Fleck_AA",
			"BWA3_Kitbag_Fleck_Illum",
			"BWA3_Kitbag_Fleck_Medic_Filled",
			"BWA3_TacticalPack_Fleck",
			"BWA3_TacticalPack_Fleck_Medic",
			"BWA3_TacticalPack_Fleck_Medic_Filled",
			"BWA3_FieldPack_Fleck",
			"BWA3_Carryall_Fleck",
			"BWA3_Carryall_Fleck_Eng",
			"BWA3_PatrolPack_Fleck",
			
			"B_AssaultPack_blk",	
			"B_Parachute",	
			"B_UAV_01_backpack_F",
			"B_UAV_06_medical_backpack_F",
			"B_UAV_06_backpack_F",
			"B_UGV_02_Demining_backpack_F",
			"B_UGV_02_Science_backpack_F",			
			"B_Static_Designator_01_weapon_F"
			
		];


		_arsenalNvgoggles = [

			"rhsusf_Rhino",
			"rhsusf_anvis_nvg_bc_caps",
			"rhsusf_ANVIS",
			"rhsusf_ANPVS_14",
			"rhsusf_ANPVS_15"

		];


		_arsenalPrimaryAttachments = [

			"rhsusf_acc_harris_bipod",
			"rhsusf_acc_harris_swivel",
			"rhsusf_acc_saw_bipod",
			"rhsusf_acc_saw_lw_bipod",
			"rhsusf_acc_m14_bipod",
			"rhsusf_acc_grip1",
			"rhsusf_acc_grip2",
			"rhsusf_acc_grip3",
			"rhsusf_acc_grip4",
			"rhsusf_acc_grip4_bipod",
			"rhsusf_acc_rvg_blk",
			"rhsusf_acc_tacsac_blk",
			"rhsusf_acc_tdstubby_blk",
			"rhsusf_acc_kac_grip",
			"rhsusf_acc_kac_grip_saw_bipod",
			"rhs_acc_at4_handler",
			"rhsusf_acc_anpeq15A",
			"rhsusf_acc_anpeq15_bk",
			"rhsusf_acc_anpeq15_h",
			"rhsusf_acc_anpeq15_sc",
			"rhsusf_acc_anpeq15_bk_h",
			"rhsusf_acc_anpeq15_bk_sc",
			"rhsusf_acc_anpeq15_bk_light",
			"rhsusf_acc_anpeq15_light_h",
			"rhsusf_acc_anpeq15_light_sc",
			"rhsusf_acc_anpeq15_bk_light_h",
			"rhsusf_acc_anpeq15_bk_light_sc",
			"rhsusf_acc_anpeq15_wmx_h",
			"rhsusf_acc_anpeq15_wmx_light_h",
			"rhsusf_acc_anpeq15_wmx_sc",
			"rhsusf_acc_anpeq15_wmx_light_sc",
			"rhsusf_acc_anpeq15_bk_top",
			"rhsusf_acc_anpeq15_top_h",
			"rhsusf_acc_anpeq15_bk_top_h",
			"rhsusf_acc_anpeq15_top_sc",
			"rhsusf_acc_anpeq15_bk_top_sc",
			"rhsusf_acc_anpeq15side_bk",
			"rhsusf_acc_anpeq16a",
			"rhsusf_acc_anpeq16a_light",
			"rhsusf_acc_anpeq16a_top",
			"rhsusf_acc_anpeq16a_light_top",
			"rhsusf_acc_anpeq16a_top_h",
			"rhsusf_acc_anpeq16a_light_top_h",
			"rhsusf_acc_anpeq16a_top_sc",
			"rhsusf_acc_anpeq16a_light_top_sc",
			"rhsusf_acc_M952V",			
			"rhsusf_acc_wmx_bk",
			"rhsusf_acc_M2010S",
			"rhsusf_acc_M2010S_sa",
			"rhsusf_acc_SR25S",
			"rhsusf_acc_rotex5_grey",
			"rhsusf_acc_nt4_black",
			"rhsusf_acc_omega9k",
			"rhsusf_acc_rotex_mp7",
			"rhsusf_acc_muzzleFlash_ar15",
			"rhsusf_acc_muzzleFlash_SF3P556",
			"rhsusf_acc_muzzleFlash_SFMB556",
			"rhsusf_acc_muzzleFlash_ardec_m240",
			"rhsusf_acc_muzzleFlash_M14_USGI_NM",
			"rhsusf_m4muzzlebreak_base",
			"rhsusf_acc_SF3P556",
			"rhsusf_acc_SFMB556",
			"rhsusf_acc_ARDEC_M240",
			"rhsusf_acc_m14_flashsuppresor",
			"rhsusf_acc_m24_silencer_black",
			"rhsusf_acc_m24_muzzlehider_black",
			"rhsusf_acc_aac_scarh_silencer",
			"rhsusf_acc_aac_762sd_silencer",
			"rhsusf_acc_aac_762sdn6_silencer",
			"rhsusf_acc_aac_m14dcqd_silencer",
			"rhsusf_acc_sniper_base",
			"rhsusf_acc_compm4",
			"rhsusf_acc_T1_high",
			"rhsusf_acc_T1_low",
			"rhsusf_acc_T1_low_fwd",
			"rhsusf_acc_T1_low_fwd_ak",
			"rhsusf_acc_RX01",
			"rhsusf_acc_RX01_NoFilter",
			"rhsusf_acc_RM05",
			"rhsusf_acc_RM05_fwd",
			"rhsusf_acc_RM05_fwd_ak",
			"rhsusf_acc_mrds",
			"rhsusf_acc_mrds_fwd",
			"rhsusf_acc_mrds_fwd_ak",
			"rhsusf_acc_eotech_552",
			"rhsusf_acc_anpvs27",
			"rhsusf_acc_anpas13gv1",
			"rhsusf_acc_LEUPOLDMK4",
			"rhsusf_acc_ELCAN",
			"rhsusf_acc_ELCAN_ard",
			"rhsusf_acc_elcan_3d",
			"rhsusf_acc_elcan_ard_3d",
			"rhsusf_acc_ELCAN_pip",
			"rhsusf_acc_ELCAN_ard_pip",
			"rhsusf_acc_su230_base",
			"rhsusf_acc_su230_base_3d",
			"rhsusf_acc_su230_mrds_base",
			"rhsusf_acc_su230_mrds_base_3d",
			"rhsusf_acc_su230",
			"rhsusf_acc_su230_3d",
			"rhsusf_acc_su230_mrds",
			"rhsusf_acc_su230_mrds_3d",
			"rhsusf_acc_su230a",
			"rhsusf_acc_su230a_3d",
			"rhsusf_acc_su230a_mrds",
			"rhsusf_acc_su230a_mrds_3d",
			"rhsusf_acc_SpecterDR",
			"rhsusf_acc_SpecterDR_D",
			"rhsusf_acc_SpecterDR_OD",
			"rhsusf_acc_SpecterDR_CX",
			"rhsusf_acc_SpecterDR_A",
			"rhsusf_acc_SpecterDR_3d",
			"rhsusf_acc_SpecterDR_D_3D",
			"rhsusf_acc_SpecterDR_OD_3D",
			"rhsusf_acc_SpecterDR_A_3d",
			"rhsusf_acc_SpecterDR_CX_3D",
			"rhsusf_acc_SpecterDR_pvs27",
			"rhsusf_acc_ACOG",
			"rhsusf_acc_ACOG_sa",
			"rhsusf_acc_ACOG2",
			"rhsusf_acc_ACOG3",
			"rhsusf_acc_ACOG_USMC",
			"rhsusf_acc_ACOG2_USMC",
			"rhsusf_acc_ACOG3_USMC",
			"rhsusf_acc_ACOG_RMR",
			"rhsusf_acc_ACOG_3d",
			"rhsusf_acc_ACOG_sa_3d",
			"rhsusf_acc_ACOG2_3d",
			"rhsusf_acc_ACOG3_3d",
			"rhsusf_acc_ACOG_USMC_3d",
			"rhsusf_acc_ACOG2_USMC_3d",
			"rhsusf_acc_ACOG3_USMC_3d",
			"rhsusf_acc_ACOG_RMR_3d",
			"rhsusf_acc_ACOG_pip",
			"rhsusf_acc_ACOG_sa_pip",
			"rhsusf_acc_ACOG2_pip",
			"rhsusf_acc_ACOG3_pip",
			"rhsusf_acc_ACOG_USMC_pip",
			"rhsusf_acc_ACOG2_USMC_pip",
			"rhsusf_acc_ACOG3_USMC_pip",
			"rhsusf_acc_ACOG_RMR_pip",
			"rhsusf_acc_ACOG_anpvs27",
			"rhsusf_acc_LEUPOLDMK4_2",
			"rhsusf_acc_LEUPOLDMK4_2_mrds",
			"rhsusf_acc_premier",
			"rhsusf_acc_premier_mrds",
			"rhsusf_acc_premier_low",
			"rhsusf_acc_premier_anpvs27",
			"rhsusf_acc_M8541",
			"rhsusf_acc_M8541_mrds",
			"rhsusf_acc_M8541_low",
			"rhsusf_acc_M2A1",
			"rhsusf_acc_eotech_xps3",
			"rhsusf_acc_g33_xps3",
			"rhsusf_acc_g33_xps3_flip",
			"rhsusf_acc_g33_T1",
			"rhsusf_acc_g33_T1_flip",
			"rhs_weap_optic_smaw",
			"rhs_weap_optic_smaw_1",
			"rhs_weap_optic_smaw_2",
			"rhs_weap_optic_smaw_3",
			"rhs_weap_optic_smaw_4",
			"rhs_weap_optic_smaw_5",
			"rhs_weap_optic_smaw_6",
			"rhs_weap_optic_smaw_7",
			"rhs_weap_optic_smaw_8",
			"rhs_weap_optic_smaw_9",
			"rhs_weap_optic_smaw_10",
			
			"acc_flashlight",
			"acc_pointer_IR",
			
			"BWA3_ItemNaviPad",
			"BWA3_optic_RSAS",
			"BWA3_optic_RSAS_brown",
			"BWA3_optic_RSAS_sand",
			"BWA3_optic_RSAS_tan",
			"BWA3_optic_RSAS_green",
			"BWA3_optic_RSAS_G36A2",
			"BWA3_optic_RSAS_G36A2_pip",
			"BWA3_optic_RSAS_brown_G36A2",
			"BWA3_optic_RSAS_brown_G36A2_pip",
			"BWA3_optic_RSAS_sand_G36A2",
			"BWA3_optic_RSAS_sand_G36A2_pip",
			"BWA3_optic_RSAS_tan_G36A2",
			"BWA3_optic_RSAS_tan_G36A2_pip",
			"BWA3_optic_RSAS_green_G36A2",
			"BWA3_optic_RSAS_green_G36A2_pip",
			"BWA3_optic_Flipsights",
			"BWA3_optic_G36C_Ironsight_100",
			"BWA3_optic_G36C_Ironsight_300",
			"BWA3_optic_MicroT1",
			"BWA3_optic_MicroT1_G36A2",
			"BWA3_optic_MicroT1_G36A2_pip",
			"BWA3_optic_MicroT2",
			"BWA3_optic_MicroT2_G36A2",
			"BWA3_optic_MicroT2_G36A2_pip",
			"BWA3_optic_CompM2",
			"BWA3_optic_CompM2_tan",
			"BWA3_optic_CompM2_green",
			"BWA3_optic_CompM2_G36A2",
			"BWA3_optic_CompM2_G36A2_pip",
			"BWA3_optic_CompM2_tan_G36A2",
			"BWA3_optic_CompM2_tan_G36A2_pip",
			"BWA3_optic_CompM2_green_G36A2",
			"BWA3_optic_CompM2_green_G36A2_pip",
			"BWA3_optic_EOTech552",
			"BWA3_optic_EOTech552_tan",
			"BWA3_optic_EOTech552_green",
			"BWA3_optic_EOTech552_G36A2",
			"BWA3_optic_EOTech552_G36A2_pip",
			"BWA3_optic_EOTech552_tan_G36A2",
			"BWA3_optic_EOTech552_tan_G36A2_pip",
			"BWA3_optic_EOTech552_green_G36A2",
			"BWA3_optic_EOTech552_green_G36A2_pip",
			"BWA3_optic_EOTech",
			"BWA3_optic_EOTech_sand",
			"BWA3_optic_EOTech_G36A2",
			"BWA3_optic_EOTech_G36A2_pip",
			"BWA3_optic_EOTech_sand_G36A2",
			"BWA3_optic_EOTech_sand_G36A2_pip",
			"BWA3_optic_ZO4x30",
			"BWA3_optic_ZO4x30_pip",
			"BWA3_optic_ZO4x30_brown",
			"BWA3_optic_ZO4x30_brown_pip",
			"BWA3_optic_ZO4x30_NSV",
			"BWA3_optic_ZO4x30_NSV_pip",
			"BWA3_optic_ZO4x30_brown_NSV",
			"BWA3_optic_ZO4x30_brown_NSV_pip",
			"BWA3_optic_ZO4x30_IRV",
			"BWA3_optic_ZO4x30_IRV_pip",
			"BWA3_optic_ZO4x30_brown_IRV",
			"BWA3_optic_ZO4x30_brown_IRV_pip",
			"BWA3_optic_ZO4x30_RSAS",
			"BWA3_optic_ZO4x30_RSAS_pip",
			"BWA3_optic_ZO4x30_RSAS_brown",
			"BWA3_optic_ZO4x30_RSAS_brown_pip",
			"BWA3_optic_ZO4x30_RSAS_NSV",
			"BWA3_optic_ZO4x30_RSAS_NSV_pip",
			"BWA3_optic_ZO4x30_RSAS_brown_NSV",
			"BWA3_optic_ZO4x30_RSAS_brown_NSV_pip",
			"BWA3_optic_ZO4x30_RSAS_IRV",
			"BWA3_optic_ZO4x30_RSAS_IRV_pip",
			"BWA3_optic_ZO4x30_RSAS_brown_IRV",
			"BWA3_optic_ZO4x30_RSAS_brown_IRV_pip",
			"BWA3_optic_ZO4x30_MicroT2",
			"BWA3_optic_ZO4x30_MicroT2_pip",
			"BWA3_optic_ZO4x30_MicroT2_brown",
			"BWA3_optic_ZO4x30_MicroT2_brown_pip",
			"BWA3_optic_ZO4x30_MicroT2_NSV",
			"BWA3_optic_ZO4x30_MicroT2_NSV_pip",
			"BWA3_optic_ZO4x30_MicroT2_brown_NSV",
			"BWA3_optic_ZO4x30_MicroT2_brown_NSV_pip",
			"BWA3_optic_ZO4x30_MicroT2_IRV",
			"BWA3_optic_ZO4x30_MicroT2_IRV_pip",
			"BWA3_optic_ZO4x30_MicroT2_brown_IRV",
			"BWA3_optic_ZO4x30_MicroT2_brown_IRV_pip",
			"BWA3_optic_ZO4x30i",
			"BWA3_optic_ZO4x30i_pip",
			"BWA3_optic_ZO4x30i_sand",
			"BWA3_optic_ZO4x30i_sand_pip",
			"BWA3_optic_ZO4x30i_RSAS",
			"BWA3_optic_ZO4x30i_RSAS_pip",
			"BWA3_optic_ZO4x30i_RSAS_sand",
			"BWA3_optic_ZO4x30i_RSAS_sand_pip",
			"BWA3_optic_ZO4x30i_MicroT2",
			"BWA3_optic_ZO4x30i_MicroT2_pip",
			"BWA3_optic_ZO4x30i_MicroT2_sand",
			"BWA3_optic_ZO4x30i_MicroT2_sand_pip",
			"BWA3_optic_EOTech_Mag_Off",
			"BWA3_optic_EOTech_Mag_On",
			"BWA3_optic_EOTech_sand_Mag_Off",
			"BWA3_optic_EOTech_sand_Mag_On",
			"BWA3_optic_PMII_ShortdotCC",
			"BWA3_optic_PMII_ShortdotCC_pip",
			"BWA3_optic_PMII_DMR",
			"BWA3_optic_PMII_DMR_pip",
			"BWA3_optic_PMII_DMR_MicroT1_front",
			"BWA3_optic_PMII_DMR_MicroT1_front_pip",
			"BWA3_optic_PMII_DMR_MicroT1_rear",
			"BWA3_optic_PMII_DMR_MicroT1_rear_pip",
			"BWA3_optic_PMII_DMR_NSV",
			"BWA3_optic_PMII_DMR_NSV_pip",
			"BWA3_optic_PMII_DMR_MicroT1_front_NSV",
			"BWA3_optic_PMII_DMR_MicroT1_front_NSV_pip",
			"BWA3_optic_PMII_DMR_MicroT1_rear_NSV",
			"BWA3_optic_PMII_DMR_MicroT1_rear_NSV_pip",
			"BWA3_optic_M5Xi_Tremor3",
			"BWA3_optic_M5Xi_Tremor3_pip",
			"BWA3_optic_M5Xi_Tremor3_MicroT2",
			"BWA3_optic_M5Xi_Tremor3_MicroT2_pip",
			"BWA3_optic_M5Xi_MSR",
			"BWA3_optic_M5Xi_MSR_pip",
			"BWA3_optic_M5Xi_MSR_MicroT2",
			"BWA3_optic_M5Xi_MSR_MicroT2_pip",
			"BWA3_optic_M5Xi_Tremor3_NSV",
			"BWA3_optic_M5Xi_Tremor3_NSV_pip",
			"BWA3_optic_M5Xi_Tremor3_MicroT2_NSV",
			"BWA3_optic_M5Xi_Tremor3_MicroT2_NSV_pip",
			"BWA3_optic_M5Xi_MSR_NSV",
			"BWA3_optic_M5Xi_MSR_NSV_pip",
			"BWA3_optic_M5Xi_MSR_MicroT2_NSV",
			"BWA3_optic_M5Xi_MSR_MicroT2_NSV_pip",
			"BWA3_optic_Hensoldt",
			"BWA3_optic_Hensoldt_NSV",
			"BWA3_optic_NSV600",
			"BWA3_optic_IRV600",
			"BWA3_optic_NSV80",
			"BWA3_optic_NSA80",
			"BWA3_optic_NSA80_G36",
			"BWA3_optic_CarlGustav",
			"BWA3_acc_LLM01_irlaser",
			"BWA3_acc_LLM01_flash",
			"BWA3_acc_LLM01_laser",
			"BWA3_acc_LLM01_irlaser_tan",
			"BWA3_acc_LLM01_flash_tan",
			"BWA3_acc_LLM01_laser_tan",
			"BWA3_acc_LLM01_irlaser_green",
			"BWA3_acc_LLM01_flash_green",
			"BWA3_acc_LLM01_laser_green",
			"BWA3_acc_LLM01_irlaser_underbarrel",
			"BWA3_acc_LLM01_flash_underbarrel",
			"BWA3_acc_LLM01_laser_underbarrel",
			"BWA3_acc_VarioRay_irlaser",
			"BWA3_acc_VarioRay_flash",
			"BWA3_acc_VarioRay_laser",
			"BWA3_acc_VarioRay_irlaser_black",
			"BWA3_acc_VarioRay_flash_black",
			"BWA3_acc_VarioRay_laser_black",
			"BWA3_muzzle_snds_Rotex_IIA",
			"BWA3_muzzle_snds_Rotex_Monoblock",
			"BWA3_muzzle_snds_Rotex_IIIC",
			"BWA3_muzzle_snds_Rotex_IIIC_tan",
			"BWA3_muzzle_snds_Rotex_IIIC_green",
			"BWA3_muzzle_snds_QDSS",
			"BWA3_muzzle_snds_QDSS_tan",
			"BWA3_muzzle_snds_QDSS_green",
			"BWA3_muzzle_snds_Rotex_II",
			"BWA3_bipod_MG3",
			"BWA3_bipod_Atlas",
			"BWA3_bipod_Harris",
			"BWA3_bipod_Harris_tan",
			"BWA3_bipod_Harris_green",
			"BWA3_Vector",
			"BWA3_SEM90"
		
		];


		_arsenalSecondaryAttachments = [

		];
		
		_arsenalExplosives = [
		
			"SatchelCharge_Remote_Mag",
			"DemoCharge_Remote_Mag",
			"SLAMDirectionalMine_Wire_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellGreen",
			"SmokeShellYellow",
			"SmokeShellPurple",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_yellow",
			"Chemlight_blue",
			"B_IR_Grenade",
			"Laserbatteries"
		
		];


		_arsenalItems = [
		
			"rhsusf_bino_lerca_1200_black",
			"rhsusf_bino_lerca_1200_tan",
			"lerca_1200_black",
			"lerca_1200_tan",
			"rhsusf_bino_lrf_Vector21",
			"rhsusf_lrf_Vector21",
			"rhsusf_bino_leopold_mk4",
			"Leupold_Mk4",
			"rhsusf_bino_m24",
			"rhsusf_bino_m24_ARD",
			"m24_bino",
			"m24_bino_ARD",
			
			"ItemGPS",
			"B_UavTerminal",
			"Laserdesignator",
			"MineDetector",
			"Binocular",
			"FirstAidKit",
			"ItemCompass",
			"Rangefinder",
			"ItemWatch",
			"ToolKit",
			"ItemRadio",
			"Medikit",
			"ItemMap"

		];
				
		_return = [_arsenalHeadgear, _arsenalGoggles, _arsenalUniforms, _arsenalVests, _arsenalBackpacks, _arsenalNvgoggles, _arsenalPrimaryAttachments, _arsenalSecondaryAttachments, _arsenalExplosives, _arsenalItems];
		
		_return
