		_arsenalHeadgear = [
			
			'CUP_H_OpsCore_Covered_MTP_SF',
			'CUP_H_OpsCore_Covered_MTP',
			'CUP_H_OpsCore_Covered_MTP_NoHS',
			
			'CUP_H_BAF_Helmet_Pilot',
			'CUP_H_BAF_PILOT',
			
			'CUP_H_BAF_MTP_Mk7',
			'CUP_H_BAF_MTP_Mk7_PRR',
			'CUP_H_BAF_MTP_Mk7_PRR_SCRIM_A',
			'CUP_H_BAF_MTP_Mk7_PRR_SCRIM_B',
			'CUP_H_BAF_MTP_Mk6_EMPTY',
			'CUP_H_BAF_MTP_Mk6_EMPTY_PRR',
			'CUP_H_BAF_MTP_Mk6_CREW_PRR',
			'CUP_H_BAF_MTP_Mk6_GLASS_PRR',
			'CUP_H_BAF_MTP_Mk6_GOGGLES_PRR',
			'CUP_H_BAF_MTP_Mk6_NETTING_PRR',
			'CUP_H_BAF_Crew_Helmet_MTP',
			'CUP_H_BAF_Helmet_Net_2_MTP',
			'CUP_H_BAF_Helmet_1_MTP',
			'CUP_H_BAF_Helmet_2_MTP',
			'CUP_H_BAF_Helmet_3_MTP',
			'CUP_H_BAF_Helmet_4_MTP',
			'CUP_H_SPH4',
			'CUP_H_SPH4_visor',
			'CUP_H_SPH4_green',
			'CUP_H_SPH4_green_visor',
			'CUP_H_SPH4_khaki',
			'CUP_H_SPH4_khaki_visor',
			'CUP_H_SPH4_grey',
			'CUP_H_SPH4_grey_visor',
			"H_PilotHelmetFighter_B",
			'CUP_H_CVC'
	
		];

		_arsenalGoggles = [

			"G_AirPurifyingRespirator_01_F",
			"G_Balaclava_blk",
			"G_Balaclava_combat",
			"G_Balaclava_lowprofile",
			"G_Balaclava_oli",
			"G_Balaclava_TI_blk_F",
			"G_Balaclava_TI_G_blk_F",
			"G_Balaclava_TI_G_tna_F",
			"G_Balaclava_TI_tna_F",
			"G_Combat",
			"G_Combat_Goggles_tna_F",
			"G_B_Diving",
			"G_Lowprofile",
			"G_Tactical_Black",
			"G_Tactical_Clear"
			
		];

		_arsenalUniforms = [
				
			'CUP_U_B_BAF_MTP_UBACSLONG',
			'CUP_U_B_BAF_MTP_UBACSLONG_Gloves',
			'CUP_U_B_BAF_MTP_UBACSLONGKNEE',
			'CUP_U_B_BAF_MTP_UBACSLONGKNEE_Gloves',
			'CUP_U_B_BAF_MTP_UBACSSEAL',
			'CUP_U_B_BAF_MTP_UBACSROLLED',
			'CUP_U_B_BAF_MTP_UBACSROLLED_Gloves',
			'CUP_U_B_BAF_MTP_UBACSROLLEDKNEE',
			'CUP_U_B_BAF_MTP_UBACSTSHIRT',
			'CUP_U_B_BAF_MTP_UBACSTSHIRT_Gloves',
			'CUP_U_B_BAF_MTP_UBACSTSHIRTKNEE',
			'CUP_U_B_BAF_MTP_S1_RolledUp',
			'CUP_U_B_BAF_MTP_S2_UnRolled',
			'CUP_U_B_BAF_MTP_Tshirt',
			'CUP_U_B_BAF_MTP_S3_RolledUp',
			'CUP_U_B_BAF_MTP_S4_UnRolled',
			'CUP_U_B_BAF_MTP_S5_UnRolled',
			'CUP_U_B_BAF_MTP_S6_UnRolled'
		
		];

		_arsenalVests = [
				
			'CUP_V_BAF_Osprey_Mk4_MTP_Grenadier',
			'CUP_V_BAF_Osprey_Mk4_MTP_MachineGunner',
			'CUP_V_BAF_Osprey_Mk4_MTP_Rifleman',
			'CUP_V_BAF_Osprey_Mk4_MTP_SquadLeader',
			'CUP_V_B_BAF_MTP_Osprey_Mk4_Crewman',
			'CUP_V_B_BAF_MTP_Osprey_Mk4_Empty',
			'CUP_V_B_BAF_MTP_Osprey_Mk4_Engineer',
			'CUP_V_B_BAF_MTP_Osprey_Mk4_Grenadier',
			'CUP_V_B_BAF_MTP_Osprey_Mk4_AutomaticRifleman',
			'CUP_V_B_BAF_MTP_Osprey_Mk4_Medic',
			'CUP_V_B_BAF_MTP_Osprey_Mk4_Rifleman',
			'CUP_V_B_BAF_MTP_Osprey_Mk4_Scout',
			'CUP_V_B_BAF_MTP_Osprey_Mk4_Officer',
			'CUP_V_B_BAF_MTP_Osprey_Mk4_Belt',
			'CUP_V_B_BAF_MTP_Osprey_Mk4_Webbing'

		];

		_arsenalBackpacks = [

			'CUP_B_Bergen_BAF',
			'CUP_B_Predator_Ammo_MTP',
			'CUP_B_Predator_AA_MTP',
			'CUP_B_Predator_AT_MTP',
			'CUP_B_Predator_RAT_MTP',
			'CUP_B_Predator_RLAT_MTP',
			'CUP_B_Predator_Explosive_MTP',
			'CUP_B_Predator_Mine_MTP',
			'CUP_B_Motherlode_Medic_MTP',
			'CUP_B_Motherlode_Engineer_MTP',
			
			'B_Kitbag_cbr',
			'B_Kitbag_rgr',
			
			"B_UAV_01_backpack_F",
			"B_UAV_06_medical_backpack_F",
			"B_UAV_06_backpack_F",
			"B_UGV_02_Demining_backpack_F",
			"B_UGV_02_Science_backpack_F",
			"B_Parachute",
			"B_Static_Designator_01_weapon_F"

		];

		_arsenalNvgoggles = [
		
			"NVGoggles",
			"NVGoggles_OPFOR",
		
			'CUP_NVG_PVS7',
			'CUP_NVG_PVS7_Hide',
			'CUP_NVG_HMNVS',
			'CUP_NVG_HMNVS_Hide',
			'CUP_NVG_PVS14',
			'CUP_NVG_PVS14_Hide',
			'CUP_NVG_GPNVG_black',
			'CUP_NVG_GPNVG_Hide',
			'CUP_NVG_GPNVG_tan',
			'CUP_NVG_GPNVG_green',
			'CUP_NVG_GPNVG_winter',
			'CUP_NVG_PVS15_black',
			'CUP_NVG_PVS15_Hide',
			'CUP_NVG_PVS15_tan',
			'CUP_NVG_PVS15_green',
			'CUP_NVG_PVS15_winter'

		];	

		_arsenalPrimaryAttachments = [
		
			'CUP_optic_AC11704_Black',
			'CUP_optic_VortexRazor_UH1_Black',		
			'CUP_optic_artel_m14',
			'CUP_optic_artel_m14_pip',
			'CUP_optic_Aimpoint_5000',
			'CUP_optic_CWS',
			'CUP_optic_CWS_NV',
			'CUP_optic_CWS_NV_RDS',
			'CUP_optic_HoloBlack',
			'CUP_optic_Eotech553_Black',		
			'CUP_optic_CompM2_Black',			
			'CUP_optic_CompM2_low',			
			'CUP_optic_CompM4',
			'CUP_optic_MicroT1',			
			'CUP_optic_MicroT1_low',			
			'CUP_optic_MARS',
			'CUP_optic_MEPRO',
			'CUP_optic_MEPRO_openx_orange',
			'CUP_optic_MEPRO_moa_clear',
			'CUP_optic_MEPRO_tri_clear',
			'CUP_optic_SUSAT',
			'CUP_optic_SUSAT_PIP',
			'CUP_optic_SUSAT_3D',
			'CUP_optic_ACOG',
			'CUP_optic_ACOG_PIP',
			'CUP_optic_ACOG_3D',
			'CUP_optic_ACOG2',
			'CUP_optic_ACOG2_PIP',
			'CUP_optic_ACOG2_3D',
			'CUP_optic_ACOG_TA31_KF',
			'CUP_optic_ACOG_TA31_KF_PIP',
			'CUP_optic_ACOG_TA31_KF_3D',
			'CUP_optic_RCO',
			'CUP_optic_ACOG_TA01NSN_Black_PIP',
			'CUP_optic_ACOG_TA01NSN_Black_3D',
			'CUP_optic_ACOG_TA01NSN_RMR_Black',
			'CUP_optic_ACOG_TA01NSN_RMR_Black_PIP',
			'CUP_optic_ACOG_TA01NSN_RMR_Black_3D',
			'CUP_optic_ACOG_TA01B_Black',
			'CUP_optic_ACOG_TA01B_Black_PIP',
			'CUP_optic_ACOG_TA01B_Black_3D',
			'CUP_optic_ACOG_TA01B_RMR_Black',
			'CUP_optic_ACOG_TA01B_RMR_Black_PIP',
			'CUP_optic_ACOG_TA01B_RMR_Black_3D',
			'CUP_optic_LeupoldMk4',
			'CUP_optic_LeupoldMk4_pip',
			'CUP_optic_Leupold_VX3',
			'CUP_optic_Leupold_VX3_pip',
			'CUP_optic_LeupoldM3LR',
			'CUP_optic_LeupoldM3LR_pip',
			'CUP_optic_LeupoldMk4_20x40_LRT',
			'CUP_optic_LeupoldMk4_20x40_LRT_pip',
			'CUP_optic_LeupoldMk4_CQ_T',
			'CUP_optic_SB_11_4x20_PM',
			'CUP_optic_SB_11_4x20_PM_pip',
			'CUP_optic_SB_3_12x50_PMII',
			'CUP_optic_SB_3_12x50_PMII_PIP',
			'CUP_optic_ZDDot',
			'CUP_optic_MRad',
			'CUP_optic_TrijiconRx01_black',
			'CUP_optic_TrijiconRx01_kf_black',
			'CUP_optic_AN_PVS_4',
			'CUP_optic_AN_PVS_4_M14',
			'CUP_optic_AN_PVS_4_M16',
			'CUP_optic_AN_PVS_10_black',
			'CUP_optic_AN_PAS_13c1',
			'CUP_optic_AN_PAS_13c2',
			'CUP_optic_ElcanM145',
			'CUP_optic_ElcanM145_PIP',
			'CUP_optic_ElcanM145_3D',
			'CUP_optic_Elcan_SpecterDR_black',
			'CUP_optic_Elcan_SpecterDR_black_PIP',
			'CUP_optic_Elcan_SpecterDR_black_3D',
			'CUP_optic_Elcan_SpecterDR_KF_black',
			'CUP_optic_Elcan_SpecterDR_KF_black_PIP',
			'CUP_optic_Elcan_SpecterDR_KF_black_3D',
			'CUP_optic_Elcan_SpecterDR_RMR_black',
			'CUP_optic_Elcan_SpecterDR_RMR_black_PIP',
			'CUP_optic_Elcan_SpecterDR_RMR_black_3D',
			'CUP_optic_Elcan_SpecterDR_KF_RMR_black',
			'CUP_optic_Elcan_SpecterDR_KF_RMR_black_PIP',
			'CUP_optic_Elcan_SpecterDR_KF_RMR_black_3D',
			'CUP_optic_Elcan',
			'CUP_optic_Elcan_pip',
			'CUP_optic_Elcan_3D',
			'CUP_optic_Elcan_reflex',
			'CUP_optic_Elcan_reflex_pip',
			'CUP_optic_Elcan_reflex_3D',
			'CUP_optic_ZeissZPoint',
			'CUP_optic_HensoldtZO',
			'CUP_optic_HensoldtZO_PIP',
			'CUP_optic_HensoldtZO_3D',
			'CUP_optic_HensoldtZO_RDS',
			'CUP_optic_HensoldtZO_RDS_PIP',
			'CUP_optic_HensoldtZO_RDS_3D',
			'CUP_optic_HensoldtZO_low',
			'CUP_optic_HensoldtZO_low_PIP',
			'CUP_optic_HensoldtZO_low_3D',
			'CUP_optic_HensoldtZO_low_RDS',
			'CUP_optic_HensoldtZO_low_RDS_PIP',
			'CUP_optic_HensoldtZO_low_RDS_3D',
			'CUP_optic_LeupoldMk4_25x50_LRT',
			'CUP_optic_LeupoldMk4_25x50_LRT_pip',
			'CUP_acc_ANPEQ_15',
			'CUP_acc_ANPEQ_15_V',
			'CUP_acc_ANPEQ_15_Black',
			'CUP_acc_ANPEQ_15_Black_V',
			'CUP_acc_ANPEQ_15_Black_Top',
			'CUP_acc_ANPEQ_15_Black_Top_V',
			'CUP_acc_ANPEQ_2',
			'CUP_acc_ANPEQ_2_Black_Top',
			'CUP_acc_Flashlight',
			'CUP_acc_Flashlight_MP5SD',
			'CUP_acc_XM8_light_module',
			'CUP_acc_CZ_M3X',
			'CUP_acc_CZ_M3X_L',
			'CUP_acc_MLPLS_Laser',
			'CUP_acc_ANPEQ_2_Flashlight_Black_L',
			'CUP_acc_ANPEQ_2_Flashlight_Black_F',
			'CUP_acc_ANPEQ_15_Flashlight_Black_L',
			'CUP_acc_ANPEQ_15_Flashlight_Black_F',
			'CUP_acc_ANPEQ_15_Flashlight_Black_V',
			'CUP_acc_ANPEQ_15_Top_Flashlight_Black_L',
			'CUP_acc_ANPEQ_15_Top_Flashlight_Black_F',
			'CUP_acc_ANPEQ_15_Top_Flashlight_Black_V',
			'CUP_acc_LLM01_L',
			'CUP_acc_LLM01_F',
			'CUP_acc_LLM_Flashlight',
			'CUP_acc_LLM_black',
			'CUP_acc_LLM_black_Flashlight',
			'CUP_optic_G33_HWS_BLK',
			'CUP_optic_G33_HWS_BLK_DWN',
			'CUP_optic_AIMM_COMPM4_BLK',
			'CUP_optic_AIMM_COMPM4_BLK_DWN',
			'CUP_optic_AIMM_COMPM2_BLK',
			'CUP_optic_AIMM_COMPM2_BLK_DWN',
			'CUP_optic_AIMM_MICROT1_BLK',
			'CUP_optic_AIMM_MICROT1_BLK_DWN',
			'CUP_optic_AIMM_ZDDOT_BLK',
			'CUP_optic_AIMM_ZDDOT_BLK_DWN',
			'CUP_optic_AIMM_MARS_BLK',
			'CUP_optic_AIMM_MARS_BLK_DWN',
			'CUP_optic_AIMM_M68_BLK',
			'CUP_optic_AIMM_M68_BLK_DWN',
			'CUP_bipod_Harris_1A2_L',
			'CUP_bipod_Harris_1A2_L_BLK',
			'CUP_bipod_VLTOR_Modpod',
			'CUP_bipod_VLTOR_Modpod_black',
			'CUP_muzzle_mfsup_Flashhider_556x45_Black',
			'CUP_muzzle_mfsup_Flashhider_762x51_Black',
			'CUP_muzzle_snds_M16',
			'CUP_muzzle_snds_FAMAS',
			'CUP_muzzle_mfsup_Suppressor_M107_Black',
			'CUP_muzzle_mfsup_Suppressor_Mac10',
			'CUP_muzzle_snds_mk23',
			'CUP_muzzle_snds_68SPC',
			'CUP_optic_PSO_1',
			'CUP_optic_PSO_1_open',
			'CUP_optic_PSO_1_open_pip',
			'CUP_optic_PSO_1_AK',
			'CUP_optic_PSO_1_AK_open',
			'CUP_optic_PSO_1_AK_open_pip',
			'CUP_optic_PSO_1_1',
			'CUP_optic_PSO_1_1_open',
			'CUP_optic_PSO_1_1_open_pip',
			'CUP_optic_PSO_3',
			'CUP_optic_PSO_3_open',
			'CUP_optic_PSO_3_open_pip',
			'CUP_optic_Kobra',
			'CUP_optic_Kobra_01',
			'CUP_optic_Kobra_02',
			'CUP_optic_Kobra_03',
			'CUP_optic_GOSHAWK',
			'CUP_optic_GOSHAWK_RIS',
			'CUP_optic_1P87_RIS',
			'CUP_optic_NSPU',
			'CUP_optic_PechenegScope',
			'CUP_muzzle_PB6P9',
			'CUP_muzzle_Bizon',
			'CUP_muzzle_PBS4',
			'CUP_muzzle_mfsup_Flashhider_545x39_Black',
			'CUP_muzzle_mfsup_Flashhider_762x39_Black',
			'CUP_muzzle_mfsup_Flashhider_PK_Black',
			'CUP_muzzle_TGPA',
			'CUP_muzzle_snds_KZRZP_Base',
			'CUP_muzzle_snds_KZRZP_SVD',
			'CUP_muzzle_snds_KZRZP_AK762',
			'CUP_muzzle_snds_KZRZP_AK545',
			'CUP_muzzle_snds_KZRZP_PK',
			'CUP_optic_ekp_8_02',
			'CUP_optic_ekp_8_02_01',
			'CUP_optic_ekp_8_02_02',
			'CUP_optic_ekp_8_02_03',
			'CUP_optic_GrozaScope',
			'CUP_optic_GrozaScope_pip',
			'CUP_muzzle_snds_groza',
			'CUP_optic_1p63',
			'CUP_bipod_G3',
			'CUP_bipod_G3SG1',
			'CUP_optic_no23mk2',
			'CUP_optic_no23mk2_pip',
			'CUP_optic_MAAWS_Scope',
			'CUP_SVD_camo_g',
			'CUP_SVD_camo_g_half',
			'CUP_SVD_camo_d',
			'CUP_SVD_camo_d_half',
			'CUP_muzzle_snds_SR3M',
			'CUP_muzzle_snds_AWM',
			'CUP_bipod_FNFAL',
			'CUP_muzzle_snds_G36_black',
			'CUP_optic_G36DualOptics',
			'CUP_optic_G36DualOptics_PIP',
			'CUP_optic_G36DualOptics_3D',
			'CUP_optic_G36Optics',
			'CUP_optic_G36Optics_PIP',
			'CUP_optic_G36Optics_3D',
			'CUP_optic_G36Optics15x',
			'CUP_optic_G36Optics15x_PIP',
			'CUP_optic_G36Optics15x_3D',
			'CUP_optic_G36Optics_Holo',
			'CUP_optic_G36Optics_Holo_PIP',
			'CUP_optic_G36Optics_Holo_3D',
			'CUP_optic_G36Optics_RDS',
			'CUP_optic_G36Optics_RDS_PIP',
			'CUP_optic_G36Optics_RDS_3D',
			'CUP_acc_Glock17_Flashlight',
			'CUP_muzzle_snds_L85',
			'CUP_acc_sffh',
			'CUP_acc_bfa',
			'CUP_muzzle_snds_M110',
			'CUP_muzzle_snds_M110_black',
			'CUP_muzzle_snds_M14',
			'CUP_muzzle_snds_Mk12',
			'CUP_Mxx_camo',
			'CUP_Mxx_camo_half',
			'CUP_muzzle_snds_M3A1_blk',
			'CUP_muzzle_snds_M3A1',
			'CUP_muzzle_snds_M9',
			'CUP_muzzle_snds_MicroUzi',
			'CUP_acc_mk23_lam_f',
			'CUP_acc_mk23_lam_l',
			'CUP_optic_PEM',
			'CUP_optic_PEM_pip',
			'CUP_optic_PEM_3D',
			'CUP_muzzle_snds_MP7',
			'CUP_optic_Remington',
			'CUP_optic_Remington_pip',
			'CUP_muzzle_snds_SA61',
			'CUP_muzzle_snds_SCAR_L',
			'CUP_muzzle_mfsup_SCAR_L',
			'CUP_muzzleFlash2SCAR_L',
			'CUP_muzzle_snds_SCAR_H',
			'CUP_muzzle_mfsup_SCAR_H',
			'CUP_optic_SMAW_Scope',
			'CUP_muzzle_snds_XM8'

		];

		_arsenalSecondaryAttachments = [

			"optic_MRD",
			"optic_Yorris",
			"acc_flashlight_pistol"

		];
		
		_arsenalExplosives = [
		
			"SatchelCharge_Remote_Mag",
			"DemoCharge_Remote_Mag",
			"SLAMDirectionalMine_Wire_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellGreen",
			"SmokeShellYellow",
			"SmokeShellPurple",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_yellow",
			"Chemlight_blue",
			"B_IR_Grenade",
			"Laserbatteries"
		
		];

		_arsenalItems = [
		
			"ItemGPS",
			"B_UavTerminal",
			"Laserdesignator",
			"MineDetector",
			"Binocular",
			"FirstAidKit",
			"ItemCompass",
			"Rangefinder",
			"ItemWatch",
			"ToolKit",
			"ItemRadio",
			"Medikit",
			"ItemMap"

		];
		
		_return = [_arsenalHeadgear, _arsenalGoggles, _arsenalUniforms, _arsenalVests, _arsenalBackpacks, _arsenalNvgoggles, _arsenalPrimaryAttachments, _arsenalSecondaryAttachments, _arsenalExplosives, _arsenalItems];
	
		_return
