	private ["_marksmanGear", "_autoRiflemanGear", "_ATgear", "_engineerGear", "_GLGear", "_TLGear"];
	
			_marksmanGear = [

				'srifle_DMR_01_F',
				'srifle_DMR_01_ACO_F',
				'srifle_DMR_01_MRCO_F',
				'srifle_DMR_01_SOS_F',
				'srifle_DMR_01_DMS_F',
				'srifle_DMR_01_DMS_snds_F',
				'srifle_DMR_01_ARCO_F',
				
				'srifle_EBR_F',
				'srifle_EBR_ACO_F',
				'srifle_EBR_MRCO_pointer_F',
				'srifle_EBR_ARCO_pointer_F',
				'srifle_EBR_SOS_F',
				'srifle_EBR_ARCO_pointer_snds_F',
				'srifle_EBR_DMS_F',
				'srifle_EBR_Hamr_pointer_F',
				'srifle_EBR_DMS_pointer_snds_F',
				'srifle_EBR_MRCO_LP_BI_F',
				
				'srifle_GM6_F',
				'srifle_GM6_SOS_F',
				'srifle_GM6_LRPS_F',
				'srifle_GM6_camo_F',
				'srifle_GM6_camo_SOS_F',
				'srifle_GM6_camo_LRPS_F',
				'srifle_GM6_ghex_F',
				'srifle_GM6_ghex_LRPS_F',
				
				'srifle_LRR_F',
				'srifle_LRR_SOS_F',
				'srifle_LRR_LRPS_F',
				'srifle_LRR_camo_F',
				'srifle_LRR_camo_SOS_F',
				'srifle_LRR_camo_LRPS_F',		
				'srifle_LRR_tna_F',
				'srifle_LRR_tna_LRPS_F',
				
				'srifle_DMR_07_blk_F',
				'srifle_DMR_07_hex_F',
				'srifle_DMR_07_ghex_F',
				'srifle_DMR_07_blk_DMS_F',
				'srifle_DMR_07_blk_DMS_Snds_F',
				'srifle_DMR_07_blk_F_arco_flash_F',
				
				'srifle_DMR_01_DMS_BI_F',
				'srifle_DMR_01_DMS_snds_BI_F',
				
				'srifle_DMR_02_F',
				'srifle_DMR_02_camo_F',
				'srifle_DMR_02_sniper_F',
				'srifle_DMR_02_ACO_F',
				'srifle_DMR_02_MRCO_F',
				'srifle_DMR_02_SOS_F',
				'srifle_DMR_02_DMS_F',
				'srifle_DMR_02_sniper_AMS_LP_S_F',
				'srifle_DMR_02_camo_AMS_LP_F',
				'srifle_DMR_02_ARCO_F',
				
				'srifle_DMR_03_F',
				'srifle_DMR_03_khaki_F',
				'srifle_DMR_03_tan_F',
				'srifle_DMR_03_multicam_F',
				'srifle_DMR_03_woodland_F',
				'srifle_DMR_03_ACO_F',
				'srifle_DMR_03_MRCO_F',
				'srifle_DMR_03_SOS_F',
				'srifle_DMR_03_DMS_F',
				'srifle_DMR_03_tan_AMS_LP_F',
				'srifle_DMR_03_DMS_snds_F',
				'srifle_DMR_03_ARCO_F',
				'srifle_DMR_03_AMS_F',
				
				'srifle_DMR_04_F',
				'srifle_DMR_04_Tan_F',
				'srifle_DMR_04_ACO_F',
				'srifle_DMR_04_MRCO_F',
				'srifle_DMR_04_SOS_F',
				'srifle_DMR_04_DMS_F',
				'srifle_DMR_04_ARCO_F',
				'srifle_DMR_04_NS_LP_F',
				'srifle_DMR_04_DMS_weathered_Kir_F_F',
				
				'srifle_DMR_05_blk_F',
				'srifle_DMR_05_hex_F',
				'srifle_DMR_05_tan_f',
				'srifle_DMR_05_ACO_F',
				'srifle_DMR_05_MRCO_F',
				'srifle_DMR_05_SOS_F',
				'srifle_DMR_05_DMS_F',
				'srifle_DMR_05_KHS_LP_F',
				'srifle_DMR_05_DMS_snds_F',
				'srifle_DMR_05_ARCO_F',
									
				'arifle_MXM_DMS_LP_BI_snds_F',
				'arifle_MXM_Hamr_LP_BI_F',
				'arifle_MXM_khk_F',
				'arifle_MXM_khk_MOS_Pointer_Bipod_F',
				'arifle_MXM_khk_MOS_Pointer_Bipod_Snds_F',
				'arifle_MXM_Black_MOS_Pointer_Bipod_F',
				'arifle_MXM_Black_MOS_Pointer_Bipod_Snds_F',
				'arifle_MXM_Hamr_pointer_F',
				'arifle_MXM_F',
				'arifle_MXM_SOS_pointer_F',
				'arifle_MXM_RCO_pointer_snds_F',
				'arifle_MXM_DMS_F',
				'arifle_MXM_Black_F',
				
				'arifle_SPAR_03_blk_F',
				'arifle_SPAR_03_khk_F',
				'arifle_SPAR_03_snd_F',
				
				'arifle_MSBS65_Mark_SOS_LP_BI_F',
				'arifle_MSBS65_Mark_F',	
				'arifle_MSBS65_Mark_black_F',	
				'arifle_MSBS65_Mark_sand_F',		
				'arifle_MSBS65_Mark_camo_F',

				"rhs_weap_M107",
				"rhs_weap_M107_d",
				"rhs_weap_M107_w",
				"rhs_weap_M107_lc",
				"rhs_weap_M107_leu",
				"rhs_weap_M107_d_leu",
				"rhs_weap_M107_w_leu",
				"rhs_weap_M107_premier",
				"rhs_weap_M107_d_premier",
				"rhs_weap_M107_w_premier",

				"rhs_weap_XM2010",
				"rhs_weap_XM2010_d",
				"rhs_weap_XM2010_wd",
				"rhs_weap_XM2010_sa",

				"rhs_weap_m14ebrri",

				"rhs_weap_sr25",
				"rhs_weap_sr25_ec",
				"rhs_weap_sr25_wd",
				"rhs_weap_sr25_ec_wd",
				"rhs_weap_sr25_d",
				"rhs_weap_sr25_ec_d",

				"rhs_weap_m24sws",
				"rhs_weap_m24sws_d",
				"rhs_weap_m24sws_wd",
				"rhs_weap_m24sws_ghillie",
				"rhs_weap_m40a5",
				"rhs_weap_m40a5_d",
				"rhs_weap_m40a5_wd",

				"rhs_weap_t5000",

				"rhs_weap_mk17_STD",
				"rhs_weap_mk17_LB",
				"rhs_weap_SCARH_LB",
				"rhs_weap_SCARH_USA_CQC",
				"rhs_weap_SCARH_USA_STD",
				"rhs_weap_SCARH_USA_LB",

				"rhs_weap_vss",
				"rhs_weap_vss_grip",
				"rhs_weap_vss_npz",
				"rhs_weap_vss_grip_npz",
				"rhs_weap_svd",
				"rhs_weap_svdp",
				"rhs_weap_svdp_npz",
				"rhs_weap_svdp_wd",
				"rhs_weap_svdp_wd_npz",
				"rhs_weap_svds",
				"rhs_weap_svds_npz",

				"UK3CB_BAF_L115A3",
				"UK3CB_BAF_L115A3_BL",
				"UK3CB_BAF_L115A3_DE",
				"UK3CB_BAF_L115A3_Ghillie",
				"UK3CB_BAF_L115A3_BL_Ghillie",
				"UK3CB_BAF_L115A3_DE_Ghillie",
				"UK3CB_BAF_L118A1_Covert",
				"UK3CB_BAF_L118A1_Covert_BL",
				"UK3CB_BAF_L118A1_Covert_DE",
				"UK3CB_BAF_L129A1",
				"UK3CB_BAF_L135A1",
				"UK3CB_BAF_L86A3",

				"rhs_weap_SCARH_STD",
				"rhs_weap_SCARH_FDE_STD",

				"rhs_weap_m82a1",

				"TFC_W_c14",
				"TFC_W_c15a2",
				"TFC_W_c20",

				"ncs_nzdf_dmw",
				"ncs_nzdf_l96a1",
				"ncs_nzdf_mrad",
				"ncs_nzdf_m107",

				"ffaa_armas_cetme_l",
				"ffaa_armas_aw",
				"ffaa_armas_m95",
				"ffaa_armas_aw50",

				"AMF_714_short_01_F",
				"AMF_SCAR_H_01_F",

				"sfp_ag90_base",
				"sfp_psg90_base",
				"sfp_ak4b",

				'CUP_arifle_FNFAL',
				'CUP_arifle_FNFAL_railed',
				'CUP_arifle_FNFAL_desert',
				'CUP_arifle_FNFAL_railed_desert',
				'CUP_arifle_FNFAL_sand',
				'CUP_arifle_FNFAL_railed_sand',
				'CUP_arifle_FNFAL_woodland',
				'CUP_arifle_FNFAL_railed_woodland',
				'CUP_arifle_FNFAL5060',
				'CUP_arifle_FNFAL5060_railed',
				'CUP_arifle_FNFAL5060_rhodesian',
				'CUP_arifle_FNFAL5060_desert',
				'CUP_arifle_FNFAL5060_sand',
				'CUP_arifle_FNFAL5060_woodland',
				'CUP_arifle_FNFAL5060_railed_desert',
				'CUP_arifle_FNFAL5060_railed_sand',
				'CUP_arifle_FNFAL5060_railed_woodland',
				'CUP_arifle_FNFAL5061',
				'CUP_arifle_FNFAL5061_railed',
				'CUP_arifle_FNFAL5061_rhodesian',
				'CUP_arifle_FNFAL5061_wooden',
				'CUP_arifle_FNFAL5061_wooden_railed',
				'CUP_arifle_FNFAL5062',
				'CUP_arifle_FNFAL5062_railed',
				'CUP_arifle_FNFAL_OSW',
				'CUP_arifle_FNFAL_OSW_railed',
				'CUP_arifle_G3_Base',
				'CUP_arifle_G3A3_ris',
				'CUP_arifle_G3A3_ris_vfg',
				'CUP_arifle_G3A3_modern_ris',
				'CUP_arifle_G3A3_ris_black',
				'CUP_arifle_G3A3_ris_vfg_black',
				'CUP_arifle_G3A3_modern_ris_black',
				'CUP_BAF_AS50_scoped',
				'CUP_PMC_AS50_scoped',
				'CUP_BAF_AS50_TWS',
				'CUP_PMC_AS50_TWS',
				'CUP_BAF_LRR_scoped',
				'CUP_BAF_LRR_scoped_W',
				'CUP_arifle_Mk17_Base',
				'CUP_arifle_Mk17_CQC',
				'CUP_arifle_Mk17_CQC_FG',
				'CUP_arifle_Mk17_CQC_AFG',
				'CUP_arifle_Mk17_CQC_SFG',
				'CUP_arifle_Mk17_STD',
				'CUP_arifle_Mk17_STD_FG',
				'CUP_arifle_Mk17_STD_AFG',
				'CUP_arifle_Mk17_STD_SFG',
				'CUP_arifle_Mk20',
				'CUP_arifle_Mk17_CQC_Black',
				'CUP_arifle_Mk17_CQC_FG_black',
				'CUP_arifle_Mk17_CQC_AFG_black',
				'CUP_arifle_Mk17_CQC_SFG_black',
				'CUP_arifle_Mk17_STD_black',
				'CUP_arifle_Mk17_STD_FG_black',
				'CUP_arifle_Mk17_STD_AFG_black',
				'CUP_arifle_Mk17_STD_SFG_black',
				'CUP_arifle_Mk20_black',
				'CUP_arifle_Mk17_CQC_woodland',
				'CUP_arifle_Mk17_CQC_FG_woodland',
				'CUP_arifle_Mk17_CQC_AFG_woodland',
				'CUP_arifle_Mk17_CQC_SFG_woodland',
				'CUP_arifle_Mk17_STD_woodland',
				'CUP_arifle_Mk17_STD_FG_woodland',
				'CUP_arifle_Mk17_STD_AFG_woodland',
				'CUP_arifle_Mk17_STD_SFG_woodland',
				'CUP_arifle_Mk20_woodland',
				'CUP_arifle_Mk17_CQC_SFG_Aim_mfsup',
				'CUP_arifle_Mk17_STD_FG_Aim_Laser_snds',
				'CUP_arifle_Mk17_STD_FG_ANPAS13c1_Laser_Snds',
				'CUP_arifle_Mk20_LeupoldMk4MRT',
				'CUP_arifle_Mk20_SB11420_snds',
				'CUP_arifle_Mk17_STD_woodland_Optic_Laser_bipod_snds',
				'CUP_arifle_Mk17_CQC_woodland_Optic_Laser_bipod_snds',
				'CUP_DMR',
				'CUP_LeeEnfield',
				'CUP_m8_sharpshooter',
				'CUP_arifle_Gewehr1',
				'CUP_arifle_Gewehr1_railed',
				'CUP_SCAR_H_CQC_CCO',
				'CUP_SCAR_H_CQC_CCO_SD',
				'CUP_SCAR_H_LNG_Sniper',
				'CUP_SCAR_H_LNG_Sniper_SD',
				'CUP_SCAR_H_STD_TWS_SD',
				'CUP_SVD',
				'CUP_SVD_CAMO',
				'CUP_SVD_des_EP1',
				'CUP_SVD_NSPU_EP1',
				'CUP_VSS_vintorez',
				'CUP_arifle_ACR_DMR_blk_68',
				'CUP_arifle_ACR_DMR_tan_68',
				'CUP_arifle_ACR_DMR_wdl_68',
				'CUP_arifle_ACR_DMR_snw_68',
				'CUP_arifle_ACR_DMR_blk_556',
				'CUP_arifle_ACR_DMR_tan_556',
				'CUP_arifle_ACR_DMR_wdl_556',
				'CUP_arifle_ACR_DMR_snw_556',
				'CUP_arifle_ACR_DMR_BASE_68',
				'CUP_arifle_ACR_DMR_BASE_556',
				'CUP_srifle_VSSVintorez',
				'CUP_srifle_VSSVintorez_top_rail',
				'CUP_srifle_VSSVintorez_VFG',
				'CUP_srifle_VSSVintorez_VFG_top_rail',
				'CUP_srifle_VSSVintorez_flash',
				'CUP_srifle_VSSVintorez_flash_top',
				'CUP_srifle_CZ750_Base',
				'CUP_srifle_CZ750',
				'CUP_srifle_CZ750_SOS_bipod',
				'CUP_srifle_LeeEnfield',
				'CUP_srifle_LeeEnfield_rail',
				'CUP_srifle_LeeEnfield_T',
				'CUP_srifle_SVD',
				'CUP_srifle_SVD_top_rail',
				'CUP_srifle_SVD_des',
				'CUP_srifle_SVD_wdl',
				'CUP_srifle_SVD_des_top_rail',
				'CUP_srifle_SVD_wdl_top_rail',
				'CUP_srifle_SVD_des_ghillie_pso',
				'CUP_srifle_SVD_wdl_ghillie',
				'CUP_srifle_SVD_pso',
				'CUP_srifle_SVD_Des_pso',
				'CUP_srifle_SVD_NSPU',
				'CUP_srifle_VSSVintorez_pso',
				'CUP_srifle_AS50',
				'CUP_srifle_AS50_SBPMII',
				'CUP_srifle_AS50_AMPAS13c2',
				'CUP_srifle_AWM_Base',
				'CUP_srifle_AWM_des',
				'CUP_srifle_AWM_wdl',
				'CUP_srifle_AWM_blk',
				'CUP_srifle_G22_des',
				'CUP_srifle_G22_wdl',
				'CUP_srifle_G22_blk',
				'CUP_srifle_AWM_des_SBPMII',
				'CUP_srifle_G22_des_SBPMII',
				'CUP_srifle_G22_wdl_SBPMII',
				'CUP_srifle_AWM_wdl_SBPMII',
				'CUP_srifle_CZ550_base',
				'CUP_srifle_CZ550',
				'CUP_srifle_CZ550_rail',
				'CUP_srifle_ksvk',
				'CUP_srifle_ksvk_PSO3',
				'CUP_srifle_L129A1',
				'CUP_srifle_L129A1_HG',
				'CUP_srifle_L129A1_HG_Leupold_Bipod',
				'CUP_srifle_M107_Base',
				'CUP_srifle_M107_Desert',
				'CUP_srifle_M107_Pristine',
				'CUP_srifle_M107_Snow',
				'CUP_srifle_M107_Woodland',
				'CUP_srifle_M107_LeupoldVX3',
				'CUP_srifle_M107_LeupoldMk4',
				'CUP_srifle_M107_ANPAS13c2',
				'CUP_srifle_M107_LeupoldMk4_10x40',
				'CUP_srifle_M107_Woodland_LeupoldMk4_25x50',
				'CUP_srifle_M110',
				'CUP_srifle_M110_black',
				'CUP_srifle_M110_woodland',
				'CUP_srifle_m110_kac',
				'CUP_srifle_m110_kac_black',
				'CUP_srifle_m110_kac_woodland',
				'CUP_srifle_M110_ANPAS13c2',
				'CUP_srifle_M110_ANPVS10',
				'CUP_srifle_M110_Shortdot_bipod_snds',
				'CUP_srifle_M14',
				'CUP_srifle_M21',
				'CUP_srifle_M21_ris',
				'CUP_srifle_M14_CCO',
				'CUP_srifle_M14_LeupoldMk4_snd',
				'CUP_srifle_M14_LeupoldMk4',
				'CUP_srifle_M21_artel',
				'CUP_srifle_M14_DMR',
				'CUP_srifle_M14_DMR_LeupoldMk4',
				'CUP_srifle_M14_DMR_LeupoldMk4_snds',
				'CUP_srifle_DMR',
				'CUP_srifle_DMR_LeupoldMk4',
				'CUP_srifle_DMR_LeupoldMk4_snds',
				'CUP_arifle_DSA_SA58_DMR',
				'CUP_srifle_Mk12SPR',
				'CUP_srifle_Mk12SPR_LeupoldM3LR',
				'CUP_srifle_Mk12SPR_LeupoldM3LR_bipod',
				'CUP_srifle_M24_des',
				'CUP_srifle_M24_wdl',
				'CUP_srifle_M24_ghillie',
				'CUP_srifle_M24_blk',
				'CUP_srifle_M40A3',
				'CUP_srifle_M24_des_LeupoldMk4LRT',
				'CUP_srifle_M24_wdl_LeupoldMk4LRT',
				'CUP_srifle_M24_blk_LeupoldMk4LRT',
				'CUP_srifle_M24_ghillie_bipod',
				'CUP_srifle_M40A3_bipod',
				'CUP_srifle_M24_wdl_leupoldmk4_camo_bipod_snd',
				'CUP_srifle_Mosin_Nagant',
				'CUP_srifle_Mosin_Nagant_PEM',
				'CUP_srifle_Remington700',
				'CUP_srifle_Remington700_scoped',
				'CUP_srifle_RSASS_BASE',
				'CUP_srifle_RSASS_Black',
				'CUP_srifle_RSASS_WDL',
				'CUP_srifle_RSASS_WDLNet',
				'CUP_srifle_RSASS_Sand',
				'CUP_srifle_RSASS_Dazzle',
				'CUP_srifle_RSASS_Winter',
				'CUP_srifle_RSASS_Jungle',
				'CUP_srifle_RSASS_Black_LRPS_Flashlight',
				'CUP_srifle_Mk18_sage',
				'CUP_srifle_Mk18_des',
				'CUP_srifle_Mk18_blk',
				'CUP_M4SPR',
				'CUP_M24',
				'CUP_M24_des_EP1',
				'CUP_M40A3',
				'CUP_M107',
				'CUP_M107_TWS_EP1',
				'CUP_M110_TWS_EP1',
				'CUP_M110_NVG_EP1',
				'CUP_BAF_L110A1_Aim',
				'CUP_arifle_HK417_Base',
				'CUP_arifle_HK417_20',
				'CUP_arifle_HK417_20_Wood',
				'CUP_arifle_HK417_20_Desert',
				'CUP_arifle_HK417_12',
				'CUP_arifle_HK417_12_Wood',
				'CUP_arifle_HK417_12_Desert',
				'CUP_arifle_HK417_20_Laser_Scope_Silenced',
				'CUP_arifle_HK417_20_Scope',
				'CUP_arifle_HK417_20_Laser_Scope',
				'CUP_srifle_Mk18_wdl',

				'ACR_A3_CZ_BREN2_762_14',
				'ACR_A3_CZ_BREN2_762_8',
				'ACR_A3_arifle_CZ805_B_GL',
				'ACR_A3_arifle_CZ805_B',
				'ACR_A3_srifle_CZ750',
				'ACR_A3_srifle_CZ750_SOS',
				'ACR_A3_srifle_CZ550',
				'ACR_A3_srifle_CZ550_rail',

				'ffp_TKiv2000',

				'APD_ARX200_base',
				'APD_ARX200',
				'ASZ_ARX200_AG',
				'APD_ARX200_VGrip',
				'APD_ARX200sf',
				'ASZ_ARX200sf_AG',
				'APD_ARX200sf_VGrip',
				'ASZ_SakoTRG42_base',
				'ASZ_SakoTRG42',
				'ASZ_SakoTRG42_SB',
				'ASZ_M40A3_Green_base',
				'ASZ_M40A3_Green_ghillie',
				'ASZ_M40A3_Green_ghillie_Leu',
				'ASZ_M40A3_Green',
				'ASZ_M40A3_Green_Leu',
				'ASZ_M40A3_Des_ghillie',
				'ASZ_M40A3_Des_ghillie_Leu',
				'ASZ_M40A3_Des',
				'ASZ_M40A3_Des_Leu',
				'ASZ_M107_base',
				'ASZ_M107_Blk',
				'ASZ_M107_Leu',
				'ASZ_M107_des',
				'ASZ_M107_des_Leu',
				'ASZ_MCM_tac50_base',
				'ASZ_MCM_tac50_blk',
				'ASZ_MCM_tac50_blk_leu',
				'ASZ_MCM_tac50_des',
				'ASZ_MCM_tac50_des_leu',
				'ASZ_MCM_tac50_green',
				'ASZ_MCM_tac50_green_leu',

				'BWA3_G28',
				'BWA3_G27',
				'BWA3_G27_tan',
				'BWA3_G27_AG40',
				'BWA3_G27_AG40_tan',
				'BWA3_G29',
				'BWA3_G82',

				'arifle_jpa_hk417c',
				'arifle_jpa_hk417_m203c',
				'srifle_jpa_hk417',
				'srifle_jpa_m24',
				
				'OPTRE_BR55HB',
				'OPTRE_BR55',
				'OPTRE_BR45',
				'OPTRE_M295_BMR',
				'OPTRE_M295_BMR_Woodland',
				'OPTRE_M295_BMR_Snow',
				'OPTRE_M295_BMR_Snow_Desert',
				'OPTRE_M392_DMR',
				'OPTRE_M393_DMR',
				'OPTRE_M393S_DMR',
				'OPTRE_M99A2S3',
				'OPTRE_SRS99D',
				'OPTRE_SRS99C',
				'OPTRE_SRM77_S1',
				'OPTRE_FC_T50_SRS',
				'OPTRE_FC_T51_Carbine',
				'OPTRE_M58S',
				'OPTRE_BR37',


				'UK3CB_Enfield',
				'UK3CB_Enfield_Rail',
				'UK3CB_SVD_OLD',
				'UK3CB_SVD_OLD_NPZ',
				'UK3CB_FNFAL_FULL',
				'UK3CB_G3KA4',
				'UK3CB_G3A3_RIS',
				'UK3CB_G3A3V_RIS',
				'UK3CB_G3KA4_GL',
				'UK3CB_G3SG1_RIS',
				'UK3CB_PSG1A1_RIS',
				'UK3CB_M14',
				'UK3CB_M14DMR',
				'UK3CB_M14DMR_Railed',
				'UK3CB_M21',
				'UK3CB_M14_artel',
				'UK3CB_M14_artel_sup',
				'UK3CB_M14DMR_Railed_Acog',
				'UK3CB_M14DMR_Railed_SOS',
				'UK3CB_M14DMR_Railed_SOS_sup',
				'UK3CB_M21_artel',
				'UK3CB_M21_artel_sup',
				'UK3CB_G3KA4_aco_grn',
				'UK3CB_G3A3_RIS_aco_grn',
				'UK3CB_G3A3V_RIS_aco_grn',
				'UK3CB_G3KA4_GL_aco_grn',
				'UK3CB_G3SG1_RIS_erco',
				'UK3CB_G3SG1_RIS_aco_grn',
				'UK3CB_G3A3V_RIS_aco_grn_sup',
				'UK3CB_M14DMR_artel_sup',
				'UK3CB_Enfield_Rail_KHS',
				'UK3CB_Enfield_Rail_KHS_bipod',
				'UK3CB_Enfield_Rail_KHS_bipod_sup',
				'UK3CB_FNFAL_FULL_SUIT',
				'UK3CB_FNFAL_FULL_SUIT_SUP',
				'UK3CB_PSG1A1',
				'UK3CB_M14_Railed',
				'UK3CB_M21_Bipod_Railed',
				'UK3CB_FNFAL_PARA',
				'UK3CB_G3SG1',
				'UK3CB_PSG1A1_RIS_erco_sup',
				'UK3CB_PSG1A1_RIS_SOS_sup',
				'uk3cb_weap_svd_old_pso1m2',
				'uk3cb_weap_svd_old_pso1m2_sup',
				'UK3CB_G3SG1_RIS_aco_grn_sup',

				'CSLA_HuntingRifle',
				'US85_FAL',
				'US85_FALf',
				'CSLA_OP63',
				'CSLA_OP63n',
				'US85_M21',

				'gm_g3a4_ebr_oli',
				'gm_g3a4_ebr_blk',
				'gm_g3a4_ebr_des',
				'gm_g3a3_dmr_oli',
				'gm_g3a3_dmr_blk',
				'gm_g3a3_dmr_des',		
				'gm_svd_wud',
				
				'LIB_M1903A4_Springfield',
				'LIB_K98ZF39',
				'LIB_LeeEnfield_No4_Scoped_CUP',
				"LIB_LeeEnfield_No4_Scoped",
				'LIB_M9130PU',
				'LIB_PTRD',
				'CSA38_boys',
				
				'fow_w_m1903A1_sniper',
				'fow_w_k98_scoped',
				'fow_w_type99_sniper',
				
				'vn_m40a1',
				'vn_m40a1_camo',
				'vn_m40a1_sniper',
				'vn_m40a1_sniper_sd',
				'vn_m40a1_nvg',
				'vn_m40a1_nvg_sd',
				'vn_m4956',
				'vn_m4956_bayo',
				'vn_m4956_sniper',
				'vn_m4956_gl',
				'vn_m9130_sniper',
				"vn_m3carbine",
				
				'ADFU_HK417',
				
				'SMA_Mk17_16_black',
				'SMA_Mk17_16_Green',
				'SMA_Mk17_16',
				
				'SMA_HK417_16in',
				
				"Tier1_M110k1",
				
				'srifle_EBR_blk_tws_bpd_blk_lxWS',
				"srifle_EBR_blk_lxWS"
		
			];

			_autoRiflemanGear = [
				
				'arifle_CTARS_blk_flash_F',		
				'arifle_CTARS_blk_F',
				'arifle_CTARS_hex_F',
				'arifle_CTARS_ghex_F',
				'arifle_CTARS_blk_Pointer_F',
				
				'LMG_Mk200_F',
				'LMG_Mk200_MRCO_F',
				'LMG_Mk200_pointer_F',
				
				'LMG_Zafir_F',
				'LMG_Zafir_pointer_F',
				'LMG_Zafir_ARCO_F',
				
				'LMG_Mk200_LP_BI_F',
				'LMG_Mk200_BI_F',
				'LMG_Mk200_black_F',
				'LMG_Mk200_black_ACO_pointer_F',
				'LMG_Mk200_black_LP_BI_F',
				'LMG_Mk200_black_BI_F',
				
				'MMG_01_hex_F',
				'MMG_01_tan_F',
				'MMG_01_hex_ARCO_LP_F',
				
				'MMG_02_camo_F',
				'MMG_02_black_F',
				'MMG_02_sand_F',
				'MMG_02_sand_RCO_LP_F',
				'MMG_02_black_RCO_BI_F',
				
				'arifle_RPK12_F',
				'arifle_RPK12_lush_F',
				'arifle_RPK12_arid_F',	
				'arifle_RPK12_lush_arco_snds_pointer_F',
				'arifle_RPK12_lush_holo_snds_pointer_F',
				'arifle_RPK12_lush_arco_pointer_F',
				
				'arifle_SPAR_02_blk_F',
				'arifle_SPAR_02_khk_F',
				'arifle_SPAR_02_snd_F',
				
				'LMG_03_F',
				'LMG_03_Vehicle_F',
				
				'arifle_MX_SW_Black_F',
				'arifle_MX_SW_khk_F',
				'arifle_MX_SW_khk_Pointer_F',
				'arifle_MX_SW_Black_Hamr_pointer_F',	
				'arifle_MX_SW_pointer_F',
				'arifle_MX_SW_Hamr_pointer_F',
				'arifle_MX_SW_F',
				'arifle_MX_SW_Black_Pointer_F',

				"rhs_weap_m27iar",
				"rhs_weap_m27iar_grip",
				"rhs_weap_m249",
				"rhs_weap_m249_pip_S",
				"rhs_weap_m249_pip_S_para",
				"rhs_weap_m249_light_S",
				"rhs_weap_m249_pip",
				"rhs_weap_m249_pip_ris",
				"rhs_weap_m249_pip_L",
				"rhs_weap_m249_pip_L_para",
				"rhs_weap_m249_light_L",
				"rhs_weap_m240B",
				"rhs_weap_m240G",

				"rhs_weap_pkp",
				"rhs_weap_pkm",
				"rhs_weap_rpk74",
				"rhs_weap_rpk74m",
				"rhs_weap_rpk74m_npz",

				"UK3CB_BAF_L110_Base",
				"UK3CB_BAF_L110_762_Base",
				"UK3CB_BAF_L110_556_Base",
				"UK3CB_BAF_L110A1",
				"UK3CB_BAF_L110A2",
				"UK3CB_BAF_L110A2RIS",
				"UK3CB_BAF_L110A3",
				"UK3CB_BAF_L110_762",
				"UK3CB_BAF_L86A2",
				"UK3CB_BAF_L7A2",
				"rhs_weap_minimi_para_railed",
				"rhs_weap_m249_light_L",
				"rhs_weap_fnmag",

				"rhs_weap_m84",

				"TFC_W_mk48_e",
				"TFC_W_c6",
				"TFC_W_c6a1",
				"TFC_W_C9A2_e",

				"ncs_nzdf_maximi",
				"ncs_nzdf_c9_cqb",
				"ncs_nzdf_mag58_1",

				"ffaa_armas_mg4",
				"ffaa_armas_ameli",
				"ffaa_armas_mg3",
				"ffaa_armas_minimi",

				"AMF_MINI_MG_01_F",

				"sfp_ksp90c",
				"sfp_ksp58B2",

				'CUP_M60E4_base',
				'CUP_arifle_MG36',
				'CUP_arifle_MG36_camo',
				'CUP_arifle_MG36_wdl',
				'CUP_arifle_MG36_hex',
				'CUP_BAF_L86A2_ACOG',
				'CUP_lmg_MG3',
				'CUP_lmg_MG3_rail',
				'CUP_lmg_MG3_M145',
				'CUP_lmg_UK59',
				'CUP_lmg_M240',
				'CUP_lmg_M240_norail',
				'CUP_lmg_M240_B',
				'CUP_lmg_L7A2',
				'CUP_lmg_L7A2_Flat',
				'CUP_lmg_FNMAG',
				'CUP_lmg_FNMAG_RIS',
				'CUP_lmg_FNMAG_RIS_modern',
				'CUP_lmg_M240_ElcanM143',
				'CUP_lmg_M240_B_ElcanM143_ANPEQ15',
				'CUP_saw_base',
				'CUP_lmg_minimipara',
				'CUP_lmg_minimi',
				'CUP_lmg_m249_para',
				'CUP_lmg_M249_E2',
				'CUP_lmg_minimi_railed',
				'CUP_lmg_m249_pip1',
				'CUP_lmg_M249',
				'CUP_lmg_m249_pip2',
				'CUP_lmg_m249_pip3',
				'CUP_lmg_m249_pip4',
				'CUP_lmg_m249_SQuantoon',
				'CUP_lmg_L110A1',
				'CUP_lmg_M249_E1',
				'CUP_lmg_M249_ElcanM145_Laser',
				'CUP_lmg_M249_ElcanM145',
				'CUP_lmg_M249_Laser',
				'CUP_lmg_M249_ANPAS13c2_Laser',
				'CUP_lmg_L110A1_Aim_Laser',
				'CUP_lmg_minimi_railed_ElcanM145',
				'CUP_lmg_M60E4',
				'CUP_lmg_M60E4_norail',
				'CUP_lmg_M60E4_wood',
				'CUP_lmg_M60E4_norail_wood',
				'CUP_lmg_M60E4_jungle',
				'CUP_lmg_M60E4_norail_jungle',
				'CUP_lmg_M60E4_desert',
				'CUP_lmg_M60E4_norail_desert',
				'CUP_lmg_M60',
				'CUP_lmg_M60E4_jungle_Aimpoint_Laser',
				'CUP_lmg_Mk48_Base',
				'CUP_lmg_Mk48',
				'CUP_lmg_Mk48_des',
				'CUP_lmg_Mk48_wdl',
				'CUP_lmg_Mk48_tan',
				'CUP_lmg_Mk48_od',
				'CUP_lmg_Mk48_nohg',
				'CUP_lmg_Mk48_nohg_des',
				'CUP_lmg_Mk48_nohg_wdl',
				'CUP_lmg_Mk48_nohg_tan',
				'CUP_lmg_Mk48_nohg_od',
				'CUP_lmg_Mk48_des_Aim_Laser',
				'CUP_lmg_Mk48_Aim_Laser',
				'CUP_lmg_Mk48_wdl_Aim_Laser',
				'CUP_lmg_PKM',
				'CUP_lmg_PKMN',
				'CUP_lmg_Pecheneg',
				'CUP_lmg_PKM_top_rail',
				'CUP_lmg_PKM_B50_vfg',
				'CUP_lmg_PKM_front_rail_B50_vfg',
				'CUP_lmg_PKM_top_rail_B50_vfg',
				'CUP_lmg_Pecheneg_top_rail',
				'CUP_lmg_Pecheneg_B50_vfg',
				'CUP_lmg_Pecheneg_top_rail_B50_vfg',
				'CUP_lmg_Pecheneg_desert',
				'CUP_lmg_Pecheneg_woodland',
				'CUP_lmg_Pecheneg_PScope',
				'CUP_M240',
				'CUP_m240_scoped_EP1',
				'CUP_Pecheneg',
				'CUP_M249_m145_EP1',
				'CUP_M249_EP1',
				'CUP_M249_TWS_EP1',
				'CUP_M249',
				'CUP_arifle_L86A2',
				'CUP_arifle_L86A2_ACOG',
				'CUP_arifle_HK_M27',
				'CUP_arifle_HK_M27_VFG',
				'CUP_arifle_M27_ACOG',
				'CUP_BAF_L7A2_GPMG',
				'CUP_Mk_48_DES_EP1',
				'CUP_Mk_48',
				'CUP_RPK_74',
				'CUP_arifle_RPK74M_1p78',
				'CUP_arifle_RPK74',
				'CUP_arifle_RPK74_top_rail',
				'CUP_arifle_RPK74_45',
				'CUP_arifle_RPK74_45_top_rail',
				'CUP_arifle_RPK74M',
				'CUP_arifle_RPK74M_top_rail',
				'CUP_arifle_RPK74M_railed',
				'CUP_arifle_xm8_SAW',

				'ACR_A3_lmg_UK59',

				'ffp_kk_pkm',
				'ffp_KVKK',
				'ffp_kk_pkm_old',

				'ASZ_M249_base',
				'ASZ_M249',
				'ASZ_M249_rd',
				'ASZ_M249mk1_base',
				'ASZ_M249mk1',
				'ASZ_M249mk1_rd',

				'BWA3_MG3',
				'BWA3_MG4',
				'BWA3_MG5',
				'BWA3_MG5_tan',

	
				'OPTRE_M247',
				'OPTRE_M73',

				'UK3CB_RPK',
				'UK3CB_RPK_74',
				'UK3CB_RPK_74_BLK',
				'UK3CB_RPK_74N',
				'UK3CB_RPK_74N_BLK',
				'UK3CB_M60',
				'UK3CB_MG3',
				'UK3CB_MG3_Railed',
				'UK3CB_MG3_KWS_T',
				'UK3CB_MG3_KWS_B',
				'UK3CB_MG3_KWS_G',
				'UK3CB_Bren',
				'UK3CB_M16A1_LSW',

				'US85_M249',
				'US85_M60',
				'CSLA_UK59L',
				'CSLA_UK59Lp',

				'gm_mg3_blk',
				'gm_mg3_des',
				'gm_lmgm62_blk',
				'gm_hmgpkm_prp',
				'gm_lmgrpk_brn',
				'gm_lmgrpk_prp',
				'gm_lmgrpk74n_brn',
				'gm_lmgrpk74n_prp',
				'gm_rpk_wud',
				
				'LIB_M1919A4',
				'LIB_M1918A2_BAR',
				'LIB_M1918A2_BAR_Bipod',
				'LIB_M1918A2_BAR_Handle',
				'LIB_M1919A6',
				'LIB_DT',
				'LIB_DT_OPTIC',
				'LIB_DP28',
				'LIB_Bren_Mk2',
				'LIB_MG42',
				'LIB_MG34',
				
				'fow_w_m1918a2',
				'fow_w_m1918a2_bak',
				'fow_w_m1918a2_acc',
				'fow_w_m1918a2_bak_acc',
				'fow_w_M1912',
				'fow_w_m1919a4',
				'fow_w_m1919a6',
				'fow_w_mg34',
				'fow_w_mg42',
				'fow_w_type99_lmg',
				'fow_w_bren',
				"LIB_PPSh41_d",				
				"LIB_M1928_Thompson_d",
				
				'vn_dp28',
				'vn_m60',
				'vn_m60_shorty',
				'vn_m60_shorty_camo',
				'vn_pk',
				'vn_rpd',
				'vn_rpd_shorty',
				'vn_rpd_shorty_01',
				"vn_m63a_cdo",
				"vn_m63a_lmg",

				'ADFU_MAG58',
				'ADFU_minimi',
				'ADFU_minimi_para',
				'ADFU_Maximi',

				'sma_minimi_mk3_762tlb',
				'sma_minimi_mk3_762tlb_des',
				'sma_minimi_mk3_762tlb_wdl',
				'sma_minimi_mk3_762tsb',
				'sma_minimi_mk3_762tsb_des',
				'sma_minimi_mk3_762tsb_wdl',

				"hlc_lmg_mk48",
				"hlc_lmg_mk46",
				"hlc_lmg_M60E4",
				"hlc_rifle_M27IAR",
				
				'LMG_MK200_Holosight_blk_lxWS',
				'LMG_MK200_black_Holosight_lxWS',
				
				'arifle_XMS_M_lxWS',
				'arifle_XMS_M_khk_lxWS',
				'arifle_XMS_M_Sand_lxWS',
				
				'arifle_XMS_M_MRCO_bipod_lxWS',
				'arifle_XMS_M_MRCO_lxWS',
				'arifle_XMS_M_TWS_bipod_lxWS',
				'arifle_XMS_M_Holosight_bipod_lxWS',
				'arifle_XMS_M_Holosight_lxWS',
				
				"vn_l2a1_01",
				"vn_m1918"
				
			];


			_ATgear = [

				// Tier 3 - AT and up

					// Vanilla

						"launch_O_Vorona_brown_F",
						"launch_O_Vorona_green_F",

						"launch_O_Titan_short_F",
						"launch_O_Titan_short_ghex_F",
						"launch_I_Titan_short_F",
						"launch_B_Titan_short_F",
						"launch_B_Titan_short_tna_F",


					// RHS


						"rhs_weap_mk40_sraw",
						"rhs_weap_mk41_sraw",

						"rhs_weap_fgm148",


					// NZDF

						"ncs_nzdf_launch_Javelin",


					// CUP

						'CUP_launch_M47',
						'CUP_launch_Javelin',
						'CUP_launch_Metis',

						'CUP_launch_PzF3',
						'CUP_launch_BF3',
						'CUP_launch_HCPF3',


					// FFP

						'ffp_ito15',


					// ASZ

						'ASZ_PzF3',
						'ASZ_PzF3_Loaded',
						'ASZ_pzf3_used',

					// BWMod

						'BWA3_PzF3',
						'BWA3_PzF3_Tandem_Loaded',
						'BWA3_Bunkerfaust',
						'BWA3_Bunkerfaust_Loaded',
						'BWA3_PzF3_Used',


					// JSDF

						"gac_JSDF_W_LMAT",


					// OPTRE

						'OPTRE_M41_SSR_G',
						'OPTRE_FC_T33_FuelRod_Cannon_Guided',


					// CSLA

						'US85_M47',


					//	GM

						'gm_pzf3_blk'

			];


			_engineerGear = [

				// Tier 2 - Engineer and up

					// Vanilla

						"launch_MRAWS_green_rail_F",
						"launch_MRAWS_olive_rail_F",
						"launch_MRAWS_sand_rail_F",
						"launch_MRAWS_green_F",
						"launch_MRAWS_olive_F",
						"launch_MRAWS_sand_F",

						"launch_RPG32_F",
						"launch_RPG32_green_F",
						"launch_RPG32_ghex_F",

						"launch_RPG7_F",

						"launch_I_Titan_F",
						"launch_I_Titan_eaf_F",
						"launch_O_Titan_ghex_F",
						"launch_O_Titan_F",
						"launch_B_Titan_F",
						"launch_B_Titan_tna_F",
						"launch_B_Titan_olive_F",


					// RHS

						"rhs_weap_rpg7",
						"rhs_weap_rpg7_pgo",
						"rhs_weap_rpg7_1pn93",

						"rhs_weap_fim92",
						"rhs_weap_igla",

						"rhs_weap_smaw",
						"rhs_weap_smaw_green",
						"rhs_weap_smaw_optic",
						"rhs_weap_smaw_gr_optic",

						"rhs_weap_maaws",
						"rhs_weap_maaws_optic",


					// CUP

						'CUP_launch_RPG7V',
						'CUP_launch_9K32Strela',
						'CUP_launch_Igla',
						'CUP_launch_FIM92Stinger',

						'CUP_launch_MAAWS',
						'CUP_launch_MAAWS_Scope',

						'CUP_launch_Mk153Mod0',
						'CUP_launch_Mk153Mod0_blk',
						'CUP_launch_Mk153Mod0_SMAWOptics',
						'CUP_launch_Mk153Mod0_blk_SMAWOptics',


					// SFP

						"sfp_grg86",
						"sfp_rbs69",


					// OPTRE

						'OPTRE_M41_SSR',
						'OPTRE_FC_T33_FuelRod_Cannon',


					// ASZ

						'ASZ_Launch_Stinger',


					// BWMod

						'BWA3_CarlGustav',
						'BWA3_CarlGustav_Optic',

						'BWA3_Fliegerfaust',


					// NZDF

						"ncs_nzdf_carl_gustav",


					// JSDF

						"gac_JSDF_W_rr_110mm",
						"gac_JSDF_W_rr_84mm",
						"jpa_JSDF_W_rr_84mm",


					// Prairie Fire
					
						'vn_rpg2',
						'vn_rpg7',
						'vn_sa7',
						'vn_sa7b',
						"uns_m20_bazooka",

					// CSLA

						'CSLA_RPG7',
						'CSLA_RPG7V',
						'CSLA_9K32',
						'US85_SMAW',
						'US85_MAAWS',
						'US85_FIM92',

					// GM

						'gm_pzf84_oli',
						'gm_pzf84_des',
						'gm_pzf84_win',
						'gm_fim43_oli',
						'gm_pzf44_2_oli',
						'gm_pzf44_2_des',
						'gm_pzf44_2_win',
						'gm_rpg7_prp',
						'gm_rpg7_wud',
						'gm_9k32m_oli',
						'gm_strela_launcher',
						'gm_p2a1_launcher_blk',
					
					
					// IFA3
					
						'LIB_M2_Flamethrower',
						'LIB_M1A1_Bazooka',
						'LIB_PIAT',
						'LIB_RPzB',
						'LIB_PIAT_Rifle',
						
						
					// Faces Of War 
					
						'fow_w_piat'

			];


			_GLGear = [

				'arifle_MX_GL_F',
				'arifle_MX_GL_ACO_F',
				'arifle_MX_GL_ACO_pointer_F',
				'arifle_MX_GL_Hamr_pointer_F',
				'arifle_MX_GL_Black_Hamr_pointer_F',
				'arifle_MX_GL_Black_F',
				'arifle_MX_GL_khk_F',
				'arifle_MX_GL_khk_ACO_F',
				'arifle_MX_GL_khk_Hamr_Pointer_F',
				'arifle_MX_GL_khk_Holo_Pointer_Snds_F',
				'arifle_MX_GL_Black_ACO_F',
				'arifle_MX_GL_Black_Holo_Pointer_Snds_F',
				'arifle_MX_GL_Holo_pointer_snds_F',		
				
				'arifle_MSBS65_GL_ico_pointer_f',
				'arifle_MSBS65_GL_black_ico_pointer_f',
				'arifle_MSBS65_GL_black_ico_F',
				'arifle_MSBS65_GL_ico_F',
				'arifle_MSBS65_GL_camo_F',
				'arifle_MSBS65_GL_sand_F',
				'arifle_MSBS65_GL_F',
				'arifle_MSBS65_GL_black_F',
				
				'arifle_SPAR_01_GL_blk_F',
				'arifle_SPAR_01_GL_khk_F',
				'arifle_SPAR_01_GL_snd_F',
				
				'arifle_Mk20_GL_MRCO_pointer_F',
				'arifle_Mk20_GL_ACO_F',
				
				'arifle_Katiba_GL_F',
				'arifle_Katiba_GL_ACO_F',
				'arifle_Katiba_GL_ARCO_pointer_F',
				'arifle_Katiba_GL_ACO_pointer_F',
				'arifle_Katiba_GL_Nstalker_pointer_F',
				'arifle_Katiba_GL_ACO_pointer_snds_F',
				
				'arifle_CTAR_GL_blk_aco_flash_F',
				'arifle_CTAR_GL_blk_arco_flash_F',
				'arifle_CTAR_GL_blk_F',
				'arifle_CTAR_GL_hex_F',
				'arifle_CTAR_GL_ghex_F',
				'arifle_CTAR_GL_blk_ACO_F',
				'arifle_CTAR_GL_blk_ARCO_Pointer_F',
				'arifle_CTAR_GL_blk_ACO_Pointer_Snds_F',
				
				'arifle_AK12_GL_F',
				'arifle_AK12_GL_lush_arco_snds_pointer_F',
				'arifle_AK12_GL_lush_holo_snds_pointer_F',
				'arifle_AK12_GL_lush_arco_pointer_F',
				'arifle_AK12_GL_lush_holo_pointer_F',
				'arifle_AK12_GL_lush_F',
				'arifle_AK12_GL_arid_F',
				
				'arifle_TRG21_GL_MRCO_F',
				'arifle_TRG21_GL_ACO_pointer_F',
				'arifle_TRG21_GL_F',
				
				'arifle_Mk20_GL_F',
				'arifle_Mk20_GL_plain_F',

				"rhs_weap_ak74n_2_gp25",
				"rhs_weap_ak74n_2_gp25_npz",
				"rhs_weap_aks74_gp25",
				"rhs_weap_aks74n_gp25",
				"rhs_weap_aks74n_gp25_npz",
				"rhs_weap_akms_gp25",
				"rhs_weap_ak103_gp25",
				"rhs_weap_ak103_gp25_npz",
				"rhs_weap_ak74n_gp25",
				"rhs_weap_ak74_gp25",
				"rhs_weap_ak74n_gp25_npz",
				"rhs_weap_akm_gp25",
				"rhs_weap_akmn_gp25",
				"rhs_weap_akmn_gp25_npz",
				"rhs_weap_ak74m_fullplum_gp25",
				"rhs_weap_ak74m_fullplum_gp25_npz",
				"rhs_weap_ak74m_gp25",
				"rhs_weap_ak74mr_gp25",
				"rhs_weap_ak74m_gp25_npz",

				"rhs_weap_m4_m320",
				"rhs_weap_m4_m203",
				"rhs_weap_m4_m203S",
				"rhs_weap_m4_carryhandle_m203",
				"rhs_weap_m4_carryhandle_m203S",
				"rhs_weap_m4a1_m203",
				"rhs_weap_m4a1_m203s",
				"rhs_weap_m4a1_m203s_wd",
				"rhs_weap_m4a1_m203s_d",
				"rhs_weap_m4a1_m203s_sa",
				"rhs_weap_m4a1_carryhandle_m203",
				"rhs_weap_m4a1_carryhandle_m203S",
				"rhs_weap_m4a1_m320",
				"rhs_weap_m4a1_blockII_M203",
				"rhs_weap_m4a1_blockII_M203_bk",
				"rhs_weap_m4a1_blockII_M203_d",
				"rhs_weap_m4a1_blockII_M203_wd",
				"rhs_weap_m16a4_carryhandle_M203",
				"rhs_weap_m16a4_imod_M203",

				"rhs_weap_m32",
				"rhs_weap_m32_usmc",
				"rhs_weap_M320",

				"rhs_weap_m79",
				"rhs_weap_vhsd2_bg",
				"rhs_weap_vhsd2_bg_ct15x",
				"rhs_weap_m21a_pbg40",
				"rhs_weap_m21a_pr_pbg40",
				"rhs_weap_m70b3n_pbg40",

				"UK3CB_BAF_L85A2_UGL",
				"UK3CB_BAF_L85A2_UGL_HWS",
				"UK3CB_BAF_L85A3_UGL",
				"UK3CB_BAF_L119A1_UKUGL",

				"rhs_weap_hk416d10_m320",
				"rhs_weap_hk416d145_m320",
				"rhs_weap_mk18_m320",

				"rhs_weap_g36kv_ag36",

				"TFC_W_c8a3_m203",
				"tfc_w_c7a2_m203",

				"ncs_nzdf_steyr_a1_gl",
				"ncs_nzdf_marsl_gl",
				"ncs_nzdf_m4a1_gl",

				"ffaa_armas_hkag36e_tir",
				"ffaa_armas_hkag36e",
				"ffaa_armas_hkag36k_tir",
				"ffaa_armas_hkag36k",

				"AMF_614_long_HK269_01_F",

				"sfp_ak5_m203",

				'CUP_arifle_DSA_SA58_OSW_M203',
				'CUP_arifle_Colt727_M203',
				'CUP_arifle_mk18_m203_black',
				'CUP_arifle_M4A1_M203_Holo_Laser',
				'CUP_arifle_M4A1_M203_CCO_Laser',
				'CUP_arifle_M4A1_M203_ACOG_Laser',
				'CUP_arifle_M4A1_M203_ANPAS13c1_Laser',
				'CUP_arifle_mk18_m203_tan_holo_laserflash',
				'CUP_arifle_mk18_m203_elcan_laserflash',
				'CUP_arifle_Colt727_M203_snd',
				'CUP_arifle_M16A4_GL_Laser',
				'CUP_arifle_M16A4_GL_ACOG_Laser',
				'CUP_arifle_M4A1_GL_Holo_Laser',
				'CUP_arifle_M4A1_GL_Holo_Flashlight',
				'CUP_arifle_M4A1_GL_ACOG_Flashlight',
				'CUP_arifle_Mk16_STD_EGLM',
				'CUP_arifle_Mk16_CQC_EGLM',
				'CUP_arifle_Mk16_CQC_EGLM_black',
				'CUP_arifle_Mk16_CQC_EGLM_woodland',
				'CUP_arifle_Mk16_STD_EGLM_woodland',
				'CUP_arifle_Mk17_CQC_EGLM',
				'CUP_arifle_Mk17_STD_EGLM',
				'CUP_arifle_Mk17_CQC_EGLM_black',
				'CUP_arifle_Mk17_STD_EGLM_black',
				'CUP_arifle_Mk17_CQC_EGLM_woodland',
				'CUP_arifle_Mk16_CQC_EGLM_Holo_Laser_mfsup',
				'CUP_arifle_Mk17_STD_EGLM_woodland',
				'CUP_AK_74_GL',
				'CUP_AK_74_GL_kobra',
				'CUP_CZ805_A1_GL_ACR',
				'CUP_AK_107_GL_kobra',
				'CUP_AK_107_GL_pso',
				'CUP_arifle_Mk16_STD_EGLM_ACOG_Laser',
				'CUP_arifle_Mk16_STD_EGLM_Specter',
				'CUP_arifle_Mk16_STD_EGLM_ANPAS13c1_Laser_mfsup',
				'CUP_arifle_Mk16_STD_EGLM_woodland_Elcan_Laser_snds',
				'CUP_arifle_Mk16_STD_EGLM_woodland_Holo_Laser_snds',
				'CUP_arifle_Mk17_STD_EGL_ElcanSpecter_Laser',
				'CUP_BAF_L85A2_UGL_Holo',
				'CUP_BAF_L85A2_UGL_SUSAT',
				'CUP_BAF_L85A2_UGL_ACOG',
				'CUP_M16A2GL',
				'CUP_M16A4_GL',
				'CUP_M16A4_ACG_GL',
				'CUP_M4A3_RCO_GL_EP1',
				'CUP_M4A1_HWS_GL',
				'CUP_M4A1_RCO_GL',
				'CUP_M4A1_HWS_GL_camo',
				'CUP_M4A1_HWS_GL_SD_Camo',
				'CUP_SCAR_L_CQC_EGLM_Holo',
				'CUP_SCAR_L_STD_EGLM_RCO',
				'CUP_SCAR_L_STD_EGLM_TWS',
				'CUP_SCAR_H_STD_EGLM_Spect',
				'CUP_arifle_ACR_EGLM_blk_68',
				'CUP_arifle_ACR_EGLM_tan_68',
				'CUP_arifle_ACR_EGLM_wdl_68',
				'CUP_arifle_ACR_EGLM_snw_68',
				'CUP_arifle_ACRC_EGLM_blk_68',
				'CUP_arifle_ACRC_EGLM_tan_68',
				'CUP_arifle_ACRC_EGLM_wdl_68',
				'CUP_arifle_ACRC_EGLM_snw_68',
				'CUP_arifle_ACR_EGLM_BASE_68',
				'CUP_arifle_ACR_EGLM_SHORT_BASE_68',
				'CUP_arifle_ACR_EGLM_blk_556',
				'CUP_arifle_ACR_EGLM_tan_556',
				'CUP_arifle_ACR_EGLM_wdl_556',
				'CUP_arifle_ACR_EGLM_snw_556',
				'CUP_arifle_ACRC_EGLM_blk_556',
				'CUP_arifle_ACRC_EGLM_tan_556',
				'CUP_arifle_ACRC_EGLM_wdl_556',
				'CUP_arifle_ACRC_EGLM_snw_556',
				'CUP_arifle_ACR_EGLM_BASE_556',
				'CUP_arifle_ACR_EGLM_SHORT_BASE_556',
				'CUP_CZ_BREN2_556_14_GL',
				'CUP_CZ_BREN2_556_11_GL',
				'CUP_CZ_BREN2_762_14_GL',
				'CUP_CZ_BREN2_556_14_GL_Tan',
				'CUP_CZ_BREN2_556_14_GL_Grn',
				'CUP_CZ_BREN2_556_11_GL_Tan',
				'CUP_CZ_BREN2_556_11_GL_Grn',
				'CUP_CZ_BREN2_762_14_GL_Tan',
				'CUP_CZ_BREN2_762_14_GL_Grn',
				'CUP_arifle_AK47_GL',
				'CUP_arifle_AKM_GL',
				'CUP_arifle_AKM_GL_top_rail',
				'CUP_arifle_AKM_GL_Early',
				'CUP_arifle_AKMS_GL',
				'CUP_arifle_AKMS_GL_top_rail',
				'CUP_arifle_AKMS_GL_Early',
				'CUP_arifle_AK47_GL_top_rail',
				'CUP_arifle_AK47_GL_Early',
				'CUP_arifle_AK74_GL',
				'CUP_arifle_AK74_GL_top_rail',
				'CUP_arifle_AK74_GL_Early',
				'CUP_arifle_AKS74_GL',
				'CUP_arifle_AKS74_GL_top_rail',
				'CUP_arifle_AKS74_GL_Early',
				'CUP_arifle_AK74M_GL',
				'CUP_arifle_AK74M_GL_top_rail',
				'CUP_arifle_AK74M_GL_railed',
				'CUP_arifle_AK74M_GL_desert',
				'CUP_arifle_AK74M_GL_top_rail_desert',
				'CUP_arifle_AK74M_GL_railed_desert',
				'CUP_arifle_AK74M_GL_camo',
				'CUP_arifle_AK74M_GL_top_rail_camo',
				'CUP_arifle_AK74M_GL_railed_camo',
				'CUP_arifle_AK101_GL',
				'CUP_arifle_AK101_GL_top_rail',
				'CUP_arifle_AK101_GL_railed',
				'CUP_arifle_AK103_GL',
				'CUP_arifle_AK103_GL_top_rail',
				'CUP_arifle_AK103_GL_railed',
				'CUP_arifle_AK107_GL',
				'CUP_arifle_AK107_GL_top_rail',
				'CUP_arifle_AK107_GL_railed',
				'CUP_arifle_AK108_GL',
				'CUP_arifle_AK108_GL_top_rail',
				'CUP_arifle_AK108_GL_railed',
				'CUP_arifle_AK109_GL',
				'CUP_arifle_AK109_GL_top_rail',
				'CUP_arifle_AK109_GL_railed',
				'CUP_arifle_G36A_AG36_RIS',
				'CUP_arifle_G36A_AG36_RIS_camo',
				'CUP_arifle_G36A_AG36_RIS_wdl',
				'CUP_arifle_G36A3_AG36',
				'CUP_arifle_G36A3_AG36_camo',
				'CUP_arifle_G36A3_AG36_wdl',
				'CUP_arifle_G36A3_AG36_hex',
				'CUP_arifle_G36K_RIS_AG36',
				'CUP_arifle_G36K_RIS_AG36_camo',
				'CUP_arifle_G36K_RIS_AG36_wdl',
				'CUP_arifle_G36K_RIS_AG36_hex',
				'CUP_arifle_G36K_AG36',
				'CUP_arifle_G36K_AG36_camo',
				'CUP_arifle_G36K_AG36_wdl',
				'CUP_arifle_HK416_CQB_AG36',
				'CUP_arifle_HK416_CQB_AG36_Desert',
				'CUP_arifle_HK416_CQB_AG36_Wood',
				'CUP_arifle_HK_M27_AG36',
				'CUP_arifle_HK417_12_AG36',
				'CUP_arifle_HK417_12_AG36_Wood',
				'CUP_arifle_HK417_12_AG36_Desert',
				'CUP_arifle_HK416_CQB_AG36_Desert_G33_snds_las',
				'CUP_arifle_HK416_CQB_AG36_Wood_G33_snds_las',
				'CUP_arifle_AG36',
				'CUP_arifle_AG36_camo',
				'CUP_arifle_AG36_wdl',
				'CUP_CZ_BREN2_GL_Base',
				'CUP_CZ_BREN2_762_GL_Base',
				'CUP_arifle_M4A1_GL_carryhandle',
				'CUP_arifle_M4A1_GL_carryhandle_camo',
				'CUP_arifle_M4A1_GL_carryhandle_desert',
				'CUP_arifle_M4A1_BUIS_GL',
				'CUP_arifle_M4A1_BUIS_camo_GL',
				'CUP_arifle_M4A1_BUIS_desert_GL',
				'CUP_arifle_AK107_GL_kobra',
				'CUP_arifle_AK107_GL_pso',
				'CUP_arifle_AK74_GL_kobra',
				'CUP_arifle_AK74_GL_EKP',
				'CUP_arifle_AK74M_GL_kobra',
				'CUP_arifle_AK74M_GL_EKP',
				'CUP_arifle_AK74M_GL_kobra_snds',
				'CUP_arifle_AK74M_GL_pso',
				'CUP_arifle_AK74M_GL_pso_open',
				'CUP_arifle_AK74M_GL_1p63',
				'CUP_arifle_CZ805_GL',
				'CUP_arifle_CZ805_GL_blk',
				'CUP_arifle_CZ805_GL_coyote',
				'CUP_arifle_XM8_Carbine_GL',
				'CUP_arifle_CZ805_GL_Hamr_Laser',
				'CUP_arifle_CZ805_GL_ZDDot_Laser',
				'CUP_arifle_OTS14_GROZA_GL',
				'CUP_arifle_OTS14_GROZA_762_GL',
				'CUP_arifle_HK416_M203_Black',
				'CUP_arifle_HK416_M203_Desert',
				'CUP_arifle_HK416_M203_Wood',
				'CUP_arifle_HK416_CQB_M203_Black',
				'CUP_arifle_HK416_CQB_M203_Desert',
				'CUP_arifle_HK416_CQB_M203_Wood',
				'CUP_arifle_HK417_12_M203',
				'CUP_arifle_HK417_12_M203_Wood',
				'CUP_arifle_HK417_12_M203_Desert',
				'CUP_m8_carbineGL',
				'CUP_arifle_L85A2_GL',
				'CUP_arifle_L85A2_GL_ACOG_Laser',
				'CUP_arifle_L85A2_GL_Holo_Laser',
				'CUP_arifle_L85A2_GL_SUSAT_Laser',
				'CUP_arifle_L85A2_GL_Elcan_Laser',
				'CUP_arifle_M16A1GL',
				'CUP_arifle_M16A1GL_USA',
				'CUP_arifle_M16A1GL_FS',
				'CUP_arifle_M16A2_GL',
				'CUP_arifle_M16A4_GL',
				'CUP_arifle_M16A1E1GL',
				'CUP_arifle_HK416_AGL_Black',
				'CUP_arifle_HK416_AGL_Desert',
				'CUP_arifle_HK416_AGL_Wood',
				'CUP_l85a2_ugl',
				'CUP_arifle_M4A3_desert_GL_ACOG_Laser',
				'CUP_arifle_M4A1_camo_GL_Holo_Flashlight',
				'CUP_arifle_M4A1_camo_GL_Holo_Flashlight_Snds',
				'CUP_lmg_m249_para_gl',
				'CUP_arifle_Sa58RIS2_gl',
				'CUP_arifle_Sa58RIS2_gl_desert',
				'CUP_arifle_Sa58RIS2_gl_woodland',
				'CUP_arifle_Mk16_STD_EGLM_black',
				'CUP_glaunch_Base',
				'CUP_glaunch_M32',
				'CUP_glaunch_M79',
				'CUP_glaunch_Mk13',
				'CUP_glaunch_6G30',

				'ACR_A3_CZ_BREN2_556_14_GL',
				'ACR_A3_CZ_BREN2_556_14_GL_ACO',
				'ACR_A3_CZ_BREN2_556_11_GL',
				'ACR_A3_CZ_BREN2_762_14_GL',
				'ACR_A3_arifle_CZ805_GL',

				'ASZ_AR7090_gl',
				'ASZ_SC90_gl',
				'ASZ_SC90_gl_ag',
				'ASZ_ARX160_GLS',
				'ASZ_ARX160_AG_GLS',
				'ASZ_ARX160_GLS_CC',
				'ASZ_ARX160_AG_GLS_CC',
				'ASZ_ARX160SF_GLS',
				'ASZ_ARX160SF_AG_GLS',
				'ASZ_ARX160SF_GLS_CC',
				'ASZ_ARX160SF_AG_GLS_CC',
				'ASZ_M32',
				'ASZ_Mk13',
				'ASZ_GrenadeLauncher',

				'BWA3_G36A1_AG40',
				'BWA3_G36A1_AG40_tan',
				'BWA3_G36A1_AG40_green',
				'BWA3_G38_AG40',
				'BWA3_G38_AG40_tan',
				'BWA3_G36A2_AG40',
				'BWA3_G36A2_AG40_tan',
				'BWA3_G36A2_AG40_green',
				'BWA3_G36A3_AG40',
				'BWA3_G36A3_AG40_tan',
				'BWA3_G36A3_AG40_green',
				'BWA3_G38K_AG40',
				'BWA3_G38K_AG40_tan',

				'arifle_jpa_hk416_m203',
				'arifle_jpa_hk416_m203c',

				'OPTRE_M319',
				'OPTRE_M319n',
				'OPTRE_M319m',
				'OPTRE_M319s',
				'OPTRE_MA32GL',
				'OPTRE_MA32BGL',
				'OPTRE_MA5BGL',
				'OPTRE_MA5CGL',
				'OPTRE_MA5AGL',
				'OPTRE_MA37GL',
				'OPTRE_MA37BGL',

				'UK3CB_M79',
				'UK3CB_M16A2_UGL',
				'UK3CB_HK33KA2_RIS_GL',
				'UK3CB_HK33KA2_RIS_GL_aco_grn_sup',
				'UK3CB_M16A2_UGL_eotech_552',
				'UK3CB_M16A2_UGL_sup',

				'CSLA_VG70',
				'US85_M16A2GL',
				'US85_M16A2CARGL',

				'gm_pallad_d_brn',
				'gm_hk69a1_blk',
				'gm_akm_pallad_wud',
				
				'vn_m79',
				'vn_xm177_xm148',
				'vn_xm177_xm148_camo',
				'vn_m1carbine_gl',
				'vn_m2carbine_gl',
				'vn_sks_gl',
				'vn_m79_p',
				"vn_m16_xm148",
				
				'ADFU_Steyr_F88_GL',
				'ADFU_SteyrEF88_GL',
				'ADFU_F88SA1_gl',
				'ADFU_f88sa2_gl',
				'ADFU_f88sa2_gl_camo',
				'ADFU_m4a5_gl',
				
				'SMA_AUG_EGLM_Olive',
				'SMA_AUG_EGLM_tan',
				'SMA_AUG_EGLM',
				'SMA_ACRREMGL_N',
				'SMA_ACRREMGL_B_N',
				'SMA_ACRREMCQBGL_N',
				'SMA_ACRREMCQBGL_B_N',
				'SMA_ACRGL',
				'SMA_ACRGL_B',
				'SMA_ACRREMGL',
				'SMA_ACRREMGL_B',
				'SMA_ACRREMCQBGL',
				'SMA_ACRREMCQBGL_B',
				'SMA_HK416GL',
				'SMA_HK416GLCQB',
				'SMA_HK416GLCQB_B',
				'SMA_HK416GLCQB_ODP',
				'SMA_HK416GLOD',
				'SMA_HK416CQBGLOD',
				'SMA_HK416_GL_ODPAINTED',
				'SMA_M4_GL',
				'SMA_M4_GL_SM',
				'SMA_MK18_GL',
				'SMA_MK18_GL_SM',
				'SMA_MK18TANBLK_GL',
				'SMA_MK18TANBLK_GL_SM',
				'SMA_MK18TAN_GL',
				'SMA_MK18TAN_GL_SM',
				'SMA_MK18BLK_GL',
				'SMA_MK18BLK_GL_SM',
				'SMA_MK18ODBLK_GL',
				'SMA_MK18ODBLK_GL_SM',
				'SMA_MK18OD_GL',
				'SMA_MK18OD_GL_SM',
				'SMA_Mk16_EGLM',
				'SMA_MK16_EGLM_black',
				'SMA_MK16_EGLM_Green',
	
				'SMA_Mk17_EGLM',
				'SMA_MK17_EGLM_black',
				'SMA_MK17_EGLM_Green',
				
				"hlc_rifle_m4m203",
				"hlc_smg_9mmar",
				
				'arifle_XMS_GL_ACO_lxWS',
				'arifle_XMS_GL_lxWS',
				'arifle_XMS_GL_khk_lxWS',
				'arifle_XMS_GL_Sand_lxWS',
				'arifle_SLR_V_GL_lxWS',
				'arifle_SLR_GL_lxWS',
				
				"vn_m16_m203",
				"vn_l1a1_01_gl",
				"vn_l1a1_xm148",
				
				"vn_xm16e1_xm148",
				"vn_l1a1_xm148_camo",
				"vn_m1_garand_gl",
				"vn_m16_m203_camo"
				
			];

			
			if (BEW_v_WW2) then {
			
				_TLGear = [

					'LIB_M1A1_Thompson',
					'LIB_MP44',
					"LIB_MP44_GW",
					'LIB_PPSh41_m',
					'LIB_M1928_Thompson',
					"LIB_M1928A1_Thompson",
					'LIB_FG42G',
					
					'fow_w_fg42',
					'fow_w_stg44',
					'fow_w_m1a1_thompson',
					'fow_w_m1_thompson',

					'vn_ppsh41',
					'vn_m1a1_tommy',
					'vn_m1a1_tommy_so',
					"vn_m1928_tommy",
					"vn_m1928a1_tommy"					

				];
				
			}else{
				
				_TLGear = [];
				
			};
			
		
		private _classnames = [["B_soldier_M_F"], ["B_soldier_AR_F"], ["B_soldier_AT_F"], ["B_soldier_AT_F", "B_engineer_F"], ["B_Soldier_TL_F", "B_Soldier_GL_F"], ["B_Soldier_TL_F", "B_soldier_AR_F"]];
		
		if (BEW_v_Zombies) then {
		
			_classnames = [["B_Soldier_F", "B_Soldier_TL_F"], ["B_Soldier_F", "B_Soldier_TL_F"], ["B_Soldier_F", "B_Soldier_TL_F"], ["B_Soldier_F", "B_Soldier_TL_F"], ["B_Soldier_F", "B_Soldier_TL_F"], ["B_Soldier_F", "B_Soldier_TL_F"]];
		
		};
		
		_restrictedLists = [_marksmanGear, _autoRiflemanGear, _ATgear, _engineerGear, _GLGear, _TLGear];

		_returnArray = [_classnames, _restrictedLists];

		_returnArray
