
		_arsenalHeadgear = [	
			
			'Jp_Helmet_M88_Jeitai',
			'Jp_Helmet_M88_Desert_Jeitai',
			'Jp_Helmet_M88_D_Modern_Jeitai',
			'JP_T66Helmet_Jeitai',
			'JP_T66Helmet_Jeitai_Desert',
			'JP_T66Helmet_Jeitai_Desert_2012',
			'JP_Mk7Helmet_Jeitai',
			'JP_Mk7Helmet_Jeitai_Desert',
			'JP_Mk7Helmet_Jeitai_Desert_2012',
			'Japan_JP_Jeitai_Casque_Pilot_Tan',
			'Japan_JP_Jeitai_Casque_Pilot',
			'Japan_JP_Jeitai_Helmet',
			'Japan_JP_Jeitai_Helmet_Light',
			'Japan_JP_Jeitai_D_Helmet',
			'Japan_JP_Jeitai_D_Helmet_Light',
			'Japan_JP_Jeitai_Desert_2012_Helmet',
			'Japan_JP_Jeitai_Desert_2012_Helmet_Light',
			
			"FIR_ScorpionHMCS"
			
		];
		
		
		_arsenalGoggles = [

			"G_AirPurifyingRespirator_01_F",
			"G_Balaclava_blk",
			"G_Balaclava_combat",
			"G_Balaclava_lowprofile",
			"G_Balaclava_oli",
			"G_Balaclava_TI_blk_F",
			"G_Balaclava_TI_G_blk_F",
			"G_Balaclava_TI_G_tna_F",
			"G_Balaclava_TI_tna_F",
			"G_Combat",
			"G_Combat_Goggles_tna_F",
			"G_B_Diving",
			"G_Lowprofile",
			"G_Tactical_Black",
			"G_Tactical_Clear"
			
		];
		
		
		_arsenalUniforms = [
		
			'Japan_JP_Jeitai_Uniform_Vest',
			'Japan_JP_Jeitai_Uniform_D_Vest',
			'Japan_JP_Jeitai_Uniform_Desert_Moderne_Vest',
			'Japan_JP_Jeitai_Uniform_Tshirt',
			'Japan_JP_Jeitai_Uniform_D_Tshirt',
			'Japan_JP_Jeitai_Uniform_Desert_Moderne_Tshirt',
			'Japan_JP_Jeitai_Uniform',
			'Japan_JP_Jeitai_Uniform_D',
			'Japan_JP_Jeitai_Uniform_D_Moderne',
			'Japan_JP_Jeitai_Uniform_Light_tshirt',
			'Japan_JP_Jeitai_Uniform_D_Light_tshirt',
			'Japan_JP_Jeitai_Uniform_D_Moderne_Light_tshirt',
			'Japan_JP_Jeitai_Uniform_base',
			'Japan_JP_Jeitai_Uniform_D_base',
			'Japan_JP_Jeitai_Uniform_Desert_2012_base',
			'Japan_JP_Jeitai_Uniform_Pilot',
			
			"U_B_Wetsuit"

		];

		
		_arsenalVests = [
		
		
			'V_Heavy_Deltaforce_Jeitai',
			'V_Heavy_Deltaforce_Desert_Jeitai',
			'V_Heavy_Deltaforce_D_Modern_Jeitai',
			'V_Deltaforce_Jeitai',
			'V_Deltaforce_Desert_Jeitai',
			'V_Deltaforce_D_Modern_Jeitai',
			'Japan_Jeitai_TacVestIR_blk',
			'Japan_Jeitai_Desert_TacVestIR_blk',
			'Japan_Jeitai_Desert_Moderne_TacVestIR_blk',
			'Japan_Jeitai_Digital_TacVestIR_blk',
			'Japan_Jeitai_Navy_TacVestIR_blk',
			'Japan_Jeitai_Kaki_TacVestIR_blk',
			'Japan_Jeitai_Tan_TacVestIR_blk',
			'Japan_Jeitai_Grey_TacVestIR_blk',
			'Japan_Jeitai_Black_TacVestIR_blk',
			'Japan_Bust_Armor_Jeitai',
			'Japan_Bust_Armor_Jeitai_Desert',
			'Japan_Bust_Armor_Jeitai_Desert_2012',
			'Japan_Jeitai_PlateCarrier1',
			'Japan_Jeitai_PlateCarrier2',
			'Japan_Jeitai_Desert_PlateCarrier1',
			'Japan_Jeitai_Desert_PlateCarrier2',
			'Japan_Jeitai_Desert_Moderne_PlateCarrier1',
			'Japan_Jeitai_Desert_Moderne_PlateCarrier2',
			'Japan_Jeitai_Tan_PlateCarrier1',
			'Japan_Jeitai_Tan_PlateCarrier2',
			'Japan_Jeitai_Kaki_PlateCarrier1',
			'Japan_Jeitai_Kaki_PlateCarrier2',
			'Japan_Jeitai_Grey_PlateCarrier1',
			'Japan_Jeitai_Grey_PlateCarrier2',
			'Japan_Jeitai_Black_PlateCarrier1',
			'Japan_Jeitai_Black_PlateCarrier2',
			'Japan_Jeitai_Black2_PlateCarrier1',
			'Japan_Jeitai_Black2_PlateCarrier2',
			'Japan_Jeitai_Black3_PlateCarrier1',
			'Japan_Jeitai_Black3_PlateCarrier2',
			'Japan_JP_PlateCarrierGL_Jeitai',
			'Japan_JP_PlateCarrierSpec_Jeitai',
			'Japan_JP_PlateCarrierGL_Jeitai_Desert',
			'Japan_JP_PlateCarrierSpec_Jeitai_Desert',
			'Japan_JP_PlateCarrierGL_Jeitai_Desert_2012',
			'Japan_JP_PlateCarrierSpec_Jeitai_Desert_2012',
			'Japan_JP_PlateCarrierIAGL_Jeitai',
			'Japan_JP_PlateCarrierIAGL_Jeitai_Desert',
			'Japan_JP_PlateCarrierIAGL_Jeitai_Desert_2012',
			'Japan_Jeitai_PlateCarrier_l',
			'Japan_Jeitai_PlateCarrier_2',
			'Japan_Jeitai_PlateCarrier_D_l',
			'Japan_Jeitai_PlateCarrier_D_2',
			'Japan_Jeitai_PlateCarrier_Desert_Moderne_l',
			'Japan_Jeitai_PlateCarrier_Desert_Moderne_2',
			
			"V_RebreatherB"

		];
		
		

		_arsenalBackpacks = [

			'Japan_JP_Jeitai_FieldPack',
			'Japan_JP_Jeitai_Desert_FieldPack',
			'Japan_JP_Jeitai_Desert_2012_FieldPack',
			'Japan_JP_Jeitai_Kitbag',
			'Japan_JP_Jeitai_Desert_Kitbag',
			'Japan_JP_Jeitai_Desert_2012_Kitbag',
			'Japan_JP_Jeitai_Carryall',
			'Japan_JP_Jeitai_Desert_Carryall',
			'Japan_JP_Jeitai_Desert_2012_Carryall',
			'Japan_JP_Jeitai_Medic',
			'Japan_JP_Jeitai_Desert_Medic',
			'Japan_JP_Jeitai_Desert_2012_Medic',
			'BackPack_Vest_Jeitai',
			'BackPack_Vest_Jeitai_Desert',
			'BackPack_Vest_Jeitai_Desert_Moderne',
			'BackPack_Belt_Jeitai',
			'BackPack_Belt_Jeitai_Desert',
			'BackPack_Belt_Jeitai_Desert_Moderne',
			'JP_Viper_Jeitai',
			'JP_Viper_Jeitai_Desert',
			'JP_Viper_Jeitai_D_2012',
			'JP_Viper_Light_Jeitai',
			'JP_Viper_Light_Jeitai_Desert',
			'JP_Viper_Light_Jeitai_D_2012',
				
			"B_Parachute",	
			"B_UAV_01_backpack_F",
			"B_UAV_06_medical_backpack_F",
			"B_UAV_06_backpack_F",
			"B_UGV_02_Demining_backpack_F",
			"B_UGV_02_Science_backpack_F",					
			"B_Mortar_01_weapon_F",
			"B_Mortar_01_support_F",			
			"B_Static_Designator_01_weapon_F"
			
		];


		_arsenalNvgoggles = [

			'Jp_Goggles_NV',
			'Jp_Goggles_NV_Tan',
			'Jp_Goggles_NV_Kaki',
			'Jp_Goggles_NV_O',
			'Jp_Goggles_NV_Tan_O',
			'Jp_Goggles_NV_Kaki_O',
			'JP_NVG_blk',
			'JP_NVG_blk_clr',
			'JP_NVG_tan',
			'JP_NVG_tan_clr',
			'JP_NVG_grn',
			'JP_NVG_grn_clr',
			'NVGoggles_jpa_h'

		];


		_arsenalPrimaryAttachments = [

		
			"rhsusf_acc_harris_bipod",
			"rhsusf_acc_harris_swivel",
			"rhsusf_acc_saw_bipod",
			"rhsusf_acc_saw_lw_bipod",
			"rhsusf_acc_m14_bipod",
			"rhsusf_acc_grip1",
			"rhsusf_acc_grip2",
			"rhsusf_acc_grip3",
			"rhsusf_acc_grip4",
			"rhsusf_acc_grip4_bipod",
			"rhsusf_acc_rvg_blk",
			"rhsusf_acc_tacsac_blk",
			"rhsusf_acc_tdstubby_blk",
			"rhsusf_acc_kac_grip",
			"rhsusf_acc_kac_grip_saw_bipod",
			"rhs_acc_at4_handler",
			"rhsusf_acc_anpeq15A",
			"rhsusf_acc_anpeq15_bk",
			"rhsusf_acc_anpeq15_h",
			"rhsusf_acc_anpeq15_sc",
			"rhsusf_acc_anpeq15_bk_h",
			"rhsusf_acc_anpeq15_bk_sc",
			"rhsusf_acc_anpeq15_bk_light",
			"rhsusf_acc_anpeq15_light_h",
			"rhsusf_acc_anpeq15_light_sc",
			"rhsusf_acc_anpeq15_bk_light_h",
			"rhsusf_acc_anpeq15_bk_light_sc",
			"rhsusf_acc_anpeq15_wmx_h",
			"rhsusf_acc_anpeq15_wmx_light_h",
			"rhsusf_acc_anpeq15_wmx_sc",
			"rhsusf_acc_anpeq15_wmx_light_sc",
			"rhsusf_acc_anpeq15_bk_top",
			"rhsusf_acc_anpeq15_top_h",
			"rhsusf_acc_anpeq15_bk_top_h",
			"rhsusf_acc_anpeq15_top_sc",
			"rhsusf_acc_anpeq15_bk_top_sc",
			"rhsusf_acc_anpeq15side_bk",
			"rhsusf_acc_anpeq16a",
			"rhsusf_acc_anpeq16a_light",
			"rhsusf_acc_anpeq16a_top",
			"rhsusf_acc_anpeq16a_light_top",
			"rhsusf_acc_anpeq16a_top_h",
			"rhsusf_acc_anpeq16a_light_top_h",
			"rhsusf_acc_anpeq16a_top_sc",
			"rhsusf_acc_anpeq16a_light_top_sc",
			"rhsusf_acc_M952V",			
			"rhsusf_acc_wmx_bk",
			"rhsusf_acc_M2010S",
			"rhsusf_acc_M2010S_sa",
			"rhsusf_acc_SR25S",
			"rhsusf_acc_rotex5_grey",
			"rhsusf_acc_nt4_black",
			"rhsusf_acc_omega9k",
			"rhsusf_acc_rotex_mp7",
			"rhsusf_acc_muzzleFlash_ar15",
			"rhsusf_acc_muzzleFlash_SF3P556",
			"rhsusf_acc_muzzleFlash_SFMB556",
			"rhsusf_acc_muzzleFlash_ardec_m240",
			"rhsusf_acc_muzzleFlash_M14_USGI_NM",
			"rhsusf_m4muzzlebreak_base",
			"rhsusf_acc_SF3P556",
			"rhsusf_acc_SFMB556",
			"rhsusf_acc_ARDEC_M240",
			"rhsusf_acc_m14_flashsuppresor",
			"rhsusf_acc_m24_silencer_black",
			"rhsusf_acc_m24_muzzlehider_black",
			"rhsusf_acc_aac_scarh_silencer",
			"rhsusf_acc_aac_762sd_silencer",
			"rhsusf_acc_aac_762sdn6_silencer",
			"rhsusf_acc_aac_m14dcqd_silencer",
			"rhsusf_acc_sniper_base",
			"rhsusf_acc_compm4",
			"rhsusf_acc_T1_high",
			"rhsusf_acc_T1_low",
			"rhsusf_acc_T1_low_fwd",
			"rhsusf_acc_T1_low_fwd_ak",
			"rhsusf_acc_RX01",
			"rhsusf_acc_RX01_NoFilter",
			"rhsusf_acc_RM05",
			"rhsusf_acc_RM05_fwd",
			"rhsusf_acc_RM05_fwd_ak",
			"rhsusf_acc_mrds",
			"rhsusf_acc_mrds_fwd",
			"rhsusf_acc_mrds_fwd_ak",
			"rhsusf_acc_eotech_552",
			"rhsusf_acc_anpvs27",
			"rhsusf_acc_anpas13gv1",
			"rhsusf_acc_LEUPOLDMK4",
			"rhsusf_acc_ELCAN",
			"rhsusf_acc_ELCAN_ard",
			"rhsusf_acc_elcan_3d",
			"rhsusf_acc_elcan_ard_3d",
			"rhsusf_acc_ELCAN_pip",
			"rhsusf_acc_ELCAN_ard_pip",
			"rhsusf_acc_su230_base",
			"rhsusf_acc_su230_base_3d",
			"rhsusf_acc_su230_mrds_base",
			"rhsusf_acc_su230_mrds_base_3d",
			"rhsusf_acc_su230",
			"rhsusf_acc_su230_3d",
			"rhsusf_acc_su230_mrds",
			"rhsusf_acc_su230_mrds_3d",
			"rhsusf_acc_su230a",
			"rhsusf_acc_su230a_3d",
			"rhsusf_acc_su230a_mrds",
			"rhsusf_acc_su230a_mrds_3d",
			"rhsusf_acc_SpecterDR",
			"rhsusf_acc_SpecterDR_D",
			"rhsusf_acc_SpecterDR_OD",
			"rhsusf_acc_SpecterDR_CX",
			"rhsusf_acc_SpecterDR_A",
			"rhsusf_acc_SpecterDR_3d",
			"rhsusf_acc_SpecterDR_D_3D",
			"rhsusf_acc_SpecterDR_OD_3D",
			"rhsusf_acc_SpecterDR_A_3d",
			"rhsusf_acc_SpecterDR_CX_3D",
			"rhsusf_acc_SpecterDR_pvs27",
			"rhsusf_acc_ACOG",
			"rhsusf_acc_ACOG_sa",
			"rhsusf_acc_ACOG2",
			"rhsusf_acc_ACOG3",
			"rhsusf_acc_ACOG_USMC",
			"rhsusf_acc_ACOG2_USMC",
			"rhsusf_acc_ACOG3_USMC",
			"rhsusf_acc_ACOG_RMR",
			"rhsusf_acc_ACOG_3d",
			"rhsusf_acc_ACOG_sa_3d",
			"rhsusf_acc_ACOG2_3d",
			"rhsusf_acc_ACOG3_3d",
			"rhsusf_acc_ACOG_USMC_3d",
			"rhsusf_acc_ACOG2_USMC_3d",
			"rhsusf_acc_ACOG3_USMC_3d",
			"rhsusf_acc_ACOG_RMR_3d",
			"rhsusf_acc_ACOG_pip",
			"rhsusf_acc_ACOG_sa_pip",
			"rhsusf_acc_ACOG2_pip",
			"rhsusf_acc_ACOG3_pip",
			"rhsusf_acc_ACOG_USMC_pip",
			"rhsusf_acc_ACOG2_USMC_pip",
			"rhsusf_acc_ACOG3_USMC_pip",
			"rhsusf_acc_ACOG_RMR_pip",
			"rhsusf_acc_ACOG_anpvs27",
			"rhsusf_acc_LEUPOLDMK4_2",
			"rhsusf_acc_LEUPOLDMK4_2_mrds",
			"rhsusf_acc_premier",
			"rhsusf_acc_premier_mrds",
			"rhsusf_acc_premier_low",
			"rhsusf_acc_premier_anpvs27",
			"rhsusf_acc_M8541",
			"rhsusf_acc_M8541_mrds",
			"rhsusf_acc_M8541_low",
			"rhsusf_acc_M2A1",
			"rhsusf_acc_eotech_xps3",
			"rhsusf_acc_g33_xps3",
			"rhsusf_acc_g33_xps3_flip",
			"rhsusf_acc_g33_T1",
			"rhsusf_acc_g33_T1_flip",
			"rhs_weap_optic_smaw",
			"rhs_weap_optic_smaw_1",
			"rhs_weap_optic_smaw_2",
			"rhs_weap_optic_smaw_3",
			"rhs_weap_optic_smaw_4",
			"rhs_weap_optic_smaw_5",
			"rhs_weap_optic_smaw_6",
			"rhs_weap_optic_smaw_7",
			"rhs_weap_optic_smaw_8",
			"rhs_weap_optic_smaw_9",
			"rhs_weap_optic_smaw_10",
			
			"acc_flashlight",
			"acc_pointer_IR",
			
			'jpa_optic_JGSDF_MAAWS_heat',
			'acc_jpa_flash_gun',
			'acc_jpa_pointer_gun_IR',
			'muzzle_jpa_snds_L',
			'muzzle_jpa_snds_SH',
			'optic_jpa_zeiss',
			'optic_jpa_zeiss_eo',
			'optic_jpa_acog',
			'optic_jpa_acog_eo',
			'jpa_APAV'
		
		];


		_arsenalSecondaryAttachments = [

		];
		
		_arsenalExplosives = [
		
			"SatchelCharge_Remote_Mag",
			"DemoCharge_Remote_Mag",
			"SLAMDirectionalMine_Wire_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellGreen",
			"SmokeShellYellow",
			"SmokeShellPurple",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_yellow",
			"Chemlight_blue",
			"B_IR_Grenade",
			"Laserbatteries"
		
		];


		_arsenalItems = [
		
			"rhsusf_bino_lerca_1200_black",
			"rhsusf_bino_lerca_1200_tan",
			"lerca_1200_black",
			"lerca_1200_tan",
			"rhsusf_bino_lrf_Vector21",
			"rhsusf_lrf_Vector21",
			"rhsusf_bino_leopold_mk4",
			"Leupold_Mk4",
			"rhsusf_bino_m24",
			"rhsusf_bino_m24_ARD",
			"m24_bino",
			"m24_bino_ARD",
			
			"ItemGPS",
			"B_UavTerminal",
			"Laserdesignator",
			"MineDetector",
			"Binocular",
			"FirstAidKit",
			"ItemCompass",
			"Rangefinder",
			"ItemWatch",
			"ToolKit",
			"ItemRadio",
			"Medikit",
			"ItemMap"

		];
				
		_return = [_arsenalHeadgear, _arsenalGoggles, _arsenalUniforms, _arsenalVests, _arsenalBackpacks, _arsenalNvgoggles, _arsenalPrimaryAttachments, _arsenalSecondaryAttachments, _arsenalExplosives, _arsenalItems];
		
		_return
