// RIFLES

	// AR
		
		'gm_g36a1_blk',
		'gm_g36a1_des',
		'gm_g36e_blk',
		'gm_c7a1_blk',
		'gm_c7a1_oli',
		'gm_akm_wud',
		'gm_akmn_wud',
		'gm_m16a1_blk',
		'gm_m16a2_blk',
		'gm_mpikm72_brn',
		'gm_mpikm72_prp',
		'gm_mpikms72_brn',
		'gm_mpikms72_prp',
		'gm_gvm95_blk',
		'gm_mpiak74n_brn',
		'gm_mpiak74n_prp',
		'gm_mpiaks74n_brn',
		'gm_mpiaks74n_prp',
		'gm_mpiaks74nk_brn',
		'gm_mpiaks74nk_prp',
	
	// BR
	
		'gm_g3a3_oli',
		'gm_g3a3_blk',
		'gm_g3a3_grn',
		'gm_g3a3_des',
		'gm_g3a4_oli',
		'gm_g3a4_blk',
		'gm_g3a4_grn',
		'gm_g3a4_des',
		'gm_gvm75_oli',
		'gm_gvm75_blk',
		'gm_gvm75_grn',
		'gm_gvm75carb_oli',
		'gm_gvm75carb_blk',
		'gm_gvm75carb_grn',
	
	// DMR
	
		'gm_g3a4_ebr_oli',
		'gm_g3a4_ebr_blk',
		'gm_g3a4_ebr_des',
		'gm_g3a3_dmr_oli',
		'gm_g3a3_dmr_blk',
		'gm_g3a3_dmr_des',		
		'gm_svd_wud'
	
	// SMG
		
		'gm_mp2a1_blk',
		'gm_mp5a2_blk',
		'gm_mp5a3_blk',
		'gm_mp5sd2_blk',
		'gm_mp5sd3_blk',
		'gm_pm63_blk',
	
	// LMG
		
		'gm_mg3_blk',
		'gm_mg3_des',
		'gm_lmgm62_blk',
		'gm_hmgpkm_prp',
		'gm_lmgrpk_brn',
		'gm_lmgrpk_prp',
		'gm_lmgrpk74n_brn',
		'gm_lmgrpk74n_prp',
		'gm_rpk_wud',
	
	
	// GL
	
		'gm_pallad_d_brn',		
		'gm_hk69a1_blk',
		'gm_akm_pallad_wud',


// HANDGUNS

'gm_lp1_blk',
'gm_p1_blk',
'gm_p2a1_blk',
'gm_wz78_blk',
'gm_pm_blk'


// LAUNCHERS

'gm_m72a3_oli',

'gm_pzf84_oli',
'gm_pzf84_des',
'gm_pzf84_win',
'gm_fim43_oli',
'gm_pzf3_blk',
'gm_pzf44_2_oli',
'gm_pzf44_2_des',
'gm_pzf44_2_win',
'gm_rpg7_prp',
'gm_rpg7_wud',
'gm_9k32m_oli',
'gm_strela_launcher',
'gm_p2a1_launcher_blk'


// ATTACHMENTS

'gm_itemAttachment_suppressor_base',
'gm_bayonet_6x3_wud',
'gm_bayonet_6x3_blk',
'gm_suppressor_safloryt_blk',
'gm_c79a1_blk',
'gm_c79a1_oli',
'gm_feroz24_blk',
'gm_feroz24_des',
'gm_feroz2x17_pzf44_2_blk',
'gm_feroz2x17_pzf44_2_des',
'gm_feroz2x17_pzf44_2_win',
'gm_feroz2x17_pzf84_blk',
'gm_feroz2x17_pzf84_des',
'gm_feroz2x17_pzf84_win',
'gm_pgo7v_blk',
'gm_pso1_gry',
'gm_zfk4x25_blk',
'gm_zvn64_rear_ak',
'gm_zvn64_rear_rpk',
'gm_zvn64_front'


// UNIFORMS

'gm_gc_army_uniform_soldier_80_str',
'gm_gc_army_uniform_soldier_gloves_80_str',
'gm_gc_army_uniform_soldier_80_blk',
'gm_gc_army_uniform_soldier_80_win',
'gm_gc_pol_uniform_dress_80_blu',
'gm_gc_army_uniform_dress_80_gry',
'gm_gc_airforce_uniform_pilot_80_blu',

'gm_ge_army_uniform_crew_80_oli',
'gm_ge_army_uniform_crew_90_flk',
'gm_ge_army_uniform_crew_90_trp',
'gm_ge_army_uniform_pilot_oli',
'gm_ge_pol_uniform_pilot_grn',
'gm_ge_army_uniform_pilot_sar',
'gm_ge_army_uniform_pilot_rolled_oli',
'gm_ge_pol_uniform_pilot_rolled_grn',
'gm_ge_army_uniform_pilot_rolled_sar',
'gm_ge_army_uniform_soldier_80_oli',
'gm_ge_army_uniform_soldier_80_ols',
'gm_ge_army_uniform_soldier_gloves_80_ols',
'gm_ge_army_uniform_soldier_parka_80_oli',
'gm_ge_army_uniform_soldier_parka_80_ols',
'gm_ge_army_uniform_soldier_parka_80_win',
'gm_ge_pol_uniform_suit_80_grn',
'gm_ge_dbp_uniform_suit_80_blu',
'gm_ge_pol_uniform_blouse_80_blk',
'gm_ge_civ_uniform_blouse_80_gry',
'gm_ge_bgs_uniform_soldier_80_smp',
'gm_ge_ff_uniform_man_80_orn',

'gm_xx_uniform_soldier_bdu_80_wdl',
'gm_xx_uniform_soldier_bdu_nogloves_80_wdl',
'gm_xx_uniform_soldier_bdu_rolled_80_wdl',

'gm_ge_uniform_soldier_tshirt_90_flk',
'gm_ge_uniform_soldier_tshirt_90_trp',
'gm_ge_uniform_soldier_90_flk',
'gm_ge_uniform_soldier_90_trp',
'gm_ge_uniform_soldier_rolled_90_flk',
'gm_ge_uniform_soldier_rolled_90_trp',

'gm_pl_army_uniform_soldier_80_moro',
'gm_pl_army_uniform_soldier_rolled_80_moro',
'gm_pl_army_uniform_soldier_autumn_80_moro',
'gm_pl_army_uniform_soldier_80_win',
'gm_pl_airforce_uniform_pilot_80_gry',

'gm_gc_civ_uniform_man_01_80_blk',
'gm_gc_civ_uniform_man_01_80_blu',
'gm_gc_civ_uniform_man_02_80_brn',
'gm_gc_civ_uniform_man_03_80_grn',
'gm_gc_civ_uniform_man_03_80_blu',
'gm_gc_civ_uniform_man_03_80_gry',
'gm_gc_civ_uniform_man_04_80_blu',
'gm_gc_civ_uniform_man_04_80_gry',
'gm_gc_civ_uniform_pilot_80_blk',

'gm_dk_army_uniform_soldier_84_m84',
'gm_dk_army_uniform_soldier_84_win',
'gm_dk_army_uniform_soldier_84_oli'


// VESTS

'gm_gc_army_vest_80_belt_str',
'gm_gc_army_vest_80_rifleman_str',
'gm_gc_army_vest_80_leader_str',
'gm_gc_bgs_vest_80_border_str',
'gm_gc_army_vest_80_lmg_str',
'gm_gc_army_vest_80_at_str',
'gm_gc_vest_combatvest3_str',

'gm_ge_army_vest_80_belt',
'gm_ge_army_vest_80_rifleman',
'gm_ge_bgs_vest_80_rifleman',
'gm_ge_army_vest_80_leader',
'gm_ge_army_vest_80_bag',
'gm_ge_army_vest_80_crew',
'gm_ge_army_vest_80_demolition',
'gm_ge_army_vest_80_machinegunner',
'gm_ge_army_vest_80_medic',
'gm_ge_army_vest_80_officer',
'gm_ge_army_vest_80_mp_wht',
'gm_ge_pol_vest_80_wht',
'gm_ge_vest_armor_90_flk',
'gm_ge_vest_armor_90_crew_flk',
'gm_ge_vest_armor_90_leader_flk',
'gm_ge_vest_armor_90_machinegunner_flk',
'gm_ge_vest_armor_90_officer_flk',
'gm_ge_vest_armor_90_rifleman_flk',
'gm_ge_vest_armor_90_demolition_flk',
'gm_ge_vest_armor_90_medic_flk',
'gm_ge_vest_90_crew_flk',
'gm_ge_vest_90_demolition_flk',
'gm_ge_vest_90_leader_flk',
'gm_ge_vest_90_machinegunner_flk',
'gm_ge_vest_90_medic_flk',
'gm_ge_vest_90_officer_flk',
'gm_ge_vest_90_rifleman_flk',
'gm_ge_army_vest_pilot_oli',
'gm_ge_army_vest_pilot_pads_oli',

'gm_pl_army_vest_80_rig_gry',
'gm_pl_army_vest_80_rifleman_gry',
'gm_pl_army_vest_80_leader_gry',
'gm_pl_army_vest_80_marksman_gry',
'gm_pl_army_vest_80_mg_gry',
'gm_pl_army_vest_80_at_gry',
'gm_pl_army_vest_80_crew_gry',
'gm_pl_army_vest_80_rifleman_smg_gry',

'gm_dk_army_vest_54_rifleman',
'gm_dk_army_vest_54_crew',
'gm_dk_army_vest_54_machinegunner',
'gm_dk_army_vest_m00_m84',
'gm_dk_army_vest_m00_m84_rifleman',
'gm_dk_army_vest_m00_m84_machinegunner',
'gm_dk_army_vest_m00_win',
'gm_dk_army_vest_m00_win_rifleman',
'gm_dk_army_vest_m00_win_machinegunner',
'gm_dk_army_vest_m00_blu',
'gm_dk_army_vest_m00_wdl',
'gm_dk_army_vest_m00_wdl_rifleman'


// HEADGEAR

'gm_gc_army_headgear_m56',
'gm_gc_army_headgear_m56_net',
'gm_gc_army_headgear_m56_cover_str',
'gm_gc_army_headgear_m56_cover_win',
'gm_gc_army_headgear_m56_cover_blu',
'gm_gc_army_headgear_crewhat_80_blk',
'gm_gc_pol_headgear_cap_80_blu',
'gm_gc_army_headgear_cap_80_gry',
'gm_gc_army_headgear_hat_80_grn',
'gm_gc_bgs_headgear_hat_80_gry',
'gm_gc_headgear_zsh3_orn',
'gm_gc_headgear_zsh3_wht',
'gm_gc_headgear_zsh3_blu',
'gm_gc_headgear_fjh_model4_oli',
'gm_gc_headgear_fjh_model4_wht',
'gm_gc_headgear_beret_blk',
'gm_gc_headgear_beret_orn',
'gm_gc_headgear_beret_str',
'gm_gc_headgear_beret_officer_blk',
'gm_gc_headgear_beret_officer_orn',
'gm_gc_headgear_beret_officer_str',

'gm_ge_headgear_m62',
'gm_ge_headgear_m62_net',
'gm_ge_headgear_m62_cover_blu',
'gm_ge_headgear_m62_cover_win',
'gm_ge_headgear_m62_cover_wdl',
'gm_ge_headgear_m62_win_pap_01',
'gm_ge_headgear_beret_mrb',
'gm_ge_headgear_beret_un',
'gm_ge_headgear_beret_bdx_armyaviation',
'gm_ge_headgear_beret_bdx_lrrp',
'gm_ge_headgear_beret_bdx_paratrooper',
'gm_ge_headgear_beret_bdx_specop',
'gm_ge_headgear_beret_blk_antitank',
'gm_ge_headgear_beret_blk_armor',
'gm_ge_headgear_beret_blk_armorrecon',
'gm_ge_headgear_beret_blk_recon',
'gm_ge_headgear_beret_grn_guardbtl',
'gm_ge_headgear_beret_grn_infantry',
'gm_ge_headgear_beret_grn_mechinf',
'gm_ge_headgear_beret_grn_music',
'gm_ge_headgear_beret_red_antiair',
'gm_ge_headgear_beret_red_artillery',
'gm_ge_headgear_beret_red_engineer',
'gm_ge_headgear_beret_red_geoinfo',
'gm_ge_headgear_beret_red_maintenance',
'gm_ge_headgear_beret_red_militarypolice',
'gm_ge_headgear_beret_red_nbc',
'gm_ge_headgear_beret_red_opcom',
'gm_ge_headgear_beret_red_signals',
'gm_ge_headgear_beret_red_supply',
'gm_ge_headgear_beret_blu_medical',
'gm_ge_headgear_beret_crew_bdx_paratrooper',
'gm_ge_headgear_beret_crew_blk_antitank',
'gm_ge_headgear_beret_crew_blk_armor',
'gm_ge_headgear_beret_crew_blk_armorrecon',
'gm_ge_headgear_beret_crew_blk_recon',
'gm_ge_headgear_beret_crew_grn_mechinf',
'gm_ge_headgear_beret_crew_red_antiair',
'gm_ge_headgear_beret_crew_red_artillery',
'gm_ge_headgear_beret_crew_red_engineer',
'gm_ge_headgear_beret_crew_red_maintenance',
'gm_ge_headgear_beret_crew_red_militarypolice',
'gm_ge_headgear_beret_crew_red_nbc',
'gm_ge_headgear_beret_crew_red_opcom',
'gm_ge_headgear_beret_crew_red_signals',
'gm_ge_headgear_beret_crew_red_supply',
'gm_ge_headgear_hat_80_oli',
'gm_ge_headgear_hat_80_m62_oli',
'gm_ge_headgear_hat_80_gry',
'gm_ge_headgear_hat_90_flk',
'gm_ge_headgear_hat_90_trp',
'gm_ge_headgear_hat_boonie_oli',
'gm_ge_headgear_hat_boonie_wdl',
'gm_ge_headgear_hat_boonie_flk',
'gm_ge_headgear_hat_boonie_trp',
'gm_ge_headgear_hat_beanie_blk',
'gm_ge_headgear_winterhat_80_oli',
'gm_ge_headgear_headset_crew_oli',
'gm_ge_headgear_crewhat_80_blk',
'gm_ge_pol_headgear_cap_80_grn',
'gm_ge_pol_headgear_cap_80_wht',
'gm_ge_dbp_headgear_cap_80_blu',
'gm_ge_bgs_headgear_m35_53_blk',
'gm_ge_bgs_headgear_m35_53_net_blk',
'gm_ge_ff_headgear_m35_53_tan',
'gm_ge_headgear_sph4_oli',
'gm_ge_headgear_m92_flk',
'gm_ge_headgear_m92_trp',
'gm_ge_headgear_m92_cover_win',
'gm_ge_headgear_m92_glasses_flk',
'gm_ge_headgear_m92_glasses_trp',
'gm_ge_headgear_m92_cover_glasses_win',

'gm_pl_army_headgear_wz67_oli',
'gm_pl_army_headgear_wz67_net_oli',
'gm_pl_headgear_wz67_cover_win',
'gm_pl_army_headgear_cap_80_moro',
'gm_pl_army_headgear_wz63_oli',
'gm_pl_army_headgear_wz63_net_oli',
'gm_pl_headgear_beret_bdx',
'gm_pl_headgear_beret_blu',
'gm_pl_headgear_beret_blk',

'gm_dk_headgear_m52_oli',
'gm_dk_headgear_m52_net_oli',
'gm_dk_headgear_m52_net_win',
'gm_dk_headgear_m96_oli',
'gm_dk_headgear_m96_blu',
'gm_dk_headgear_m96_cover_m84',
'gm_dk_headgear_m96_cover_wdl',
'gm_dk_headgear_m96_cover_wht',
'gm_dk_headgear_hat_boonie_m84'


// BINOCULARS

'gm_df7x40_blk',
'gm_df7x40_grn',
'gm_edf7x40_grn',
'gm_fero51_grn',
'gm_ferod12_grn',
'gm_ferod16_oli',
'gm_ferod16_grn',
'gm_ferod16_win',
'gm_ferod16_des'


// NVG




// GOGGLES

'gm_headgear_foliage_summer_grass_01',
'gm_headgear_foliage_summer_grass_02',
'gm_headgear_foliage_summer_grass_03',
'gm_headgear_foliage_summer_grass_04',
'gm_headgear_foliage_summer_forest_01',
'gm_headgear_foliage_summer_forest_02',
'gm_headgear_foliage_summer_forest_03',
'gm_headgear_foliage_summer_forest_04',
'gm_gc_army_facewear_schm41m',
'gm_gc_army_facewear_dustglasses',
'gm_ge_facewear_m65',
'gm_ge_facewear_dustglasses'


// MISC ITEMS

'gm_repairkit_01',
'gm_watch_kosei_80',
'gm_gc_army_gauzeBandage',
'gm_gc_army_medkit',
'gm_gc_army_medbox',
'gm_gc_compass_f73',
'gm_ge_army_gauzeBandage',
'gm_ge_army_burnBandage',
'gm_ge_army_gauzeCompress',
'gm_ge_army_conat2',
'gm_ge_army_medkit_80'


// BACKPACKS

'gm_backpack_base',
'gm_backpack_rs9_parachute_base',
'gm_backpack_rs9_parachute',
'gm_backpack_t10_parachute_base',
'gm_backpack_t10_parachute',
'gm_milan_launcher_weaponBag',
'gm_fagot_launcher_weaponBag',
'gm_mg3_aatripod_weaponBag',

'gm_gc_backpack_80_at_base',
'gm_gc_army_backpack_80_at_str',
'gm_gc_backpack_80_lmg_base',
'gm_gc_army_backpack_80_lmg_str',
'gm_gc_army_backpack_80_lmg74_str',
'gm_gc_army_backpack_80_mgk_str',
'gm_gc_backpack_80_assaultpack_base',
'gm_gc_army_backpack_80_assaultpack_empty_str',
'gm_gc_army_backpack_80_assaultpack_str',
'gm_gc_army_backpack_80_demolition_str',
'gm_gc_army_backpack_80_engineer_str',
'gm_gc_backpack_80_assaultpack_lmg_base',
'gm_gc_army_backpack_80_assaultpack_lmg_str',
'gm_gc_army_backpack_80_assaultpack_lmg74_str',
'gm_gc_army_backpack_80_assaultpack_mgk_str',
'gm_gc_backpack_r105m_base',
'gm_gc_backpack_r105m_brn',

'gm_ge_army_backpack_80_base',
'gm_ge_army_backpack_80_oli_base',
'gm_ge_army_backpack_80_oli',
'gm_ge_army_backpack_80_engineer_oli',
'gm_ge_army_backpack_80_demolition_oli',
'gm_ge_army_backpack_80_pzf44_oli',
'gm_ge_army_backpack_80_pzf84_oli',
'gm_ge_army_backpack_80_mg3_oli',
'gm_ge_army_backpack_80_grenadier_oli',
'gm_ge_army_backpack_90_base',
'gm_ge_army_backpack_90_flk_base',
'gm_ge_army_backpack_90_flk',
'gm_ge_army_backpack_90_engineer_flk',
'gm_ge_army_backpack_90_demolition_flk',
'gm_ge_army_backpack_90_pzf84_flk',
'gm_ge_army_backpack_90_mg3_flk',
'gm_ge_army_backpack_90_cover_base',
'gm_ge_army_backpack_90_cover_win_base',
'gm_ge_army_backpack_90_cover_win',
'gm_ge_army_backpack_90_cover_engineer_win',
'gm_ge_army_backpack_90_cover_demolition_win',
'gm_ge_army_backpack_90_cover_pzf84_win',
'gm_ge_army_backpack_90_cover_mg3_win',
'gm_ge_army_backpack_90_trp_base',
'gm_ge_army_backpack_90_trp',
'gm_ge_backpack_satchel_80_base',
'gm_ge_backpack_satchel_80_blk',
'gm_ge_backpack_satchel_80_san',
'gm_ge_backpack_sem35_base',
'gm_ge_backpack_sem35_oli',

'gm_pl_army_backpack_80_base',
'gm_pl_army_backpack_80_oli',
'gm_pl_army_backpack_73_demolition_oli',
'gm_pl_army_backpack_73_engineer_oli',
'gm_pl_army_backpack_73_pk_oli',
'gm_pl_army_backpack_73_rpk_oli',
'gm_pl_army_backpack_at_80_base',
'gm_pl_army_backpack_at_80_gry',

'gm_dk_army_backpack_73_base',
'gm_dk_army_backpack_73_oli',
'gm_dk_army_backpack_73_demolition_oli',
'gm_dk_army_backpack_73_pzf84_oli',
'gm_dk_army_backpack_73_mg3_oli'


