
		_arsenalHeadgear = [	

			"rhsusf_patrolcap_ocp",
			"rhs_Booniehat_ocp",
			
			"rhsusf_ach_helmet_ocp",
			"rhsusf_ach_helmet_ocp_alt",
			"rhsusf_ach_helmet_ocp_norotos",
			"rhsusf_ach_helmet_DCU",
			"rhsusf_ach_helmet_DCU_early",
			"rhsusf_ach_helmet_DCU_early_rhino",
			"rhsusf_ach_helmet_camo_ocp",
			"rhsusf_ach_helmet_headset_ocp",
			"rhsusf_ach_helmet_headset_ocp_alt",
			"rhsusf_ach_helmet_ESS_ocp",
			"rhsusf_ach_helmet_ESS_ocp_alt",
			"rhsusf_ach_helmet_headset_ess_ocp",
			"rhsusf_ach_helmet_headset_ess_ocp_alt",
			"rhsusf_ach_bare",
			"rhsusf_ach_bare_ess",
			"rhsusf_ach_bare_headset",
			"rhsusf_ach_bare_headset_ess",
			"rhsusf_ach_bare_tan",
			"rhsusf_ach_bare_tan_ess",
			"rhsusf_ach_bare_tan_headset",
			"rhsusf_ach_bare_tan_headset_ess",
			"rhsusf_ach_bare_wood",
			"rhsusf_ach_bare_wood_ess",
			"rhsusf_ach_bare_wood_headset",
			"rhsusf_ach_bare_wood_headset_ess",
			"rhsusf_ach_bare_des",
			"rhsusf_ach_bare_des_ess",
			"rhsusf_ach_bare_des_headset",
			"rhsusf_ach_bare_des_headset_ess",
			"rhsusf_ach_bare_semi",
			"rhsusf_ach_bare_semi_ess",
			"rhsusf_ach_bare_semi_headset",
			"rhsusf_ach_bare_semi_headset_ess",
			
			"rhsusf_cvc_helmet",
			"rhsusf_cvc_alt_helmet",
			"rhsusf_cvc_green_helmet",
			"rhsusf_cvc_green_alt_helmet",
			"rhsusf_cvc_ess",
			"rhsusf_cvc_green_ess",
			
			"rhsusf_hgu56p",
			"rhsusf_hgu56p_visor",
			"rhsusf_hgu56p_mask",
			"rhsusf_hgu56p_visor_mask",
			"rhsusf_hgu56p_black",
			"rhsusf_hgu56p_visor_black",
			"rhsusf_hgu56p_mask_black",
			"rhsusf_hgu56p_visor_mask_black",
			"rhsusf_hgu56p_green",
			"rhsusf_hgu56p_visor_green",
			"rhsusf_hgu56p_mask_green",
			"rhsusf_hgu56p_visor_mask_green",
			"rhsusf_hgu56p_mask_green_mo",
			"rhsusf_hgu56p_visor_mask_green_mo",
			"rhsusf_hgu56p_tan",
			"rhsusf_hgu56p_visor_tan",
			"rhsusf_hgu56p_mask_tan",
			"rhsusf_hgu56p_visor_mask_tan",
			
			"rhsusf_mich_bare",
			"rhsusf_mich_bare_headset",
			"rhsusf_mich_bare_alt",
			"rhsusf_mich_bare_norotos",
			"rhsusf_mich_bare_norotos_headset",
			"rhsusf_mich_bare_norotos_alt",
			"rhsusf_mich_bare_norotos_alt_headset",
			"rhsusf_mich_bare_norotos_arc",
			"rhsusf_mich_bare_norotos_arc_headset",
			"rhsusf_mich_bare_norotos_arc_alt",
			"rhsusf_mich_bare_norotos_arc_alt_headset",
			"rhsusf_mich_bare_tan",
			"rhsusf_mich_bare_tan_headset",
			"rhsusf_mich_bare_alt_tan",
			"rhsusf_mich_bare_norotos_tan",
			"rhsusf_mich_bare_norotos_tan_headset",
			"rhsusf_mich_bare_norotos_alt_tan",
			"rhsusf_mich_bare_norotos_alt_tan_headset",
			"rhsusf_mich_bare_norotos_arc_tan",
			"rhsusf_mich_bare_norotos_arc_tan_headset",
			"rhsusf_mich_bare_norotos_arc_alt_tan",
			"rhsusf_mich_bare_norotos_arc_alt_tan_headset",
			"rhsusf_mich_bare_semi",
			"rhsusf_mich_bare_semi_headset",
			"rhsusf_mich_bare_alt_semi",
			"rhsusf_mich_bare_norotos_semi",
			"rhsusf_mich_bare_norotos_semi_headset",
			"rhsusf_mich_bare_norotos_alt_semi",
			"rhsusf_mich_bare_norotos_alt_semi_headset",
			"rhsusf_mich_bare_norotos_arc_semi",
			"rhsusf_mich_bare_norotos_arc_semi_headset",
			"rhsusf_mich_bare_norotos_arc_alt_semi",
			"rhsusf_mich_bare_norotos_arc_alt_semi_headset",
			
			"rhsusf_Bowman",
			"rhsusf_bowman_cap",
			"RHS_jetpilot_usaf",
			"rhsusf_ihadss",
			
			"FIR_ScorpionHMCS"
			
		];
		
		
		_arsenalGoggles = [

			"G_AirPurifyingRespirator_01_F",
			"G_Balaclava_blk",
			"G_Balaclava_combat",
			"G_Balaclava_lowprofile",
			"G_Balaclava_oli",
			"G_Balaclava_TI_blk_F",
			"G_Balaclava_TI_G_blk_F",
			"G_Balaclava_TI_G_tna_F",
			"G_Balaclava_TI_tna_F",
			"G_Combat",
			"G_Combat_Goggles_tna_F",
			"G_B_Diving",
			"G_Lowprofile",
			"G_Tactical_Black",
			"G_Tactical_Clear"
			
		];
		
		
		_arsenalUniforms = [
		
			"rhs_uniform_cu_ocp",
			"rhs_uniform_acu_oefcp",
			"rhs_uniform_acu_ocp",
			"U_B_Wetsuit"

		];

		
		_arsenalVests = [

			"rhsusf_iotv_ocp",
			"rhsusf_iotv_ocp_Grenadier",
			"rhsusf_iotv_ocp_Medic",
			"rhsusf_iotv_ocp_Repair",
			"rhsusf_iotv_ocp_Rifleman",
			"rhsusf_iotv_ocp_SAW",
			"rhsusf_iotv_ocp_Squadleader",
			"rhsusf_iotv_ocp_Teamleader",
			"rhsusf_spcs_ocp",
			"rhsusf_spcs_ocp_squadleader",
			"rhsusf_spcs_ocp_teamleader",
			"rhsusf_spcs_ocp_teamleader_alt",
			"rhsusf_spcs_ocp_saw",
			"rhsusf_spcs_ocp_grenadier",
			"rhsusf_spcs_ocp_rifleman",
			"rhsusf_spcs_ocp_rifleman_alt",
			"rhsusf_spcs_ocp_medic",
			"rhsusf_spcs_ocp_crewman",
			"rhsusf_spcs_ocp_machinegunner",
			"rhsusf_spcs_ocp_sniper",
			"V_RebreatherB"

		];
		
		

		_arsenalBackpacks = [

			"rhsusf_assault_eagleaiii_ocp",
			"B_rhsusf_B_BACKPACK",
			"rhsusf_falconii_mc",
			
			"B_AssaultPack_blk",	
			"B_Parachute",	
			"B_UAV_01_backpack_F",
			"B_UAV_06_medical_backpack_F",
			"B_UAV_06_backpack_F",
			"B_UGV_02_Demining_backpack_F",
			"B_UGV_02_Science_backpack_F",			
			"B_Static_Designator_01_weapon_F"
			
		];


		_arsenalNvgoggles = [
		

			"rhsusf_Rhino",
			"rhsusf_anvis_nvg_bc_caps",
			"rhsusf_ANVIS",
			"rhsusf_ANPVS_14",
			"rhsusf_ANPVS_15"

		];


		_arsenalPrimaryAttachments = [

		
				"rhsusf_acc_harris_bipod",
			"rhsusf_acc_harris_swivel",
			"rhsusf_acc_saw_bipod",
			"rhsusf_acc_saw_lw_bipod",
			"rhsusf_acc_m14_bipod",
			"rhsusf_acc_grip1",
			"rhsusf_acc_grip2",
			"rhsusf_acc_grip3",
			"rhsusf_acc_grip4",
			"rhsusf_acc_grip4_bipod",
			"rhsusf_acc_rvg_blk",
			"rhsusf_acc_tacsac_blk",
			"rhsusf_acc_tdstubby_blk",
			"rhsusf_acc_kac_grip",
			"rhsusf_acc_kac_grip_saw_bipod",
			"rhs_acc_at4_handler",
			"rhsusf_acc_anpeq15A",
			"rhsusf_acc_anpeq15_bk",
			"rhsusf_acc_anpeq15_h",
			"rhsusf_acc_anpeq15_sc",
			"rhsusf_acc_anpeq15_bk_h",
			"rhsusf_acc_anpeq15_bk_sc",
			"rhsusf_acc_anpeq15_bk_light",
			"rhsusf_acc_anpeq15_light_h",
			"rhsusf_acc_anpeq15_light_sc",
			"rhsusf_acc_anpeq15_bk_light_h",
			"rhsusf_acc_anpeq15_bk_light_sc",
			"rhsusf_acc_anpeq15_wmx_h",
			"rhsusf_acc_anpeq15_wmx_light_h",
			"rhsusf_acc_anpeq15_wmx_sc",
			"rhsusf_acc_anpeq15_wmx_light_sc",
			"rhsusf_acc_anpeq15_bk_top",
			"rhsusf_acc_anpeq15_top_h",
			"rhsusf_acc_anpeq15_bk_top_h",
			"rhsusf_acc_anpeq15_top_sc",
			"rhsusf_acc_anpeq15_bk_top_sc",
			"rhsusf_acc_anpeq15side_bk",
			"rhsusf_acc_anpeq16a",
			"rhsusf_acc_anpeq16a_light",
			"rhsusf_acc_anpeq16a_top",
			"rhsusf_acc_anpeq16a_light_top",
			"rhsusf_acc_anpeq16a_top_h",
			"rhsusf_acc_anpeq16a_light_top_h",
			"rhsusf_acc_anpeq16a_top_sc",
			"rhsusf_acc_anpeq16a_light_top_sc",
			"rhsusf_acc_M952V",			
			"rhsusf_acc_wmx_bk",
			"rhsusf_acc_M2010S",
			"rhsusf_acc_M2010S_sa",
			"rhsusf_acc_SR25S",
			"rhsusf_acc_rotex5_grey",
			"rhsusf_acc_nt4_black",
			"rhsusf_acc_omega9k",
			"rhsusf_acc_rotex_mp7",
			"rhsusf_acc_muzzleFlash_ar15",
			"rhsusf_acc_muzzleFlash_SF3P556",
			"rhsusf_acc_muzzleFlash_SFMB556",
			"rhsusf_acc_muzzleFlash_ardec_m240",
			"rhsusf_acc_muzzleFlash_M14_USGI_NM",
			"rhsusf_m4muzzlebreak_base",
			"rhsusf_acc_SF3P556",
			"rhsusf_acc_SFMB556",
			"rhsusf_acc_ARDEC_M240",
			"rhsusf_acc_m14_flashsuppresor",
			"rhsusf_acc_m24_silencer_black",
			"rhsusf_acc_m24_muzzlehider_black",
			"rhsusf_acc_aac_scarh_silencer",
			"rhsusf_acc_aac_762sd_silencer",
			"rhsusf_acc_aac_762sdn6_silencer",
			"rhsusf_acc_aac_m14dcqd_silencer",
			"rhsusf_acc_sniper_base",
			"rhsusf_acc_compm4",
			"rhsusf_acc_T1_high",
			"rhsusf_acc_T1_low",
			"rhsusf_acc_T1_low_fwd",
			"rhsusf_acc_T1_low_fwd_ak",
			"rhsusf_acc_RX01",
			"rhsusf_acc_RX01_NoFilter",
			"rhsusf_acc_RM05",
			"rhsusf_acc_RM05_fwd",
			"rhsusf_acc_RM05_fwd_ak",
			"rhsusf_acc_mrds",
			"rhsusf_acc_mrds_fwd",
			"rhsusf_acc_mrds_fwd_ak",
			"rhsusf_acc_eotech_552",
			"rhsusf_acc_anpvs27",
			"rhsusf_acc_anpas13gv1",
			"rhsusf_acc_LEUPOLDMK4",
			"rhsusf_acc_ELCAN",
			"rhsusf_acc_ELCAN_ard",
			"rhsusf_acc_elcan_3d",
			"rhsusf_acc_elcan_ard_3d",
			"rhsusf_acc_ELCAN_pip",
			"rhsusf_acc_ELCAN_ard_pip",
			"rhsusf_acc_su230_base",
			"rhsusf_acc_su230_base_3d",
			"rhsusf_acc_su230_mrds_base",
			"rhsusf_acc_su230_mrds_base_3d",
			"rhsusf_acc_su230",
			"rhsusf_acc_su230_3d",
			"rhsusf_acc_su230_mrds",
			"rhsusf_acc_su230_mrds_3d",
			"rhsusf_acc_su230a",
			"rhsusf_acc_su230a_3d",
			"rhsusf_acc_su230a_mrds",
			"rhsusf_acc_su230a_mrds_3d",
			"rhsusf_acc_SpecterDR",
			"rhsusf_acc_SpecterDR_D",
			"rhsusf_acc_SpecterDR_OD",
			"rhsusf_acc_SpecterDR_CX",
			"rhsusf_acc_SpecterDR_A",
			"rhsusf_acc_SpecterDR_3d",
			"rhsusf_acc_SpecterDR_D_3D",
			"rhsusf_acc_SpecterDR_OD_3D",
			"rhsusf_acc_SpecterDR_A_3d",
			"rhsusf_acc_SpecterDR_CX_3D",
			"rhsusf_acc_SpecterDR_pvs27",
			"rhsusf_acc_ACOG",
			"rhsusf_acc_ACOG_sa",
			"rhsusf_acc_ACOG2",
			"rhsusf_acc_ACOG3",
			"rhsusf_acc_ACOG_USMC",
			"rhsusf_acc_ACOG2_USMC",
			"rhsusf_acc_ACOG3_USMC",
			"rhsusf_acc_ACOG_RMR",
			"rhsusf_acc_ACOG_3d",
			"rhsusf_acc_ACOG_sa_3d",
			"rhsusf_acc_ACOG2_3d",
			"rhsusf_acc_ACOG3_3d",
			"rhsusf_acc_ACOG_USMC_3d",
			"rhsusf_acc_ACOG2_USMC_3d",
			"rhsusf_acc_ACOG3_USMC_3d",
			"rhsusf_acc_ACOG_RMR_3d",
			"rhsusf_acc_ACOG_pip",
			"rhsusf_acc_ACOG_sa_pip",
			"rhsusf_acc_ACOG2_pip",
			"rhsusf_acc_ACOG3_pip",
			"rhsusf_acc_ACOG_USMC_pip",
			"rhsusf_acc_ACOG2_USMC_pip",
			"rhsusf_acc_ACOG3_USMC_pip",
			"rhsusf_acc_ACOG_RMR_pip",
			"rhsusf_acc_ACOG_anpvs27",
			"rhsusf_acc_LEUPOLDMK4_2",
			"rhsusf_acc_LEUPOLDMK4_2_mrds",
			"rhsusf_acc_premier",
			"rhsusf_acc_premier_mrds",
			"rhsusf_acc_premier_low",
			"rhsusf_acc_premier_anpvs27",
			"rhsusf_acc_M8541",
			"rhsusf_acc_M8541_mrds",
			"rhsusf_acc_M8541_low",
			"rhsusf_acc_M2A1",
			"rhsusf_acc_eotech_xps3",
			"rhsusf_acc_g33_xps3",
			"rhsusf_acc_g33_xps3_flip",
			"rhsusf_acc_g33_T1",
			"rhsusf_acc_g33_T1_flip",
			"rhs_weap_optic_smaw",
			"rhs_weap_optic_smaw_1",
			"rhs_weap_optic_smaw_2",
			"rhs_weap_optic_smaw_3",
			"rhs_weap_optic_smaw_4",
			"rhs_weap_optic_smaw_5",
			"rhs_weap_optic_smaw_6",
			"rhs_weap_optic_smaw_7",
			"rhs_weap_optic_smaw_8",
			"rhs_weap_optic_smaw_9",
			"rhs_weap_optic_smaw_10",
			
			"acc_flashlight",
			"acc_pointer_IR"
		
		];


		_arsenalSecondaryAttachments = [

		];
		
		_arsenalExplosives = [
		
			"SatchelCharge_Remote_Mag",
			"DemoCharge_Remote_Mag",
			"SLAMDirectionalMine_Wire_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellGreen",
			"SmokeShellYellow",
			"SmokeShellPurple",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_yellow",
			"Chemlight_blue",
			"B_IR_Grenade",
			"Laserbatteries"
		
		];


		_arsenalItems = [
		
			"rhsusf_bino_lerca_1200_black",
			"rhsusf_bino_lerca_1200_tan",
			"lerca_1200_black",
			"lerca_1200_tan",
			"rhsusf_bino_lrf_Vector21",
			"rhsusf_lrf_Vector21",
			"rhsusf_bino_leopold_mk4",
			"Leupold_Mk4",
			"rhsusf_bino_m24",
			"rhsusf_bino_m24_ARD",
			"m24_bino",
			"m24_bino_ARD",
			
			"ItemGPS",
			"B_UavTerminal",
			"Laserdesignator",
			"MineDetector",
			"Binocular",
			"FirstAidKit",
			"ItemCompass",
			"Rangefinder",
			"ItemWatch",
			"ToolKit",
			"ItemRadio",
			"Medikit",
			"ItemMap"

		];
				
		_return = [_arsenalHeadgear, _arsenalGoggles, _arsenalUniforms, _arsenalVests, _arsenalBackpacks, _arsenalNvgoggles, _arsenalPrimaryAttachments, _arsenalSecondaryAttachments, _arsenalExplosives, _arsenalItems];
		
		_return
