
		_arsenalHeadgear = [



		];


		_arsenalGoggles = [



		];


		_arsenalUniforms = [



		];


		_arsenalVests = [



		];


		_arsenalBackpacks = [



		];


		_arsenalNvgoggles = [



		];


		_arsenalPrimaryAttachments = [

			'hlc_muzzle_300blk_KAC',
			'hlc_muzzle_556NATO_KAC',
			'hlc_muzzle_556NATO_M42000',
			'hlc_muzzle_556NATO_rotexiiic_grey',
			'hlc_muzzle_Tundra',
			'hlc_muzzle_Octane9',
			'hlc_muzzle_Evo9',
			'hlc_muzzle_TiRant9',
			'hlc_muzzle_TiRant9S',
			'hlc_muzzle_Octane45',
			'hlc_muzzle_Evo40',
			'hlc_muzzle_MAG58_Brake',
			'hlc_muzzle_Cherrybomb',
			'hlc_muzzle_FSC30',
			'hlc_muzzle_17SBrake',
			'hlc_muzzle_Miter18T',
			'hlc_muzzle_OEMDevice',
			'hlc_muzzle_OEMDevice_556',
			'hlc_muzzle_AAC_762SDN6',
			'hlc_muzzle_AAC_SCARH',
			'hlc_muzzle_Brevis',
			'hlc_muzzle_ThunderChicken',
			'hlc_muzzle_KX3_comp',
			'hlc_muzzle_apology',
			'hlc_muzzle_SF3P_556',
			'hlc_muzzle_SF3P_68',
			'hlc_muzzle_SF3P_762',
			'hlc_muzzle_SF3P_762R',
			'hlc_muzzle_545SUP_AK',
			'hlc_muzzle_762SUP_AK',
			'hlc_muzzle_snds_ArsenalComp',
			'muzzle_HBADGER',
			'hlc_muzzle_Gunfighter_comp',
			'hlc_muzzle_snds_a6AUG',
			'hlc_muzzle_Agendasix',
			'hlc_muzzle_Agendasix10mm',
			'hlc_muzzle_snds_ROTEX3P',
			'hlc_optic_PVS4base',
			'hlc_optic_VOMZ',
			'hlc_optic_VOMZ3d',
			'hlc_optic_HensoldtZO_Hi',
			'hlc_optic_HensoldtZO_Hi_2D',
			'hlc_optic_HensoldtZO_Hi_Docter',
			'hlc_optic_HensoldtZO_Hi_Docter_2D',
			'hlc_optic_HensoldtZO_Lo',
			'hlc_optic_HensoldtZO_Lo_2D',
			'hlc_optic_HensoldtZO_lo_Docter',
			'hlc_optic_HensoldtZO_lo_Docter_2D',
			'hlc_optic_KernBase',
			'hlc_optic_ZF4xBase',
			'hlc_optic_ZF4x2DBase',
			'hlc_optic_Kern2DBase',
			'HLC_optic_DocterR',			
			'hlc_optic_ZF95',
			'hlc_optic_ZF95Base',			
			'hlc_optic_ZF95_3011',			
			'hlc_optic_ZF95_g3',
			'hlc_optic_ATACR_Offset',
			'hlc_optic_ATACR',
			'HLC_optic_DocterV',
			'HLC_optic_RomeoV',
			'HLC_Optic_PSO1',
			'HLC_Optic_1p29',
			'hlc_optic_kobra',
			'hlc_optic_goshawk',
			'hlc_barrel_standard',
			'hlc_barrel_carbine',
			'hlc_barrel_hbar',
			'hlc_barrel_9mm',
			'hlc_optic_suit',
			'hlc_optic_PVS4FAL',
			'hlc_optic_FNSTANAG4X',
			'hlc_optic_FNSTANAG2D',
			'hlc_optic_Kern_3011',
			'hlc_optic_Kern2d_3011',
			'hlc_optic_ANGSCHUTZ',
			'hlc_optic_LeupoldM3A_3011',			
			'hlc_optic_LeupoldM3A',			
			'hlc_optic_LeupoldM3A_G3',
			'HLC_Optic_G36dualoptic35x',
			'HLC_Optic_G36dualoptic35x2d',
			'HLC_Optic_G36Export35x',
			'HLC_Optic_G36Export35x2d',
			'HLC_Optic_G36Dualoptic15x',
			'HLC_Optic_G36Dualoptic15x2d',
			'HLC_Optic_G36Export15x',
			'HLC_Optic_G36Export15x2d',
			'HLC_Optic_ZFSG1',
			'hlc_optic_accupoint_g3',
			'hlc_optic_PVS4G3',
			'hlc_optic_STANAGZF2D_G3',
			'hlc_optic_STANAGZF_G3',
			'hlc_optic_artel_m14',
			'hlc_optic_PVS4M14',
			'hlc_optic_LRT_m14',
			'HLC_optic_stavenhagen',
			'HLC_optic_VTAC',
			'HLC_optic_Siglite',
			'HLC_optic_HP',
			'HLC_optic_ATT',
			'HLC_optic_XS',
			'HLC_Optic_Romeo1_RX',
			'HLC_Optic_Docter_CADEX',
			'HLC_optic228_stavenhagen',
			'HLC_optic228_VTAC',
			'HLC_optic228_Siglite',
			'HLC_optic228_HP',
			'HLC_optic228_ATT',
			'HLC_optic228_XS',
			'HLC_Optic228_Romeo1_RX',
			'HLC_Optic228_Docter_CADEX',
			'hlc_optic_Kern',
			'hlc_optic_Kern2d',
			'hlc_optic_DiavariZ_5501',
			'hlc_optic_FNSTANAG4X_550',
			'hlc_optic_FNSTANAG4X2d_550',
			'hlc_optic_Kern_550',
			'hlc_optic_Kern2d_550',
			'HLC_optic_ISM_PCAP',
			'HLC_optic_ISM1400A7',
			'HLC_optic_RCO_PCAP',
			'HLC_optic_AMO_PCAP',
			'hlc_acc_TLR1',
			'hlc_acc_DBALPL',
			'hlc_acc_DBALPL_FL',
			'HLC_Panel_base',
			'HLC_Panel_Side_FN5cm_Black',
			'HLC_Panel_Side_2xFN5cm_Black',
			'HLC_Panel_Side_FN10cm_Black',
			'HLC_Panel_Side_FN15cm_Black',
			'HLC_Panel_Side_Ladder_S_Black',
			'HLC_Panel_Side_Ladder_M_Black',
			'HLC_Panel_Side_Ladder_L_Black',
			'HLC_Panel_Side_MagpulXT_Black',
			'HLC_Panel_Side_XTME_Black',
			'HLC_Panel_Side_2xXTME_Black',
			'HLC_Panel_Side_4xXTME_Black',
			'HLC_Panel_Side_6xXTME_Black',
			'HLC_Charm_base',
			'HLC_Charm_Eurojank',
			'HLC_Charm_NIArmsbacker',
			'HLC_Charm_NIArmsbacker_dirty',
			'HLC_Charm_Izhmash',
			'HLC_Charm_Herstal',
			'HLC_Charm_Teethgang',
			'HLC_Panel_Side_ACR_FN5cm_Black',
			'HLC_Panel_Side_ACR_FN10cm_Black',
			'HLC_Panel_Side_ACR_FN15cm_Black',
			'HLC_Panel_Side_ACR_2xFN5cm_Black',
			'HLC_Panel_Side_ACR_Ladder_S_Black',
			'HLC_Panel_Side_ACR_Ladder_M_Black',
			'HLC_Panel_Side_ACR_Ladder_L_Black',
			'HLC_Panel_Side_ACR_MagpulXT_Black',
			'HLC_Panel_Side_ACR_XTME_Black',
			'HLC_Panel_Side_ACR_2xXTME_Black',
			'HLC_Panel_Side_ACR_4xXTME_Black',
			'HLC_Panel_Side_AK12_FN5cm_Black',
			'HLC_Panel_Side_AK12_Ladder_S_Black',
			'HLC_Panel_Side_AK12_XTME_Black',
			'HLC_Panel_Side_SLR107U_FN5cm_Black',
			'HLC_Panel_Side_SLR107U_FN10cm_Black',
			'HLC_Panel_Side_SLR107U_2xFN5cm_Black',
			'HLC_Panel_Side_SLR107U_Ladder_S_Black',
			'HLC_Panel_Side_SLR107U_Ladder_M_Black',
			'HLC_Panel_Side_SLR107U_XTME_Black',
			'HLC_Panel_Side_SLR107U_2xXTME_Black',
			'HLC_Panel_Side_CQBR_FN5cm_Black',
			'HLC_Panel_Side_CQBR_FN10cm_Black',
			'HLC_Panel_Side_CQBR_FN15cm_Black',
			'HLC_Panel_Side_CQBR_2xFN5cm_Black',
			'HLC_Panel_Side_CQBR_Ladder_S_Black',
			'HLC_Panel_Side_CQBR_Ladder_M_Black',
			'HLC_Panel_Side_CQBR_Ladder_L_Black',
			'HLC_Panel_Side_CQBR_MagpulXT_Black',
			'HLC_Panel_Side_CQBR_XTME_Black',
			'HLC_Panel_Side_CQBR_2xXTME_Black',
			'HLC_Panel_Side_CQBR_4xXTME_Black',
			'HLC_Panel_Side_CQBR_6xXTME_Black',
			'HLC_Panel_Side_AUGA3_FN5cm_Black',
			'HLC_Panel_Side_AUGA3_FN10cm_Black',
			'HLC_Panel_Side_AUGA3_FN15cm_Black',
			'HLC_Panel_Side_AUGA3_2xFN5cm_Black',
			'HLC_Panel_Side_AUGA3_Ladder_S_Black',
			'HLC_Panel_Side_AUGA3_Ladder_M_Black',
			'HLC_Panel_Side_AUGA3_Ladder_L_Black',
			'HLC_Panel_Side_AUGA3_MagpulXT_Black',
			'HLC_Panel_Side_AUGA3_XTME_Black',
			'HLC_Panel_Side_AUGA3_2xXTME_Black',
			'HLC_Panel_Side_AUGA3_4xXTME_Black',
			'HLC_Panel_Side_AUGA3_6xXTME_Black',
			'HLC_Panel_Side_SA58_FN5cm_Black',
			'HLC_Panel_Side_SA58_FN10cm_Black',
			'HLC_Panel_Side_SA58_FN15cm_Black',
			'HLC_Panel_Side_SA58_2xFN5cm_Black',
			'HLC_Panel_Side_SA58_Ladder_S_Black',
			'HLC_Panel_Side_SA58_Ladder_M_Black',
			'HLC_Panel_Side_SA58_Ladder_L_Black',
			'HLC_Panel_Side_SA58_MagpulXT_Black',
			'HLC_Panel_Side_SA58_XTME_Black',
			'HLC_Panel_Side_SA58_2xXTME_Black',
			'HLC_Panel_Side_SA58_4xXTME_Black',
			'HLC_Panel_Side_SA58_6xXTME_Black',
			'HLC_Panel_Side_G36TAC_FN5cm_Black',
			'HLC_Panel_Side_G36TAC_FN10cm_Black',
			'HLC_Panel_Side_G36TAC_FN15cm_Black',
			'HLC_Panel_Side_G36TAC_2xFN5cm_Black',
			'HLC_Panel_Side_G36TAC_Ladder_S_Black',
			'HLC_Panel_Side_G36TAC_Ladder_M_Black',
			'HLC_Panel_Side_G36TAC_Ladder_L_Black',
			'HLC_Panel_Side_G36TAC_MagpulXT_Black',
			'HLC_Panel_Side_G36TAC_XTME_Black',
			'HLC_Panel_Side_G36TAC_2xXTME_Black',
			'HLC_Panel_Side_G36TAC_4xXTME_Black',
			'HLC_Panel_Side_G36TAC_6xXTME_Black',
			'HLC_Panel_Side_G36V_FN5cm_Black',
			'HLC_Panel_Side_G36V_FN10cm_Black',
			'HLC_Panel_Side_G36V_FN15cm_Black',
			'HLC_Panel_Side_G36V_2xFN5cm_Black',
			'HLC_Panel_Side_G36V_Ladder_S_Black',
			'HLC_Panel_Side_G36V_Ladder_M_Black',
			'HLC_Panel_Side_G36V_Ladder_L_Black',
			'HLC_Panel_Side_G36V_MagpulXT_Black',
			'HLC_Panel_Side_G36V_XTME_Black',
			'HLC_Panel_Side_G36V_2xXTME_Black',
			'HLC_Panel_Side_G36V_4xXTME_Black',
			'HLC_Panel_Side_G36V_6xXTME_Black',
			'HLC_Panel_Side_G3K_FN5cm_Black',
			'HLC_Panel_Side_G3K_FN10cm_Black',
			'HLC_Panel_Side_G3K_FN15cm_Black',
			'HLC_Panel_Side_G3K_2xFN5cm_Black',
			'HLC_Panel_Side_G3K_Ladder_S_Black',
			'HLC_Panel_Side_G3K_Ladder_M_Black',
			'HLC_Panel_Side_G3K_Ladder_L_Black',
			'HLC_Panel_Side_G3K_MagpulXT_Black',
			'HLC_Panel_Side_G3K_XTME_Black',
			'HLC_Panel_Side_G3K_2xXTME_Black',
			'HLC_Panel_Side_G3K_4xXTME_Black',
			'HLC_Panel_Side_G3K_6xXTME_Black',
			'HLC_Panel_Side_HK33_FN5cm_Black',
			'HLC_Panel_Side_HK33_FN10cm_Black',
			'HLC_Panel_Side_HK33_FN15cm_Black',
			'HLC_Panel_Side_HK33_2xFN5cm_Black',
			'HLC_Panel_Side_HK33_Ladder_S_Black',
			'HLC_Panel_Side_HK33_Ladder_M_Black',
			'HLC_Panel_Side_HK33_Ladder_L_Black',
			'HLC_Panel_Side_HK33_MagpulXT_Black',
			'HLC_Panel_Side_HK33_XTME_Black',
			'HLC_Panel_Side_HK33_2xXTME_Black',
			'HLC_Panel_Side_HK33_4xXTME_Black',
			'HLC_Panel_Side_HK53_FN5cm_Black',
			'HLC_Panel_Side_HK53_FN10cm_Black',
			'HLC_Panel_Side_HK53_FN15cm_Black',
			'HLC_Panel_Side_HK53_2xFN5cm_Black',
			'HLC_Panel_Side_HK53_Ladder_S_Black',
			'HLC_Panel_Side_HK53_Ladder_M_Black',
			'HLC_Panel_Side_HK53_Ladder_L_Black',
			'HLC_Panel_Side_HK53_MagpulXT_Black',
			'HLC_Panel_Side_HK53_XTME_Black',
			'HLC_Panel_Side_HK53_2xXTME_Black',
			'HLC_Panel_Side_HK53_4xXTME_Black',
			'HLC_Panel_Side_MP5TAC_FN5cm_Black',
			'HLC_Panel_Side_MP5TAC_FN10cm_Black',
			'HLC_Panel_Side_MP5TAC_FN15cm_Black',
			'HLC_Panel_Side_MP5TAC_2xFN5cm_Black',
			'HLC_Panel_Side_MP5TAC_Ladder_S_Black',
			'HLC_Panel_Side_MP5TAC_Ladder_M_Black',
			'HLC_Panel_Side_MP5TAC_Ladder_L_Black',
			'HLC_Panel_Side_MP5TAC_MagpulXT_Black',
			'HLC_Panel_Side_MP5TAC_XTME_Black',
			'HLC_Panel_Side_MP5TAC_2xXTME_Black',
			'HLC_Panel_Side_MP5TAC_4xXTME_Black',
			'hlc_acc_Surefiregrip',
			'hlc_acc_slimlinegrip',
			'HLC_Panel_Side_SAW_FN5cm_Black',
			'HLC_Panel_Side_SAW_FN10cm_Black',
			'HLC_Panel_Side_SAW_FN15cm_Black',
			'HLC_Panel_Side_SAW_2xFN5cm_Black',
			'HLC_Panel_Side_SAW_Ladder_S_Black',
			'HLC_Panel_Side_SAW_Ladder_M_Black',
			'HLC_Panel_Side_SAW_Ladder_L_Black',
			'HLC_Panel_Side_SAW_MagpulXT_Black',
			'HLC_Panel_Side_SAW_XTME_Black',
			'HLC_Panel_Side_SAW_2xXTME_Black',
			'HLC_Panel_Side_SAW_4xXTME_Black',
			'HLC_Panel_Side_MK48_FN5cm_Black',
			'HLC_Panel_Side_MK48_FN10cm_Black',
			'HLC_Panel_Side_MK48_FN15cm_Black',
			'HLC_Panel_Side_MK48_2xFN5cm_Black',
			'HLC_Panel_Side_MK48_Ladder_S_Black',
			'HLC_Panel_Side_MK48_Ladder_M_Black',
			'HLC_Panel_Side_MK48_Ladder_L_Black',
			'HLC_Panel_Side_MK48_MagpulXT_Black',
			'HLC_Panel_Side_MK48_XTME_Black',
			'HLC_Panel_Side_MK48_2xXTME_Black',
			'HLC_Panel_Side_MK48_4xXTME_Black',
			'HLC_Panel_Side_Mk48mod1_FN5cm_Black',
			'HLC_Panel_Side_Mk48mod1_FN10cm_Black',
			'HLC_Panel_Side_Mk48mod1_FN15cm_Black',
			'HLC_Panel_Side_Mk48mod1_2xFN5cm_Black',
			'HLC_Panel_Side_Mk48mod1_Ladder_S_Black',
			'HLC_Panel_Side_Mk48mod1_Ladder_M_Black',
			'HLC_Panel_Side_Mk48mod1_Ladder_L_Black',
			'HLC_Panel_Side_Mk48mod1_MagpulXT_Black',
			'HLC_Panel_Side_Mk48mod1_XTME_Black',
			'HLC_Panel_Side_Mk48mod1_2xXTME_Black',
			'HLC_Panel_Side_Mk48mod1_4xXTME_Black',
			'HLC_Panel_Side_416_FN5cm_Black',
			'HLC_Panel_Side_416_FN10cm_Black',
			'HLC_Panel_Side_416_FN15cm_Black',
			'HLC_Panel_Side_416_2xFN5cm_Black',
			'HLC_Panel_Side_416_Ladder_S_Black',
			'HLC_Panel_Side_416_Ladder_M_Black',
			'HLC_Panel_Side_416_Ladder_L_Black',
			'HLC_Panel_Side_416_MagpulXT_Black',
			'HLC_Panel_Side_416_XTME_Black',
			'HLC_Panel_Side_416_2xXTME_Black',
			'HLC_Panel_Side_416_4xXTME_Black',
			'HLC_Panel_Side_SG550_FN5cm_Black',
			'HLC_Panel_Side_SG550_FN10cm_Black',
			'HLC_Panel_Side_SG550_FN15cm_Black',
			'HLC_Panel_Side_SG550_2xFN5cm_Black',
			'HLC_Panel_Side_SG550_Ladder_S_Black',
			'HLC_Panel_Side_SG550_Ladder_M_Black',
			'HLC_Panel_Side_SG550_Ladder_L_Black',
			'HLC_Panel_Side_SG550_MagpulXT_Black',
			'HLC_Panel_Side_SG550_XTME_Black',
			'HLC_Panel_Side_SG550_2xXTME_Black',
			'HLC_Panel_Side_SG550_4xXTME_Black',
			'HLC_Panel_Side_SG550_6xXTME_Black',
			'HLC_Acc_Flashlight_PCAP',
			'HLC_Acc_ISM_PCAP_Laser',
			'HLC_Acc_AMO_PCAP_Laser',
			'HLC_bipod_UTGShooters',
			'hlc_grip_AFG2',
			'hlc_grip_AFG',
			'hlc_grip_PMVFG',
			'hlc_grip_PMVFG_Black',
			'HLC_Panel_Under_base',
			'HLC_Panel_Under_FN5cm_Black',
			'HLC_Panel_Under_2xFN5cm_Black',
			'HLC_Panel_Under_FN10cm_Black',
			'HLC_Panel_Under_FN15cm_Black',
			'HLC_Panel_Under_Ladder_S_Black',
			'HLC_Panel_Under_Ladder_M_Black',
			'HLC_Panel_Under_Ladder_L_Black',
			'HLC_Panel_Under_MagpulXT_Black',
			'HLC_Panel_Under_XTME_Black',
			'HLC_Panel_Under_2xXTME_Black',
			'HLC_Panel_Under_4xXTME_Black',
			'HLC_Panel_Under_6xXTME_Black',
			'HLC_Bipod_G36',
			'hlc_grip_SAW_Grip1',
			'hlc_grip_SAW_Grip2',
			'HLC_Acc_VFG_PCAP'

		];


		_arsenalSecondaryAttachments = [



		];


		_arsenalExplosives = [



		];


		_arsenalItems = [



		];

		_return = [_arsenalHeadgear, _arsenalGoggles, _arsenalUniforms, _arsenalVests, _arsenalBackpacks, _arsenalNvgoggles, _arsenalPrimaryAttachments, _arsenalSecondaryAttachments, _arsenalExplosives, _arsenalItems];

		_return
