	
	if !(BEW_v_WW2) exitWith {};
	
	if (!(toupper worldName == (toUpper "cup_chernarus_A3"))) exitWith {};
	
	_centerPos = [6982.99,8882.02,0];
	_radius = 12000;
	
	_blacklistedModelList = [
	
		'sign_speed20.p3d',
		'sign_main.p3d',
		'kiosk_papers_f.p3d',
		'kontejner.p3d',
		'garbagecontainer_closed_f.p3d',
		'garbagecontainer_open_f.p3d',
		'garbagebags_f.p3d',
		'sign_pedcrossing.p3d',
		'kiosk_blueking_f.p3d',
		'sign_bus.p3d',
		'sign_priority.p3d',
		'wreck_ural_f.p3d',
		'wreck_uaz_f.p3d',
		'wreck_bmp2_f.p3d',
		'wreck_brdm2_f.p3d',
		'sign_oneway.p3d',
		'sign_blindway.p3d',
		'kiosk_gyros_f.p3d',
		'fs_roof_f.p3d',
		'fs_price_f.p3d',
		'misc_cargo1d.p3d',
		'garbagewashingmachine_f.p3d',
		'junkpile_f.p3d',
		'garbagepallet_f.p3d',
		'misc_cargo1c.p3d',
		'misc_cargo1f.p3d',
		'misc_cargo1b.p3d',
		'loco_742_blue.p3d',
		'v3s_wreck_f.p3d',
		'wreck_car_f.p3d',
		'wreck_van_f.p3d',
		'sign_train.p3d',
		'sign_stopprohibited.p3d',
		'bilboard_pizza_presto.p3d',
		'tec.p3d',
		'a_statue01.p3d',
		'sign_parking.p3d',
		'fuelstation_03_roof_f.p3d',
		'fuelstation_03_shop_f.p3d',
		'fuelstation_03_prices_f.p3d',
		'misc_cargo2d.p3d',
		'a_cranecon.p3d',
		'a_statue02.p3d',
		'shed_m02.p3d',
		'sign_blindway_right.p3d',
		'sign_attention.p3d',
		'misc_cargo2e.p3d',
		'zastavka_cedule.p3d',
		'bilboard_riviera.p3d',
		'bilboard_cibulka.p3d',
		'bilboard_bienvenudo.p3d',
		'sign_crossroadmain.p3d',
		'sign_serpentine_left.p3d',
		'bilboard_volte_cernaruske_hnuti.p3d',
		'busstop_village.p3d',
		'sign_speed50.p3d',
		'monument_01_f.p3d',
		'datsun02t.p3d',
		'hiluxt.p3d',
		'datsun01t.p3d',
		'bilboard_cigara_chernomorky.p3d',
		'fuelstation_03_pump_f.p3d',
		'sign_stop.p3d',
		'sign_wiatingprohibited.p3d',
		'sign_main_end.p3d',
		'misc_cargo2b.p3d',
		'misc_cargo2a.p3d',
		'sign_blindway_left.p3d',
		'sign_right.p3d',
		'bilboard_strana_noveho_radu.p3d',
		'bilboard_hlinik.p3d',
		'misc_cargo1a.p3d',
		'sign_flyawaygrit.p3d',
		'bilboard_smadny_maskrnik.p3d',
		'bilboard_everon.p3d',
		'crane_f.p3d',
		'sign_service.p3d',
		'kiosk_redburger_f.p3d',
		'sign_left.p3d',
		'sign_rightdirection.p3d',
		'sign_snowchains_end.p3d',
		'sign_downhill.p3d',
		'sign_accomodation.p3d',
		'bilboard_likery_bardak.p3d',
		'garbage_misc.p3d',
		'junkpile.p3d',
		'garbage_paleta.p3d',
		'misc_gcontainer_big.p3d',
		'bilboard_toaletak_armasan.p3d',
		'sign_priority_new.p3d',
		'cargo20_military_green_f.p3d',
		'fs_feed_f.p3d',
		'wreck_skodovka_f.p3d',
		'garbagebin_02_f.p3d',
		'bilboard_nogova.p3d',
		'bilboard_vodka.p3d',
		'toiletbox_f.p3d',
		'fieldtoilet_f.p3d',
		'cargobox_v1_f.p3d',
		'campingtable_f.p3d',
		'gastank_01_yellow_f.p3d',
		'gastank_01_blue_f.p3d',
		'misc_cargo2c.p3d',
		'cargo20_blue_f.p3d',
		'cargo20_brick_red_f.p3d',
		'bilboard_escape.p3d',
		'sign_stop_new.p3d',		
		'a_tvtower_base.p3d'
		
	];
	
	
	// Hide Objects
	
		{

			_x hideObject TRUE;
				
		} foreach (nearestTerrainObjects [_centerPos, [], _radius] select {getModelInfo _x #0 in _blacklistedModelList});