

		_arsenalHeadgear = [
		
			"ASZ_Cap_SOF",
			"ASZ_Cap_SOFdes",
			"ASZ_Cap_Alp",
			"FIR_ScorpionHMCS"

		];
		
		
		_arsenalGoggles = [

			"G_AirPurifyingRespirator_01_F",
			"G_Balaclava_blk",
			"G_Balaclava_combat",
			"G_Balaclava_lowprofile",
			"G_Balaclava_oli",
			"G_Balaclava_TI_blk_F",
			"G_Balaclava_TI_G_blk_F",
			"G_Balaclava_TI_G_tna_F",
			"G_Balaclava_TI_tna_F",
			"G_Combat",
			"G_Combat_Goggles_tna_F",
			"G_B_Diving",
			"G_Lowprofile",
			"G_Tactical_Black",
			"G_Tactical_Clear"
			
		];
		
		
		_arsenalUniforms = [


		];

		
		_arsenalVests = [
		
			"Vest_Camo_Base",
			"ASZ_Uniforme_Crew",
			"ASZ_Combat_Uniform_CM",
			"ASZ_Combat_Uniform_CM_des",
			"ASZ_Uniforme_CM",
			"ASZ_Uniforme_CM_des",
			"ASZ_Uniforme_LAG",
			"ASZ_Uniforme_RAP",
			"ASZ_Uniforme_ALP",
			"ASZ_SOD_Gear_BA_Vegecam",
			"ASZ_SOD_Gear_BA_Multiland",
			"ASZ_SOD_Gear_BA_Woodland",
			"ASZ_SOD_Gear_BA_Desert",
			"ASZ_SOD_Gear_BA_GL_Vegecam",
			"ASZ_SOD_Gear_BA_GL_Multiland",
			"ASZ_SOD_Gear_BA_GL_Woodland",
			"ASZ_SOD_Gear_BA_GL_Desert",
			"ASZ_SOD_Gear_BA_Medic_Vegecam",
			"ASZ_SOD_Gear_BA_Medic_Multiland",
			"ASZ_SOD_Gear_BA_Medic_Woodland",
			"ASZ_SOD_Gear_BA_Medic_Desert",
			"ASZ_SOD_Gear_BA_TL_Vegecam",
			"ASZ_SOD_Gear_BA_TL_Multiland",
			"ASZ_SOD_Gear_BA_TL_Woodland",
			"ASZ_SOD_Gear_BA_TL_Desert",
			"ASZ_SOD_Gear_BA_MG_Vegecam",
			"ASZ_SOD_Gear_BA_MG_Multiland",
			"ASZ_SOD_Gear_BA_MG_Woodland",
			"ASZ_SOD_Gear_BA_MG_Desert",
			"ASZ_SOD_Gear_BA_Light_Vegecam",
			"ASZ_SOD_Gear_BA_Light_Multiland",
			"ASZ_SOD_Gear_BA_Light_Woodland",
			"ASZ_SOD_Gear_BA_Light_Desert",
			"Greek_A_Rig_Oil",
			"GR_TacVest_Police",
			"GR_RebreatherB",
			"V_DeckCrew_base_F",
			"V_CarrierRigKBT_01_base_F",
			"V_CarrierRigKBT_01_light_base_F",
			"V_CarrierRigKBT_01_heavy_base_F",
			"V_SmershVest_01_base_F",
			"V_SmershVest_01_radio_base_F",
			"rhsusf_iotv_ocp_base"

		];
		
		

		_arsenalBackpacks = [

			"ASZ_Vector",
			"ASZ_Zaino_base",
			"ASZ_GhostBackpack",
			"ASZ_ZainoGreen_Medio",
			"ASZ_ZainoGreen_SOF",
			"ASZ_ZainoGreen_Grande",
			"ASZ_ZainoGreen_Special",
			"ASZ_ZainoDes_Medio",
			"ASZ_ZainoDes_SOF",
			"ASZ_ZainoDes_Grande",
			"ASZ_ZainoDes_Special",
			"ASZ_ZainoGreen_Medico_base",
			"ASZ_ZainoDGT_Medico_base",
			"ASZ_ZainoWood_Medico_base",
			"ASZ_ZainoMulti_Medico_base",
			"ASZ_ZainoDes_Medico_base",
			"ASZ_ZainoDGT_Des_Medico_base",
			"ASZ_ZainoDGT_Grande",
			"ASZ_ZainoDGT_DES_Grande",
			"ASZ_ZainoDGT_Special",
			"ASZ_ZainoDGT_DES_Special",
			"ASZ_ZainoWOOD_Special",
			"ASZ_ZainoMulti_Special",
			"ASZ_ZainoGreen_Grande_M249",
			"ASZ_ZainoGreen_Grande_MG3",
			"ASZ_Zaino_Green_Spike_ASZ",
			"ASZ_Zaino_DGT_Spike_ASZ",
			"ASZ_Zaino_Des_Spike_ASZ",
			"ASZ_Zaino_DGT_Des_Spike_ASZ",
			"ASZ_Zaino_Green_Stinger",
			"ASZ_Zaino_DGT_Stinger",
			"ASZ_Zaino_Des_Stinger",
			"ASZ_Zaino_DGT_Des_Stinger",
			"ASZ_Zaino_Wood_Stinger",
			"ASZ_Zaino_Multi_Stinger",
			"ASZ_ZainoDGT_Medio",
			"ASZ_ZainoDGT_DES_Medio",
			"ASZ_ZainoWood_Medio",
			"ASZ_ZainoMulti_Medio",
			"ASZ_ZainoGreen_Medio_Fuciliere",
			"ASZ_ZainoDGT_Medio_Fuciliere",
			"ASZ_ZainoDES_Medio_Fuciliere",
			"ASZ_ZainoDGT_DES_Medio_Fuciliere",
			"ASZ_ZainoWood_Medio_Fuciliere",
			"ASZ_ZainoMulti_Medio_Fuciliere",
			"ASZ_ZainoGreen_Medio_M249",
			"ASZ_ZainoDGT_Medio_M249",
			"ASZ_ZainoDes_Medio_M249",
			"ASZ_ZainoDGT_Des_Medio_M249",
			"ASZ_ZainoWood_Medio_M249",
			"ASZ_ZainoMulti_Medio_M249",
			"ASZ_ZainoGreen_Medio_Granatiere",
			"ASZ_ZainoDGT_Medio_Granatiere",
			"ASZ_ZainoDes_Medio_Granatiere",
			"ASZ_ZainoDGT_Des_Medio_Granatiere",
			"ASZ_ZainoWood_Medio_Granatiere",
			"ASZ_ZainoMulti_Medio_Granatiere",
			"ASZ_ZainoGreen_Medio_Sabotatore",
			"ASZ_ZainoDGT_Medio_Sabotatore",
			"ASZ_ZainoDes_Medio_Sabotatore",
			"ASZ_ZainoDGT_Des_Medio_Sabotatore",
			"ASZ_ZainoGreen_Medico",
			"ASZ_ZainoDGT_Medico",
			"ASZ_ZainoWood_Medico",
			"ASZ_ZainoMulti_Medico",
			"ASZ_ZainoDes_Medico",
			"ASZ_ZainoDGT_Des_Medico",
			"ASZ_ZainoDGT_SOF",
			"ASZ_ZainoDGT_DES_SOF",
			"ASZ_ZainoWood_SOF",
			"ASZ_ZainoGreen_SOF_Operatore",
			"ASZ_ZainoDGT_SOF_Operatore",
			"ASZ_ZainoDES_SOF_Operatore",
			"ASZ_ZainoDGT_DES_SOF_Operatore",
			"ASZ_ZainoGreen_SOF_M249",
			"ASZ_ZainoDGT_SOF_M249",
			"ASZ_ZainoDES_SOF_M249",
			"ASZ_ZainoDGT_DES_SOF_M249",
			"ASZ_ZainoGreen_SOF_Granatiere",
			"ASZ_ZainoDGT_SOF_Granatiere",
			"ASZ_ZainoDES_SOF_Granatiere",
			"ASZ_ZainoDGT_DES_SOF_Granatiere",
			"ASZ_ZainoGreen_SOF_Cecchino",
			"ASZ_ZainoDGT_SOF_Cecchino",
			"ASZ_ZainoDES_SOF_Cecchino",
			"ASZ_ZainoDGT_DES_SOF_Cecchino",
			"ASZ_ZainoMulti_Cecchino",
			"ASZ_Rastrelliera",
			"ASZ_Rastrelliera_Spike",
			"ASZ_Radio",
			"ASZ_Radio_Wood",
			
			"B_AssaultPack_blk",	
			"B_Parachute",	
			"B_UAV_01_backpack_F",
			"B_UAV_06_medical_backpack_F",
			"B_UAV_06_backpack_F",
			"B_UGV_02_Demining_backpack_F",
			"B_UGV_02_Science_backpack_F",			
			"B_Static_Designator_01_weapon_F"

		];


		_arsenalNvgoggles = [


		];


		_arsenalPrimaryAttachments = [

			"rhsusf_acc_harris_bipod",
			"rhsusf_acc_harris_swivel",
			"rhsusf_acc_saw_bipod",
			"rhsusf_acc_saw_lw_bipod",
			"rhsusf_acc_m14_bipod",
			"rhsusf_acc_grip1",
			"rhsusf_acc_grip2",
			"rhsusf_acc_grip3",
			"rhsusf_acc_grip4",
			"rhsusf_acc_grip4_bipod",
			"rhsusf_acc_rvg_blk",
			"rhsusf_acc_tacsac_blk",
			"rhsusf_acc_tdstubby_blk",
			"rhsusf_acc_kac_grip",
			"rhsusf_acc_kac_grip_saw_bipod",
			"rhs_acc_at4_handler",
			"rhsusf_acc_anpeq15A",
			"rhsusf_acc_anpeq15_bk",
			"rhsusf_acc_anpeq15_h",
			"rhsusf_acc_anpeq15_sc",
			"rhsusf_acc_anpeq15_bk_h",
			"rhsusf_acc_anpeq15_bk_sc",
			"rhsusf_acc_anpeq15_bk_light",
			"rhsusf_acc_anpeq15_light_h",
			"rhsusf_acc_anpeq15_light_sc",
			"rhsusf_acc_anpeq15_bk_light_h",
			"rhsusf_acc_anpeq15_bk_light_sc",
			"rhsusf_acc_anpeq15_wmx_h",
			"rhsusf_acc_anpeq15_wmx_light_h",
			"rhsusf_acc_anpeq15_wmx_sc",
			"rhsusf_acc_anpeq15_wmx_light_sc",
			"rhsusf_acc_anpeq15_bk_top",
			"rhsusf_acc_anpeq15_top_h",
			"rhsusf_acc_anpeq15_bk_top_h",
			"rhsusf_acc_anpeq15_top_sc",
			"rhsusf_acc_anpeq15_bk_top_sc",
			"rhsusf_acc_anpeq15side_bk",
			"rhsusf_acc_anpeq16a",
			"rhsusf_acc_anpeq16a_light",
			"rhsusf_acc_anpeq16a_top",
			"rhsusf_acc_anpeq16a_light_top",
			"rhsusf_acc_anpeq16a_top_h",
			"rhsusf_acc_anpeq16a_light_top_h",
			"rhsusf_acc_anpeq16a_top_sc",
			"rhsusf_acc_anpeq16a_light_top_sc",
			"rhsusf_acc_M952V",			
			"rhsusf_acc_wmx_bk",
			"rhsusf_acc_M2010S",
			"rhsusf_acc_M2010S_sa",
			"rhsusf_acc_SR25S",
			"rhsusf_acc_rotex5_grey",
			"rhsusf_acc_nt4_black",
			"rhsusf_acc_omega9k",
			"rhsusf_acc_rotex_mp7",
			"rhsusf_acc_muzzleFlash_ar15",
			"rhsusf_acc_muzzleFlash_SF3P556",
			"rhsusf_acc_muzzleFlash_SFMB556",
			"rhsusf_acc_muzzleFlash_ardec_m240",
			"rhsusf_acc_muzzleFlash_M14_USGI_NM",
			"rhsusf_m4muzzlebreak_base",
			"rhsusf_acc_SF3P556",
			"rhsusf_acc_SFMB556",
			"rhsusf_acc_ARDEC_M240",
			"rhsusf_acc_m14_flashsuppresor",
			"rhsusf_acc_m24_silencer_black",
			"rhsusf_acc_m24_muzzlehider_black",
			"rhsusf_acc_aac_scarh_silencer",
			"rhsusf_acc_aac_762sd_silencer",
			"rhsusf_acc_aac_762sdn6_silencer",
			"rhsusf_acc_aac_m14dcqd_silencer",
			"rhsusf_acc_sniper_base",
			"rhsusf_acc_compm4",
			"rhsusf_acc_T1_high",
			"rhsusf_acc_T1_low",
			"rhsusf_acc_T1_low_fwd",
			"rhsusf_acc_T1_low_fwd_ak",
			"rhsusf_acc_RX01",
			"rhsusf_acc_RX01_NoFilter",
			"rhsusf_acc_RM05",
			"rhsusf_acc_RM05_fwd",
			"rhsusf_acc_RM05_fwd_ak",
			"rhsusf_acc_mrds",
			"rhsusf_acc_mrds_fwd",
			"rhsusf_acc_mrds_fwd_ak",
			"rhsusf_acc_eotech_552",
			"rhsusf_acc_anpvs27",
			"rhsusf_acc_anpas13gv1",
			"rhsusf_acc_LEUPOLDMK4",
			"rhsusf_acc_ELCAN",
			"rhsusf_acc_ELCAN_ard",
			"rhsusf_acc_elcan_3d",
			"rhsusf_acc_elcan_ard_3d",
			"rhsusf_acc_ELCAN_pip",
			"rhsusf_acc_ELCAN_ard_pip",
			"rhsusf_acc_su230_base",
			"rhsusf_acc_su230_base_3d",
			"rhsusf_acc_su230_mrds_base",
			"rhsusf_acc_su230_mrds_base_3d",
			"rhsusf_acc_su230",
			"rhsusf_acc_su230_3d",
			"rhsusf_acc_su230_mrds",
			"rhsusf_acc_su230_mrds_3d",
			"rhsusf_acc_su230a",
			"rhsusf_acc_su230a_3d",
			"rhsusf_acc_su230a_mrds",
			"rhsusf_acc_su230a_mrds_3d",
			"rhsusf_acc_SpecterDR",
			"rhsusf_acc_SpecterDR_D",
			"rhsusf_acc_SpecterDR_OD",
			"rhsusf_acc_SpecterDR_CX",
			"rhsusf_acc_SpecterDR_A",
			"rhsusf_acc_SpecterDR_3d",
			"rhsusf_acc_SpecterDR_D_3D",
			"rhsusf_acc_SpecterDR_OD_3D",
			"rhsusf_acc_SpecterDR_A_3d",
			"rhsusf_acc_SpecterDR_CX_3D",
			"rhsusf_acc_SpecterDR_pvs27",
			"rhsusf_acc_ACOG",
			"rhsusf_acc_ACOG_sa",
			"rhsusf_acc_ACOG2",
			"rhsusf_acc_ACOG3",
			"rhsusf_acc_ACOG_USMC",
			"rhsusf_acc_ACOG2_USMC",
			"rhsusf_acc_ACOG3_USMC",
			"rhsusf_acc_ACOG_RMR",
			"rhsusf_acc_ACOG_3d",
			"rhsusf_acc_ACOG_sa_3d",
			"rhsusf_acc_ACOG2_3d",
			"rhsusf_acc_ACOG3_3d",
			"rhsusf_acc_ACOG_USMC_3d",
			"rhsusf_acc_ACOG2_USMC_3d",
			"rhsusf_acc_ACOG3_USMC_3d",
			"rhsusf_acc_ACOG_RMR_3d",
			"rhsusf_acc_ACOG_pip",
			"rhsusf_acc_ACOG_sa_pip",
			"rhsusf_acc_ACOG2_pip",
			"rhsusf_acc_ACOG3_pip",
			"rhsusf_acc_ACOG_USMC_pip",
			"rhsusf_acc_ACOG2_USMC_pip",
			"rhsusf_acc_ACOG3_USMC_pip",
			"rhsusf_acc_ACOG_RMR_pip",
			"rhsusf_acc_ACOG_anpvs27",
			"rhsusf_acc_LEUPOLDMK4_2",
			"rhsusf_acc_LEUPOLDMK4_2_mrds",
			"rhsusf_acc_premier",
			"rhsusf_acc_premier_mrds",
			"rhsusf_acc_premier_low",
			"rhsusf_acc_premier_anpvs27",
			"rhsusf_acc_M8541",
			"rhsusf_acc_M8541_mrds",
			"rhsusf_acc_M8541_low",
			"rhsusf_acc_M2A1",
			"rhsusf_acc_eotech_xps3",
			"rhsusf_acc_g33_xps3",
			"rhsusf_acc_g33_xps3_flip",
			"rhsusf_acc_g33_T1",
			"rhsusf_acc_g33_T1_flip",
			"rhs_weap_optic_smaw",
			"rhs_weap_optic_smaw_1",
			"rhs_weap_optic_smaw_2",
			"rhs_weap_optic_smaw_3",
			"rhs_weap_optic_smaw_4",
			"rhs_weap_optic_smaw_5",
			"rhs_weap_optic_smaw_6",
			"rhs_weap_optic_smaw_7",
			"rhs_weap_optic_smaw_8",
			"rhs_weap_optic_smaw_9",
			"rhs_weap_optic_smaw_10",
			
			"acc_flashlight",
			"acc_pointer_IR",
					
			"ASZ_Eotech_des",
			"ASZ_Eotech_blk",
			"ASZ_Aimpoint_COMPM4S",
			"ASZ_Aimpoint_PRO_blk",
			"ASZ_Aimpoint_PRO_des",
			"ASZ_Acog",
			"ASZ_AMS",
			"ASZ_Leupold_MK4_CQT",
			"ASZ_Leupold_MK4_MRT_black",
			"ASZ_Leupold_MK4_MRT_des",
			"ASZ_Leupold_MK4_LRT_blk",
			"ASZ_Leupold_VXR_Patrol",
			"ASZ_Schmidt_Bender_LP",
			"ASZ_Tasco_Pronghorn",
			"ASZ_M_Pistol_sd",
			"ASZ_Silencer_M9",
			"ASZ_Silencer_556_blk",
			"ASZ_Silencer_556_des",
			"ASZ_Silencer_762_blk",
			"ASZ_Silencer_762_des",
			"ASZ_Silencer_M4A1",
			"ASZ_Silencer_AR7090",
			"ASZ_Pointer",
			"ASZ_Pointer_blk",
			"ASZ_Pointer_M4",
			"ASZ_flashlight",
			"ASZ_FlashLight_glock17"
		
		];


		_arsenalSecondaryAttachments = [

		];
		
		_arsenalExplosives = [
		
			"SatchelCharge_Remote_Mag",
			"DemoCharge_Remote_Mag",
			"SLAMDirectionalMine_Wire_Mag",
			"ClaymoreDirectionalMine_Remote_Mag",
			"HandGrenade",
			"MiniGrenade",
			"SmokeShell",
			"SmokeShellRed",
			"SmokeShellGreen",
			"SmokeShellYellow",
			"SmokeShellPurple",
			"SmokeShellBlue",
			"SmokeShellOrange",
			"Chemlight_green",
			"Chemlight_red",
			"Chemlight_yellow",
			"Chemlight_blue",
			"B_IR_Grenade",
			"Laserbatteries"
		
		];


		_arsenalItems = [
		
			"rhsusf_bino_lerca_1200_black",
			"rhsusf_bino_lerca_1200_tan",
			"lerca_1200_black",
			"lerca_1200_tan",
			"rhsusf_bino_lrf_Vector21",
			"rhsusf_lrf_Vector21",
			"rhsusf_bino_leopold_mk4",
			"Leupold_Mk4",
			"rhsusf_bino_m24",
			"rhsusf_bino_m24_ARD",
			"m24_bino",
			"m24_bino_ARD",
			
			"ItemGPS",
			"B_UavTerminal",
			"Laserdesignator",
			"MineDetector",
			"Binocular",
			"FirstAidKit",
			"ItemCompass",
			"Rangefinder",
			"ItemWatch",
			"ToolKit",
			"ItemRadio",
			"Medikit",
			"ItemMap"

		];
				
		_return = [_arsenalHeadgear, _arsenalGoggles, _arsenalUniforms, _arsenalVests, _arsenalBackpacks, _arsenalNvgoggles, _arsenalPrimaryAttachments, _arsenalSecondaryAttachments, _arsenalExplosives, _arsenalItems];
		
		_return
