// RIFLES

'OPTRE_M295_BMR_Desert',
'OPTRE_M12_SOC'


// HANDGUNS




// LAUNCHERS

'OPTRE_M41_SSR',
'OPTRE_M41_SSR_G',
'OPTRE_FC_T33_FuelRod_Cannon_Guided'


// ATTACHMENTS

'OPTRE_MA5Suppressor',
'OPTRE_M393_Suppressor',
'OPTRE_M6_silencer',
'OPTRE_M6C_compensator',
'OPTRE_M7_silencer',
'OPTRE_M12_Suppressor',
'OPTRE_SRS99D_Suppressor',
'OPTRE_HMG38_CarryHandle',
'OPTRE_MA5_SmartLink',
'OPTRE_MA5C_SmartLink',
'OPTRE_MA5_BUIS',
'OPTRE_BMR_Scope',
'OPTRE_BR55HB_Scope',
'OPTRE_BR45_Scope',
'OPTRE_M392_Scope',
'OPTRE_M393_Scope',
'OPTRE_M393_ACOG',
'OPTRE_M393_EOTECH',
'OPTRE_M73_SmartLink',
'OPTRE_M6G_Scope',
'OPTRE_M6C_Scope',
'OPTRE_M7_Sight',
'OPTRE_M12_Optic',
'OPTRE_SRS99_Scope',
'OPTRE_SRS99C_Scope',
'OPTRE_SRM_Sight',
'OPTRE_M6G_Flashlight',
'OPTRE_M6C_Laser',
'OPTRE_M45_Flashlight',
'OPTRE_M45_Flashlight_red',
'OPTRE_M7_Flashlight',
'OPTRE_M7_Laser',
'OPTRE_M12_Laser'


// UNIFORMS

'OPTRE_FC_Marines_Uniform',
'OPTRE_FC_Marines_Uniform_L',
'OPTRE_FC_Marines_Uniform_WDL',
'OPTRE_FC_Marines_Uniform_WDL_L',
'OPTRE_FC_Marines_Uniform_BLK',
'OPTRE_FC_Marines_Uniform_BLK_L',
'OPTRE_FC_Marines_Uniform_BRN',
'OPTRE_FC_Marines_Uniform_BRN_L',
'OPTRE_FC_Marines_Uniform_SNO',
'OPTRE_FC_Marines_Uniform_SNO_L',
'OPTRE_FC_Marines_Uniform_DES',
'OPTRE_FC_Marines_Uniform_DES_L',
'OPTRE_UNSC_Marine_Uniform_SlimLeg',
'OPTRE_UNSC_Marine_Uniform_S_SlimLeg',
'OPTRE_UNSC_Marine_Uniform_R_SlimLeg',
'OPTRE_UNSC_Marine_Uniform_T_SlimLeg',
'OPTRE_UNSC_Marine_Uniform_T2_SlimLeg',
'OPTRE_UNSC_Marine_Uniform_T3_SlimLeg',
'OPTRE_UNSC_Marine_Uniform',
'OPTRE_UNSC_Marine_Uniform_S',
'OPTRE_UNSC_Marine_Uniform_R',
'OPTRE_UNSC_Marine_Uniform_T',
'OPTRE_UNSC_Marine_Uniform_T2',
'OPTRE_UNSC_Marine_Uniform_T3'

'OPTRE_MJOLNIR_Undersuit',
'OPTRE_FC_MJOLNIR_MKVI_Undersuit',
'OPTRE_MJOLNIR_Dress_Uniform',


'OPTRE_UNSC_Airforce_Uniform',
'OPTRE_UNSC_Airforce_Uniform_S',
'OPTRE_UNSC_Airforce_Uniform_R',
'OPTRE_UNSC_Airforce_Uniform_SlimLeg',
'OPTRE_UNSC_Airforce_Uniform_S_SlimLeg',
'OPTRE_UNSC_Airforce_Uniform_R_SlimLeg',


// Woodland

'OPTRE_UNSC_Army_Uniform_WDL',
'OPTRE_UNSC_Army_Uniform_S_WDL',
'OPTRE_UNSC_Army_Uniform_R_WDL',
'OPTRE_UNSC_Army_Uniform_T_WDL',
'OPTRE_UNSC_Army_Uniform_T2_WDL',
'OPTRE_UNSC_Army_Uniform_T3_WDL',
'OPTRE_UNSC_Army_Uniform_WDL_SlimLeg',
'OPTRE_UNSC_Army_Uniform_S_WDL_SlimLeg',
'OPTRE_UNSC_Army_Uniform_R_WDL_SlimLeg',
'OPTRE_UNSC_Army_Uniform_T_WDL_SlimLeg',
'OPTRE_UNSC_Army_Uniform_T2_WDL_SlimLeg',
'OPTRE_UNSC_Army_Uniform_T3_WDL_SlimLeg',

// Desert

'OPTRE_UNSC_Army_Uniform_DES',
'OPTRE_UNSC_Army_Uniform_S_DES',
'OPTRE_UNSC_Army_Uniform_R_DES',
'OPTRE_UNSC_Army_Uniform_T_DES',
'OPTRE_UNSC_Army_Uniform_T2_DES',
'OPTRE_UNSC_Army_Uniform_T3_DES',
'OPTRE_UNSC_Army_Uniform_DES_SlimLeg',
'OPTRE_UNSC_Army_Uniform_S_DES_SlimLeg',
'OPTRE_UNSC_Army_Uniform_R_DES_SlimLeg',
'OPTRE_UNSC_Army_Uniform_T_DES_SlimLeg',
'OPTRE_UNSC_Army_Uniform_T2_DES_SlimLeg',
'OPTRE_UNSC_Army_Uniform_T3_DES_SlimLeg',


// Tropical

'OPTRE_UNSC_Army_Uniform_TRO',
'OPTRE_UNSC_Army_Uniform_S_TRO',
'OPTRE_UNSC_Army_Uniform_R_TRO',
'OPTRE_UNSC_Army_Uniform_T_TRO',
'OPTRE_UNSC_Army_Uniform_T2_TRO',
'OPTRE_UNSC_Army_Uniform_TRO_SlimLeg',
'OPTRE_UNSC_Army_Uniform_S_TRO_SlimLeg',
'OPTRE_UNSC_Army_Uniform_R_TRO_SlimLeg',
'OPTRE_UNSC_Army_Uniform_T_TRO_SlimLeg',
'OPTRE_UNSC_Army_Uniform_T2_TRO_SlimLeg',


// Urban

'OPTRE_UNSC_Army_Uniform_URB',
'OPTRE_UNSC_Army_Uniform_S_URB',
'OPTRE_UNSC_Army_Uniform_R_URB',
'OPTRE_UNSC_Army_Uniform_T_URB',
'OPTRE_UNSC_Army_Uniform_URB_SlimLeg',
'OPTRE_UNSC_Army_Uniform_S_URB_SlimLeg',
'OPTRE_UNSC_Army_Uniform_R_URB_SlimLeg',
'OPTRE_UNSC_Army_Uniform_T_URB_SlimLeg',




// Winter

'OPTRE_UNSC_Army_Uniform_SNO',
'OPTRE_UNSC_Army_Uniform_S_SNO',
'OPTRE_UNSC_Army_Uniform_R_SNO',
'OPTRE_UNSC_Army_Uniform_T_SNO',
'OPTRE_UNSC_Army_Uniform_SNO_SlimLeg',
'OPTRE_UNSC_Army_Uniform_S_SNO_SlimLeg',
'OPTRE_UNSC_Army_Uniform_R_SNO_SlimLeg',
'OPTRE_UNSC_Army_Uniform_T_SNO_SlimLeg',




// Olive

'OPTRE_UNSC_Army_Uniform_OLI',
'OPTRE_UNSC_Army_Uniform_S_OLI',
'OPTRE_UNSC_Army_Uniform_R_OLI',
'OPTRE_UNSC_Army_Uniform_T_OLI',
'OPTRE_UNSC_Army_Uniform_T2_OLI',
'OPTRE_UNSC_Army_Uniform_OLI_SlimLeg',
'OPTRE_UNSC_Army_Uniform_S_OLI_SlimLeg',
'OPTRE_UNSC_Army_Uniform_R_OLI_SlimLeg',
'OPTRE_UNSC_Army_Uniform_T_OLI_SlimLeg',
'OPTRE_UNSC_Army_Uniform_T2_OLI_SlimLeg',




// Black

'OPTRE_UNSC_Army_Uniform_BLK',
'OPTRE_UNSC_Army_Uniform_S_BLK',
'OPTRE_UNSC_Army_Uniform_R_BLK',
'OPTRE_UNSC_Army_Uniform_T_BLK',
'OPTRE_UNSC_Army_Uniform_T2_BLK',
'OPTRE_UNSC_Army_Uniform_T3_BLK',
'OPTRE_UNSC_Army_Uniform_BLK_SlimLeg',
'OPTRE_UNSC_Army_Uniform_S_BLK_SlimLeg',
'OPTRE_UNSC_Army_Uniform_R_BLK_SlimLeg',
'OPTRE_UNSC_Army_Uniform_T_BLK_SlimLeg',
'OPTRE_UNSC_Army_Uniform_T2_BLK_SlimLeg',
'OPTRE_UNSC_Army_Uniform_T3_BLK_SlimLeg',




// Mixed

'OPTRE_UNSC_Army_Uniform_WDLDES',
'OPTRE_UNSC_Army_Uniform_S_WDLDES',
'OPTRE_UNSC_Army_Uniform_R_WDLDES',
'OPTRE_UNSC_Army_Uniform_DESWDL',
'OPTRE_UNSC_Army_Uniform_S_DESWDL',
'OPTRE_UNSC_Army_Uniform_R_DESWDL',
'OPTRE_UNSC_Army_Uniform_WDLDES_SlimLeg',
'OPTRE_UNSC_Army_Uniform_S_WDLDES_SlimLeg',
'OPTRE_UNSC_Army_Uniform_R_WDLDES_SlimLeg',
'OPTRE_UNSC_Army_Uniform_DESWDL_SlimLeg',
'OPTRE_UNSC_Army_Uniform_S_DESWDL_SlimLeg',
'OPTRE_UNSC_Army_Uniform_R_DESWDL_SlimLeg',

'OPTRE_UNSC_Army_Uniform_OLIWDL',
'OPTRE_UNSC_Army_Uniform_S_OLIWDL',
'OPTRE_UNSC_Army_Uniform_R_OLIWDL',
'OPTRE_UNSC_Army_Uniform_OLIWDL_SlimLeg',
'OPTRE_UNSC_Army_Uniform_S_OLIWDL_SlimLeg',
'OPTRE_UNSC_Army_Uniform_R_OLIWDL_SlimLeg',

'OPTRE_UNSC_Army_Uniform_OLITRO',
'OPTRE_UNSC_Army_Uniform_S_OLITRO',
'OPTRE_UNSC_Army_Uniform_R_OLITRO',
'OPTRE_UNSC_Army_Uniform_OLITRO_SlimLeg',
'OPTRE_UNSC_Army_Uniform_S_OLITRO_SlimLeg',
'OPTRE_UNSC_Army_Uniform_R_OLITRO_SlimLeg',

'OPTRE_UNSC_Army_Uniform_BLKURB',
'OPTRE_UNSC_Army_Uniform_S_BLKURB',
'OPTRE_UNSC_Army_Uniform_R_BLKURB',
'OPTRE_UNSC_Army_Uniform_BLKURB_SlimLeg',
'OPTRE_UNSC_Army_Uniform_S_BLKURB_SlimLeg',
'OPTRE_UNSC_Army_Uniform_R_BLKURB_SlimLeg',

'OPTRE_UNSC_Army_Uniform_AFMAR',
'OPTRE_UNSC_Army_Uniform_S_AFMAR',
'OPTRE_UNSC_Army_Uniform_R_AFMAR',
'OPTRE_UNSC_Army_Uniform_AFMAR_SlimLeg',
'OPTRE_UNSC_Army_Uniform_S_AFMAR_SlimLeg',
'OPTRE_UNSC_Army_Uniform_R_AFMAR_SlimLeg',














'OPTRE_UNSC_ODST_Uniform',
'OPTRE_UNSC_PT_ODST_Uniform',

'OPTRE_UNSC_Dress_Uniform_gray',
'OPTRE_UNSC_Dress_Uniform_white',
'OPTRE_UNSC_Dress_Uniform_odst',
'OPTRE_UNSC_Dress_Uniform_green',
'OPTRE_UNSC_Dress_Uniform_medical',
'OPTRE_UNSC_Dress_Uniform_NBlue',

'OPTRE_UNSC_PT_Uniform',











'OPTRE_UNSC_Navy_Uniform_Yellow',
'OPTRE_UNSC_Navy_Uniform_Orange',
'OPTRE_UNSC_Navy_Uniform_Red',
'OPTRE_UNSC_Navy_Uniform_Blue',
'OPTRE_UNSC_Navy_Uniform_Gray',
'OPTRE_UNSC_Navy_Uniform_Olive',
'OPTRE_UNSC_Navy_Uniform_White',
'OPTRE_UNSC_Navy_Uniform_ONI',

'OPTRE_ONI_Researcher_Uniform',
'OPTRE_ONI_Researcher_Uniform_Light',

'OPTRE_Ins_BJ_Undersuit',

'OPTRE_Ins_ER_uniform_GAtan',
'OPTRE_Ins_ER_uniform_GAgreen',
'OPTRE_Ins_ER_uniform_GGod',
'OPTRE_Ins_ER_uniform_GGgrey',
'OPTRE_Ins_ER_jacket_surplus_OD',
'OPTRE_Ins_ER_jacket_surplus_redshirt',
'OPTRE_Ins_ER_jacket_surplus_brown',
'OPTRE_Ins_ER_jacket_brown_surplus',
'OPTRE_Ins_ER_jacket_od_surplus',
'OPTRE_Ins_ER_jacket_surgeon1',
'OPTRE_Ins_ER_jacket_surgeon2',
'OPTRE_Ins_ER_rolled_surplus_black',
'OPTRE_Ins_ER_rolled_surplus_crimson',
'OPTRE_Ins_ER_rolled_jean_orca',
'OPTRE_Ins_ER_rolled_OD_crimson',
'OPTRE_Ins_ER_rolled_OD_blknblu',
'OPTRE_Ins_ER_rolled_OD_blknred',
'OPTRE_Ins_URF_Combat_Uniform'


// VESTS

'OPTRE_FC_Elite_Armor_Minor',
'OPTRE_FC_Elite_Armor_Major',
'OPTRE_FC_Elite_Armor_SpecOps',
'OPTRE_FC_Elite_Armor_Ultra',
'OPTRE_FC_Elite_Armor_Zealot',
'OPTRE_FC_Elite_Armor_FieldMarshal',
'OPTRE_FC_Elite_Armor_HonorGuard',
'OPTRE_FC_Elite_Armor_HonorGuard_Ultra',

'OPTRE_FC_M52B_Armor_Vest',
'OPTRE_FC_M52B_Armor_Breacher',
'OPTRE_FC_M52B_Armor_Grenadier',
'OPTRE_FC_M52B_Armor_Marksman',
'OPTRE_FC_M52B_Armor_Rifleman',
'OPTRE_FC_M52B_Armor_Sniper',
'OPTRE_FC_M52B_Armor_TeamLeader',
'OPTRE_FC_M52B_Armor_Light',
'OPTRE_FC_M52B_Armor_Vest_BRN',
'OPTRE_FC_M52B_Armor_Breacher_BRN',
'OPTRE_FC_M52B_Armor_Grenadier_BRN',
'OPTRE_FC_M52B_Armor_Marksman_BRN',
'OPTRE_FC_M52B_Armor_Rifleman_BRN',
'OPTRE_FC_M52B_Armor_Sniper_BRN',
'OPTRE_FC_M52B_Armor_TeamLeader_BRN',
'OPTRE_FC_M52B_Armor_Light_BRN',
'OPTRE_FC_M52B_Armor_Vest_SNO',
'OPTRE_FC_M52B_Armor_Breacher_SNO',
'OPTRE_FC_M52B_Armor_Grenadier_SNO',
'OPTRE_FC_M52B_Armor_Marksman_SNO',
'OPTRE_FC_M52B_Armor_Rifleman_SNO',
'OPTRE_FC_M52B_Armor_Sniper_SNO',
'OPTRE_FC_M52B_Armor_TeamLeader_SNO',
'OPTRE_FC_M52B_Armor_Light_SNO',
'OPTRE_FC_M52B_Armor_Vest_DES',
'OPTRE_FC_M52B_Armor_Breacher_DES',
'OPTRE_FC_M52B_Armor_Grenadier_DES',
'OPTRE_FC_M52B_Armor_Marksman_DES',
'OPTRE_FC_M52B_Armor_Rifleman_DES',
'OPTRE_FC_M52B_Armor_Sniper_DES',
'OPTRE_FC_M52B_Armor_TeamLeader_DES',
'OPTRE_FC_M52B_Armor_Light_DES',

'OPTRE_FC_MJOLNIR_MKV_Armor',
'OPTRE_FC_MJOLNIR_MKV_Armor_Olive',
'OPTRE_FC_MJOLNIR_MKV_Armor_Black',
'OPTRE_FC_MJOLNIR_MKV_Armor_Night',
'OPTRE_FC_MJOLNIR_MKV_Armor_Freeman',
'OPTRE_FC_MJOLNIR_MKV_Armor_117',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor_White',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor_Olive',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor_Tan',
'OPTRE_FC_MJOLNIR_MKV_Armor_Caboose',
'OPTRE_FC_MJOLNIR_MKV_Armor_Church',
'OPTRE_FC_MJOLNIR_MKV_Armor_Donut',
'OPTRE_FC_MJOLNIR_MKV_Armor_Grif',
'OPTRE_FC_MJOLNIR_MKV_Armor_Sarge',
'OPTRE_FC_MJOLNIR_MKV_Armor_Simmons',
'OPTRE_FC_MJOLNIR_MKV_Armor_Tucker',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor_Tex',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor_Caboose',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor_Church',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor_Tucker',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor_Donut',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor_Grif',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor_Simmons',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor_Sarge',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor_Kaikaina',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor_Lopez',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor_Doc',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor_North',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor_South',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor_York',
'OPTRE_FC_MJOLNIR_Mark_VI_Armor_Washington',
'OPTRE_MJOLNIR_Mk4Armor',
'OPTRE_MJOLNIR_Mk4Armor_Blue',
'OPTRE_MJOLNIR_Mk4Armor_Red',
'OPTRE_MJOLNIR_MkVBArmor',

'OPTRE_UNSC_M52A_Armor1_WDL',
'OPTRE_UNSC_M52A_Armor2_WDL',
'OPTRE_UNSC_M52A_Armor3_WDL',
'OPTRE_UNSC_M52A_Armor4_WDL',
'OPTRE_UNSC_M52A_Armor_Sniper_WDL',
'OPTRE_UNSC_M52A_Armor_Rifleman_WDL',
'OPTRE_UNSC_M52A_Armor_MG_WDL',
'OPTRE_UNSC_M52A_Armor_Grenadier_WDL',
'OPTRE_UNSC_M52A_Armor_Marksman_WDL',
'OPTRE_UNSC_M52A_Armor_Breacher_WDL',
'OPTRE_UNSC_M52A_Armor_TL_WDL',
'OPTRE_UNSC_M52A_Armor_Medic_WDL',
'OPTRE_UNSC_M52A_Armor1_DES',
'OPTRE_UNSC_M52A_Armor2_DES',
'OPTRE_UNSC_M52A_Armor3_DES',
'OPTRE_UNSC_M52A_Armor4_DES',
'OPTRE_UNSC_M52A_Armor_Sniper_DES',
'OPTRE_UNSC_M52A_Armor_Rifleman_DES',
'OPTRE_UNSC_M52A_Armor_MG_DES',
'OPTRE_UNSC_M52A_Armor_Grenadier_DES',
'OPTRE_UNSC_M52A_Armor_Marksman_DES',
'OPTRE_UNSC_M52A_Armor_Breacher_DES',
'OPTRE_UNSC_M52A_Armor_TL_DES',
'OPTRE_UNSC_M52A_Armor_Medic_DES',
'OPTRE_UNSC_M52A_Armor1_SNO',
'OPTRE_UNSC_M52A_Armor2_SNO',
'OPTRE_UNSC_M52A_Armor3_SNO',
'OPTRE_UNSC_M52A_Armor4_SNO',
'OPTRE_UNSC_M52A_Armor_Sniper_SNO',
'OPTRE_UNSC_M52A_Armor_Rifleman_SNO',
'OPTRE_UNSC_M52A_Armor_MG_SNO',
'OPTRE_UNSC_M52A_Armor_Grenadier_SNO',
'OPTRE_UNSC_M52A_Armor_Marksman_SNO',
'OPTRE_UNSC_M52A_Armor_Breacher_SNO',
'OPTRE_UNSC_M52A_Armor_TL_SNO',
'OPTRE_UNSC_M52A_Armor_Medic_SNO',
'OPTRE_UNSC_M52A_Armor1_URB',
'OPTRE_UNSC_M52A_Armor2_URB',
'OPTRE_UNSC_M52A_Armor3_URB',
'OPTRE_UNSC_M52A_Armor4_URB',
'OPTRE_UNSC_M52A_Armor_Sniper_URB',
'OPTRE_UNSC_M52A_Armor_Rifleman_URB',
'OPTRE_UNSC_M52A_Armor_MG_URB',
'OPTRE_UNSC_M52A_Armor_Grenadier_URB',
'OPTRE_UNSC_M52A_Armor_Marksman_URB',
'OPTRE_UNSC_M52A_Armor_Breacher_URB',
'OPTRE_UNSC_M52A_Armor_TL_URB',
'OPTRE_UNSC_M52A_Armor_Medic_URB',
'OPTRE_UNSC_M52A_Armor1_MAR',
'OPTRE_UNSC_M52A_Armor2_MAR',
'OPTRE_UNSC_M52A_Armor3_MAR',
'OPTRE_UNSC_M52A_Armor4_MAR',
'OPTRE_UNSC_M52A_Armor_Sniper_MAR',
'OPTRE_UNSC_M52A_Armor_Rifleman_MAR',
'OPTRE_UNSC_M52A_Armor_MG_MAR',
'OPTRE_UNSC_M52A_Armor_Grenadier_MAR',
'OPTRE_UNSC_M52A_Armor_Marksman_MAR',
'OPTRE_UNSC_M52A_Armor_Breacher_MAR',
'OPTRE_UNSC_M52A_Armor_TL_MAR',
'OPTRE_UNSC_M52A_Armor_Corpsman_MAR',
'OPTRE_UNSC_M52A_Armor_Pilot_AF',
'OPTRE_UNSC_M52A_Armor_Soft',
'OPTRE_UNSC_M52A_Armor_SoftD',
'OPTRE_UNSC_M52A_Armor_SoftDK',

'OPTRE_UNSC_M52D_Armor',
'OPTRE_UNSC_M52D_Armor_Demolitions',
'OPTRE_UNSC_M52D_Armor_Sniper',
'OPTRE_UNSC_M52D_Armor_Light',
'OPTRE_UNSC_M52D_Armor_Scout',
'OPTRE_UNSC_M52D_Armor_Rifleman',
'OPTRE_UNSC_M52D_Armor_Marksman',
'OPTRE_UNSC_M52D_Armor_Medic',
'OPTRE_UNSC_M52D_Armor_Scorch',
'OPTRE_UNSC_M52D_Armor_Deltagamer',
'OPTRE_UNSC_M52D_Armor_Jedi',
'OPTRE_UNSC_M52D_Armor_Lum',
'OPTRE_UNSC_M52D_Armor_Nighto',
'OPTRE_UNSC_M52D_Armor_Forky',

'OPTRE_Ins_BJ_Armor',
'OPTRE_Ins_BJ_Armor_URB',
'OPTRE_Ins_URF_Armor1'


// HEADGEAR

'OPTRE_FC_Elite_Helmet_Minor',
'OPTRE_FC_Elite_Helmet_Major',
'OPTRE_FC_Elite_Helmet_SpecOps',
'OPTRE_FC_Elite_Helmet_Ultra',
'OPTRE_FC_Elite_Helmet_Zealot',
'OPTRE_FC_Elite_Helmet_FieldMarshal',
'OPTRE_FC_Elite_Helmet_HonorGuard',
'OPTRE_FC_Elite_Helmet_HonorGuard_Ultra',
'OPTRE_FC_CH255_Helmet',
'OPTRE_FC_CH255_Helmet_Visor',
'OPTRE_FC_CH255_Helmet_BRN',
'OPTRE_FC_CH255_Helmet_BRN_Visor',
'OPTRE_FC_CH255_Helmet_DES',
'OPTRE_FC_CH255_Helmet_DES_Visor',
'OPTRE_FC_CH255_Helmet_SNO',
'OPTRE_FC_CH255_Helmet_SNO_Visor',
'OPTRE_FC_CH255_Helmet_Medic',
'OPTRE_FC_CH255_Helmet_Visor_Medic',
'OPTRE_FC_CH255_Helmet_BRN_Medic',
'OPTRE_FC_CH255_Helmet_BRN_Visor_Medic',
'OPTRE_FC_CH255_Helmet_DES_Medic',
'OPTRE_FC_CH255_Helmet_DES_Visor_Medic',
'OPTRE_FC_CH255_Helmet_SNO_Medic',
'OPTRE_FC_CH255_Helmet_SNO_Visor_Medic',
'OPTRE_FC_VX19_Helmet',
'OPTRE_FC_MJOLNIR_MKV_Helmet',
'OPTRE_FC_MJOLNIR_MKV_Helmet_Olive',
'OPTRE_FC_MJOLNIR_MKV_Helmet_Black',
'OPTRE_FC_MJOLNIR_MKV_Helmet_Night',
'OPTRE_FC_MJOLNIR_MKV_Helmet_Freeman',
'OPTRE_FC_MJOLNIR_MKV_Helmet_117',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet_White',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Olive',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Tan',
'OPTRE_FC_MJOLNIR_MKV_Helmet_Caboose',
'OPTRE_FC_MJOLNIR_MKV_Helmet_Church',
'OPTRE_FC_MJOLNIR_MKV_Helmet_Donut',
'OPTRE_FC_MJOLNIR_MKV_Helmet_Grif',
'OPTRE_FC_MJOLNIR_MKV_Helmet_Sarge',
'OPTRE_FC_MJOLNIR_MKV_Helmet_Simmons',
'OPTRE_FC_MJOLNIR_MKV_Helmet_Tucker',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Tex',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Caboose',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Church',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Donut',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Grif',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Simmons',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Sarge',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Kaikaina',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Lopez',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Doc',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet_North',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet_South',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet_York',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Washington',
'OPTRE_FC_MJOLNIR_Mark_VI_Helmet_Tucker',
'OPTRE_MJOLNIR_Mk4Helmet',
'OPTRE_MJOLNIR_Mk4Helmet_Blue',
'OPTRE_MJOLNIR_Mk4Helmet_Red',
'OPTRE_MJOLNIR_MkVBHelmet',
'OPTRE_MJOLNIR_EVAHelmet',
'OPTRE_MJOLNIR_EVAHelmet_Emily',
'OPTRE_MJOLNIR_ReconHelmet',
'OPTRE_MJOLNIR_MPHelmet',
'OPTRE_MJOLNIR_Dress_Hat',
'OPTRE_UNSC_CH252_Helmet_WDL',
'OPTRE_UNSC_CH252_Helmet_Vacuum_WDL',
'OPTRE_UNSC_CH252_Helmet2_WDL',
'OPTRE_UNSC_CH252_Helmet3_WDL',
'OPTRE_UNSC_CH252_Helmet2_Vacuum_WDL',
'OPTRE_UNSC_CH252_Helmet_WDL_MED',
'OPTRE_UNSC_CH252_Helmet_Vacuum_WDL_MED',
'OPTRE_UNSC_CH252_Helmet2_WDL_MED',
'OPTRE_UNSC_CH252_Helmet2_Vacuum_WDL_MED',
'OPTRE_UNSC_CH252_Helmet_DES',
'OPTRE_UNSC_CH252_Helmet_Vacuum_DES',
'OPTRE_UNSC_CH252_Helmet2_DES',
'OPTRE_UNSC_CH252_Helmet3_DES',
'OPTRE_UNSC_CH252_Helmet2_Vacuum_DES',
'OPTRE_UNSC_CH252_Helmet_DES_MED',
'OPTRE_UNSC_CH252_Helmet_Vacuum_DES_MED',
'OPTRE_UNSC_CH252_Helmet2_DES_MED',
'OPTRE_UNSC_CH252_Helmet2_Vacuum_DES_MED',
'OPTRE_UNSC_CH252_Helmet_SNO',
'OPTRE_UNSC_CH252_Helmet_Vacuum_SNO',
'OPTRE_UNSC_CH252_Helmet2_SNO',
'OPTRE_UNSC_CH252_Helmet2_Vacuum_SNO',
'OPTRE_UNSC_CH252_Helmet_SNO_MED',
'OPTRE_UNSC_CH252_Helmet_Vacuum_SNO_MED',
'OPTRE_UNSC_CH252_Helmet2_SNO_MED',
'OPTRE_UNSC_CH252_Helmet2_Vacuum_SNO_MED',
'OPTRE_UNSC_CH252_Helmet_URB',
'OPTRE_UNSC_CH252_Helmet_Vacuum_URB',
'OPTRE_UNSC_CH252_Helmet2_URB',
'OPTRE_UNSC_CH252_Helmet2_Vacuum_URB',
'OPTRE_UNSC_CH252_Helmet_URB_MED',
'OPTRE_UNSC_CH252_Helmet_Vacuum_URB_MED',
'OPTRE_UNSC_CH252_Helmet2_URB_MED',
'OPTRE_UNSC_CH252_Helmet2_Vacuum_URB_MED',
'OPTRE_UNSC_CH252_Helmet_MAR',
'OPTRE_UNSC_CH252_Helmet_Vacuum_MAR',
'OPTRE_UNSC_CH252_Helmet2_MAR',
'OPTRE_UNSC_CH252_Helmet2_Vacuum_MAR',
'OPTRE_UNSC_CH252_Helmet_MAR_MED',
'OPTRE_UNSC_CH252_Helmet_Vacuum_MAR_MED',
'OPTRE_UNSC_CH252_Helmet2_MAR_MED',
'OPTRE_UNSC_CH252_Helmet2_Vacuum_MAR_MED',
'OPTRE_UNSC_CH252D_Helmet',
'OPTRE_UNSC_CH252D_Helmet_Scorch',
'OPTRE_UNSC_CH252D_Helmet_Deltagamer',
'OPTRE_UNSC_CH252D_Helmet_Jedi',
'OPTRE_UNSC_CH252D_Helmet_Lum',
'OPTRE_UNSC_CH252D_Helmet_Nighto',
'OPTRE_UNSC_CH252D_Helmet_Forky',
'OPTRE_UNSC_Recon_Helmet',
'OPTRE_UNSC_CH252A_Helmet',
'OPTRE_UNSC_CH252A_Helmet_dp',
'OPTRE_UNSC_VX16_Helmet',
'OPTRE_UNSC_VX16_HelmetNV',
'OPTRE_UNSC_VX16_HelmetV',
'OPTRE_UNSC_VX16_Helmet_Mask',
'OPTRE_UNSC_VX16_Helmet_MaskV',
'OPTRE_UNSC_VX16_Helmet_MaskS',
'OPTRE_UNSC_VX16_Helmet_MaskSV',
'OPTRE_UNSC_VX16_Helmet_med',
'OPTRE_UNSC_VX16_HelmetNV_med',
'OPTRE_UNSC_VX16_HelmetV_med',
'OPTRE_UNSC_VX16_Helmet_Mask_med',
'OPTRE_UNSC_VX16_Helmet_MaskV_med',
'OPTRE_UNSC_VX16_Helmet_MaskS_med',
'OPTRE_UNSC_VX16_Helmet_MaskSV_med',
'OPTRE_UNSC_VX16_Helmet_oli',
'OPTRE_UNSC_VX16_HelmetNV_oli',
'OPTRE_UNSC_VX16_HelmetV_oli',
'OPTRE_UNSC_VX16_Helmet_Mask_oli',
'OPTRE_UNSC_VX16_Helmet_MaskV_oli',
'OPTRE_UNSC_VX16_Helmet_MaskS_oli',
'OPTRE_UNSC_VX16_Helmet_MaskSV_oli',
'OPTRE_UNSC_VX16_Helmet_oli_med',
'OPTRE_UNSC_VX16_HelmetNV_oli_med',
'OPTRE_UNSC_VX16_HelmetV_oli_med',
'OPTRE_UNSC_VX16_Helmet_Mask_oli_med',
'OPTRE_UNSC_VX16_Helmet_MaskV_oli_med',
'OPTRE_UNSC_VX16_Helmet_MaskS_oli_med',
'OPTRE_UNSC_VX16_Helmet_MaskSV_oli_med',
'OPTRE_UNSC_VX16_Helmet_des',
'OPTRE_UNSC_VX16_HelmetNV_des',
'OPTRE_UNSC_VX16_HelmetV_des',
'OPTRE_UNSC_VX16_Helmet_Mask_des',
'OPTRE_UNSC_VX16_Helmet_MaskV_des',
'OPTRE_UNSC_VX16_Helmet_MaskS_des',
'OPTRE_UNSC_VX16_Helmet_MaskSV_des',
'OPTRE_UNSC_VX16_Helmet_des_med',
'OPTRE_UNSC_VX16_HelmetNV_des_med',
'OPTRE_UNSC_VX16_HelmetV_des_med',
'OPTRE_UNSC_VX16_Helmet_Mask_des_med',
'OPTRE_UNSC_VX16_Helmet_MaskV_des_med',
'OPTRE_UNSC_VX16_Helmet_MaskS_des_med',
'OPTRE_UNSC_VX16_Helmet_MaskSV_des_med',
'OPTRE_UNSC_VX16_Helmet_blk',
'OPTRE_UNSC_VX16_HelmetNV_blk',
'OPTRE_UNSC_VX16_HelmetV_blk',
'OPTRE_UNSC_VX16_Helmet_Mask_blk',
'OPTRE_UNSC_VX16_Helmet_MaskV_blk',
'OPTRE_UNSC_VX16_Helmet_MaskS_blk',
'OPTRE_UNSC_VX16_Helmet_MaskSV_blk',
'OPTRE_UNSC_VX16_Helmet_blk_med',
'OPTRE_UNSC_VX16_HelmetNV_blk_med',
'OPTRE_UNSC_VX16_HelmetV_blk_med',
'OPTRE_UNSC_VX16_Helmet_Mask_blk_med',
'OPTRE_UNSC_VX16_Helmet_MaskV_blk_med',
'OPTRE_UNSC_VX16_Helmet_MaskS_blk_med',
'OPTRE_UNSC_VX16_Helmet_MaskSV_blk_med',
'OPTRE_UNSC_VX16_Helmet_wht',
'OPTRE_UNSC_VX16_HelmetNV_wht',
'OPTRE_UNSC_VX16_HelmetV_wht',
'OPTRE_UNSC_VX16_Helmet_Mask_wht',
'OPTRE_UNSC_VX16_Helmet_MaskV_wht',
'OPTRE_UNSC_VX16_Helmet_MaskS_wht',
'OPTRE_UNSC_VX16_Helmet_MaskSV_wht',
'OPTRE_UNSC_VX16_Helmet_wht_med',
'OPTRE_UNSC_VX16_HelmetNV_wht_med',
'OPTRE_UNSC_VX16_HelmetV_wht_med',
'OPTRE_UNSC_VX16_Helmet_Mask_wht_med',
'OPTRE_UNSC_VX16_Helmet_MaskV_wht_med',
'OPTRE_UNSC_VX16_Helmet_MaskS_wht_med',
'OPTRE_UNSC_VX16_Helmet_MaskSV_wht_med',
'OPTRE_UNSC_VX16_Helmet_Mask_uwu',
'OPTRE_UNSC_Dress_Hat',
'OPTRE_UNSC_PatrolCap_Army',
'OPTRE_UNSC_PatrolCap_Marines',
'OPTRE_UNSC_Cap_ODST',
'OPTRE_UNSC_Watchcap',
'OPTRE_PatrolCap_Navy',
'OPTRE_Cap_FinalDawn',
'OPTRE_Helmet_NavyDeckCrew',
'OPTRE_ONI_Researcher_Headgear',
'OPTRE_Ins_BJ_Helmet',
'OPTRE_Ins_BJ_Helmet_URB',
'OPTRE_h_Booniehat_Grey',
'OPTRE_h_PatrolCap_Green',
'OPTRE_h_PatrolCap_Brown',
'OPTRE_Ins_URF_Helmet1',
'OPTRE_Ins_URF_Helmet2',
'OPTRE_Ins_URF_Helmet3',
'OPTRE_Ins_URF_Helmet4'


// BINOCULARS




// NVG

'OPTRE_NVG'


// GOGGLES

'OPTRE_Glasses_Cigar',
'OPTRE_FC_Glasses_Cigar',
'OPTRE_Glasses_Cigarette',
'OPTRE_HUD_Glasses',
'OPTRE_HUD_g_Glasses',
'OPTRE_HUD_r_Glasses',
'OPTRE_HUD_b_Glasses',
'OPTRE_HUD_p_Glasses',
'OPTRE_HUD_w_Glasses',
'OPTRE_EyePiece'


// MISC ITEMS

'OPTRE_Datachip',
'OPTRE_Biofoam',
'OPTRE_MedKit',
'OPTRE_Medigel'


// BACKPACKS

'OPTRE_ILCS_Rucksack_Black',
'OPTRE_ILCS_Rucksack_Medical',
'OPTRE_ILCS_Rucksack_Heavy',
'OPTRE_S12_SOLA_Jetpack',
'OPTRE_S12_SOLA_Jetpack_On',
'OPTRE_Fury_Backpack_Nuke',
'OPTRE_Armored_Matrix',
'OPTRE_ANPRC_515',
'OPTRE_UNSC_Rucksack',
'OPTRE_UNSC_Rucksack_Heavy',
'OPTRE_UNSC_Rucksack_Medic',
'OPTRE_ANPRC_521_Green',
'OPTRE_ANPRC_521_Black',
'OPTRE_ANPRC_521_Snow',
'OPTRE_ANPRC_521_Tan',
'OPTRE_ANPRC_521_URF',
'OPTRE_ONI_Researcher_Suitcase',
'OPTRE_ILCS_Rucksack_Black_M41',
'OPTRE_ILCS_Rucksack_Heavy_M41G',
'OPTRE_ILCS_Rucksack_Heavy_Demo',
'OPTRE_ILCS_Rucksack_Heavy_M73',
'OPTRE_ILCS_Rucksack_Black_Lead',
'OPTRE_ILCS_Rucksack_Medical_Filled',
'OPTRE_UNSC_Rucksack_M41',
'OPTRE_UNSC_Rucksack_Heavy_M41G',
'OPTRE_UNSC_Rucksack_Heavy_Demo',
'OPTRE_UNSC_Rucksack_Heavy_M73',
'OPTRE_UNSC_Rucksack_Lead',
'OPTRE_UNSC_Rucksack_Medic_Filled',
'OPTRE_ILCS_Rucksack_Black_Spartan',
'OPTRE_ILCS_Rucksack_Medical_Spartan',
'OPTRE_ILCS_Rucksack_Heavy_Spartan',
'OPTRE_S12_SOLA_Jetpack_Spartan',
'OPTRE_S12_SOLA_Jetpack_On_Spartan',
'OPTRE_Fury_Backpack_Nuke_Spartan',
'OPTRE_Armored_Matrix_Spartan',
'OPTRE_ANPRC_515_Spartan',
'OPTRE_UNSC_Rucksack_Spartan',
'OPTRE_UNSC_Rucksack_Heavy_Spartan',
'OPTRE_UNSC_Rucksack_Medic_Spartan',
'OPTRE_ANPRC_521_Green_Spartan',
'OPTRE_ANPRC_521_Black_Spartan',
'OPTRE_ANPRC_521_Snow_Spartan',
'OPTRE_ANPRC_521_Tan_Spartan',
'OPTRE_ANPRC_521_URF_Spartan',
'OPTRE_ILCS_Rucksack_Black_M41_Spartan',
'OPTRE_ILCS_Rucksack_Heavy_M41G_Spartan',
'OPTRE_ILCS_Rucksack_Heavy_Demo_Spartan',
'OPTRE_ILCS_Rucksack_Heavy_M73_Spartan',
'OPTRE_ILCS_Rucksack_Black_Lead_Spartan',
'OPTRE_ILCS_Rucksack_Medical_Filled_Spartan',
'OPTRE_UNSC_Rucksack_M41_Spartan',
'OPTRE_UNSC_Rucksack_Heavy_M41G_Spartan',
'OPTRE_UNSC_Rucksack_Heavy_Demo_Spartan',
'OPTRE_UNSC_Rucksack_Heavy_M73_Spartan',
'OPTRE_UNSC_Rucksack_Lead_Spartan',
'OPTRE_UNSC_Rucksack_Medic_Filled_Spartan'


