_allLevels = [
	
	// Level 1
	
	[
		
		"B_Truck_01_mover_F",
		"B_Truck_01_ammo_F",
		"B_Truck_01_box_F",
		"B_Truck_01_cargo_F",
		"B_Truck_01_flatbed_F",
		"B_Truck_01_fuel_F",
		"B_Truck_01_medical_F",
		"B_Truck_01_Repair_F",
		"B_Truck_01_transport_F",
		"B_Truck_01_covered_F",
		"B_MRAP_01_F",
		"B_Quadbike_01_F",
		"B_LSV_01_unarmed_F",
		"B_T_Truck_01_mover_F",
		"B_T_Truck_01_ammo_F",
		"B_T_Truck_01_box_F",
		"B_T_Truck_01_cargo_F",
		"B_T_Truck_01_flatbed_F",
		"B_T_Truck_01_fuel_F",
		"B_T_Truck_01_medical_F",
		"B_T_Truck_01_Repair_F",
		"B_T_Truck_01_transport_F",
		"B_T_Truck_01_covered_F",
		"B_T_LSV_01_unarmed_F",
		"B_T_MRAP_01_F",
		"B_T_Quadbike_01_F",
		"B_T_Boat_Transport_01_F",
		"B_D_Truck_01_mover_lxWS",
		"B_D_Truck_01_ammo_lxWS",
		"B_D_Truck_01_box_lxWS",
		"B_D_Truck_01_cargo_lxWS",
		"B_D_Truck_01_flatbed_lxWS",
		"B_D_Truck_01_fuel_lxWS",
		"B_D_Truck_01_medical_lxWS",
		"B_D_Truck_01_Repair_lxWS",
		"B_D_Truck_01_transport_lxWS",
		"B_D_Truck_01_covered_lxWS",
		"B_D_MRAP_01_lxWS",
		"B_D_Quadbike_01_lxWS",
		"B_Boat_Transport_01_F",
		"B_G_Boat_Transport_01_F",
		"B_T_Lifeboat",
		"B_Lifeboat",
		"B_G_Van_01_fuel_F",
		"B_G_Offroad_01_F",
		"B_G_Offroad_01_repair_F",
		"B_G_Quadbike_01_F",
		"B_G_Van_01_transport_F",
		"B_G_Van_02_vehicle_F",
		"B_G_Van_02_transport_F",
		"B_G_Offroad_01_armor_base_lxWS",
		"I_Quadbike_01_F",
		"I_MRAP_03_F",
		"I_Truck_02_ammo_F",
		"I_Truck_02_cargo_lxWS",
		"I_Truck_02_flatbed_lxWS",
		"I_Truck_02_fuel_F",
		"I_Truck_02_medical_F",
		"I_Truck_02_box_F",
		"I_Truck_02_transport_F",
		"I_Truck_02_covered_F",
		"I_Boat_Transport_01_F",
		"I_G_Boat_Transport_01_F",
		"I_G_Van_01_fuel_F",
		"I_G_Offroad_01_F",
		"I_G_Offroad_01_armor_base_lxWS",
		"I_G_Quadbike_01_F",
		"I_G_Van_01_transport_F",
		"I_G_Van_02_vehicle_F",
		"I_G_Van_02_transport_F",
		"I_G_Offroad_01_repair_F",
		"I_E_Offroad_01_F",
		"I_E_Offroad_01_comms_F",
		"I_E_Offroad_01_covered_F",
		"I_E_Quadbike_01_F",
		"I_E_Van_02_medevac_F",
		"I_E_Van_02_vehicle_F",
		"I_E_Van_02_transport_F",
		"I_E_Van_02_transport_MP_F",
		"I_E_Truck_02_Ammo_F",
		"I_E_Truck_02_cargo_lxWS",
		"I_E_Truck_02_flatbed_lxWS",
		"I_E_Truck_02_fuel_F",
		"I_E_Truck_02_Medical_F",
		"I_E_Truck_02_Box_F",
		"I_E_Truck_02_transport_F",
		"I_E_Truck_02_F",
		"I_C_Boat_Transport_01_F",
		"I_C_Offroad_02_unarmed_F",
		"I_C_Van_01_transport_F",
		"I_C_Van_02_vehicle_F",
		"I_C_Van_02_transport_F",
		"I_Tura_Offroad_armor_lxWS",
		"O_MRAP_02_F",
		"O_LSV_02_unarmed_F",
		"O_Quadbike_01_F",
		"O_Truck_03_device_F",
		"O_Truck_03_ammo_F",
		"O_Truck_03_fuel_F",
		"O_Truck_03_medical_F",
		"O_Truck_03_repair_F",
		"O_Truck_03_transport_F",
		"O_Truck_03_covered_F",
		"O_Truck_02_Ammo_F",
		"O_Truck_02_cargo_lxWS",
		"O_Truck_02_flatbed_lxWS",
		"O_Truck_02_fuel_F",
		"O_Truck_02_medical_F",
		"O_Truck_02_box_F",
		"O_Truck_02_transport_F",
		"O_Truck_02_covered_F",
		"O_Boat_Transport_01_F",
		"O_Lifeboat",
		"O_T_Boat_Transport_01_F",
		"O_T_Lifeboat",
		"O_T_MRAP_02_ghex_F",
		"O_T_LSV_02_unarmed_F",
		"O_T_Quadbike_01_ghex_F",
		"O_T_Truck_03_device_ghex_F",
		"O_T_Truck_03_ammo_ghex_F",
		"O_T_Truck_03_fuel_ghex_F",
		"O_T_Truck_03_medical_ghex_F",
		"O_T_Truck_03_repair_ghex_F",
		"O_T_Truck_03_transport_ghex_F",
		"O_T_Truck_03_covered_ghex_F",
		"O_T_Truck_02_Ammo_F",
		"O_T_Truck_02_cargo_lxWS",
		"O_T_Truck_02_flatbed_lxWS",
		"O_T_Truck_02_fuel_F",
		"O_T_Truck_02_Medical_F",
		"O_T_Truck_02_Box_F",
		"O_T_Truck_02_transport_F",
		"O_T_Truck_02_F",
		"O_Tura_Offroad_armor_lxWS",
		"C_Boat_Civil_01_F",
		"C_Boat_Civil_01_police_F",
		"C_Boat_Civil_01_rescue_F",
		"C_Rubberboat",
		"C_Boat_Transport_02_F",
		"C_Scooter_Transport_01_F",
		"C_Van_01_fuel_F",
		"C_Hatchback_01_F",
		"C_Hatchback_01_sport_F",
		"C_Kart_01_F",
		"C_Kart_01_Blu_F",
		"C_Kart_01_Fuel_F",
		"C_Kart_01_Red_F",
		"C_Kart_01_Vrana_F",
		"C_Offroad_02_unarmed_F",
		"C_Offroad_01_F",
		"C_Offroad_01_comms_F",
		"C_Offroad_01_covered_F",
		"C_Offroad_lxWS",
		"C_Offroad_01_repair_F",
		"C_Quadbike_01_F",
		"C_SUV_01_F",
		"C_Tractor_01_F",
		"C_Van_01_transport_F",
		"C_Van_01_box_F",
		"C_Van_02_medevac_F",
		"C_Van_02_vehicle_F",
		"C_Van_02_service_F",
		"C_Van_02_transport_F",
		"C_Truck_02_cargo_lxWS",
		"C_Truck_02_flatbed_lxWS",
		"C_Truck_02_fuel_F",
		"C_Truck_02_racing_lxWS",
		"C_Truck_02_box_F",
		"C_Truck_02_transport_F",
		"C_Truck_02_covered_F",
		"C_Plane_Civil_01_racing_F",
		"C_Heli_Light_01_civil_F",
		"I_Heli_light_03_unarmed_F",
		"I_E_Heli_light_03_unarmed_F",
		"I_C_Heli_Light_01_civil_F",
		"O_Heli_Light_02_unarmed_F",
		"B_ION_Heli_Light_02_unarmed_lxWS",
		"B_D_Heli_Light_01_lxWS",
		"B_Heli_Light_01_F",
		"I_LT_01_scout_F",
		"I_LT_01_cannon_F",
		"B_SDV_01_F",
		"O_SDV_01_F",
		"I_SDV_01_F",
		"I_C_Plane_Civil_01_F",
		"C_Plane_Civil_01_F",
		"C_Plane_Civil_01_racing_F"
		
	],
	
	// Level 2
	[
		
		"I_LT_01_AA_F",
		"I_A_Truck_02_aa_lxWS",
		"B_LSV_01_armed_F",
		"B_T_LSV_01_armed_F",
		"O_LSV_02_armed_F",
		"O_T_LSV_02_armed_F",
		"I_G_Offroad_01_armed_F",
		"B_G_Offroad_01_armed_F",
		"O_G_Offroad_01_armed_F",
		"I_C_Offroad_02_LMG_F",
		"B_Heli_Light_01_dynamicLoadout_F",
		"B_Heli_Transport_01_F",
		"B_D_Heli_Transport_01_lxWS",
		"B_CTRG_Heli_Transport_01_tropic_F",
		"B_CTRG_Heli_Transport_01_sand_F",
		"I_Heli_light_03_dynamicLoadout_F",
		"I_E_Heli_light_03_dynamicLoadout_F",
		"O_Heli_Light_02_dynamicLoadout_F",
		"I_Plane_Fighter_03_dynamicLoadout_F"
		
	],
		
	// Level 3
	[
	
		"B_APC_Wheeled_01_cannon_F",
		"B_D_APC_Wheeled_01_cannon_lxWS",
		"B_T_APC_Wheeled_01_cannon_F",
		"O_APC_Wheeled_02_rcws_v2_F",
		"O_T_APC_Wheeled_02_rcws_v2_ghex_F",
		"I_APC_Wheeled_03_cannon_F",
		"B_MRAP_01_hmg_F",
		"B_LSV_01_AT_F",
		"B_D_MRAP_01_hmg_lxWS",
		"B_T_LSV_01_AT_F",
		"B_T_MRAP_01_hmg_F",
		"O_LSV_02_AT_F",
		"O_T_LSV_02_AT_F",
		"O_T_MRAP_02_hmg_ghex_F",
		"O_MRAP_02_hmg_F",
		"I_MRAP_03_hmg_F",
		"I_G_Offroad_01_AT_F",
		"B_G_Offroad_01_AT_F",
		"O_G_Offroad_01_AT_F",
		"I_C_Offroad_02_AT_F",
		"I_Boat_Armed_01_minigun_F",
		"O_Boat_Armed_01_hmg_F",
		"O_T_Boat_Armed_01_hmg_F",
		"B_Boat_Armed_01_minigun_F",
		"B_T_Boat_Armed_01_minigun_F",
		"I_C_Boat_Transport_02_F",
		"B_Heli_Transport_03_F",
		"B_Heli_Transport_03_unarmed_F",
		"I_Heli_Transport_02_F",
		"O_Heli_Transport_04_F",
		"O_Heli_Transport_04_ammo_F",
		"O_Heli_Transport_04_bench_F",
		"O_Heli_Transport_04_box_F",
		"O_Heli_Transport_04_fuel_F",
		"O_Heli_Transport_04_medevac_F",
		"O_Heli_Transport_04_repair_F",
		"O_Heli_Transport_04_covered_F",
		"B_T_VTOL_01_infantry_F",
		"B_T_VTOL_01_vehicle_F",
		"O_T_VTOL_02_infantry_dynamicLoadout_F",
		"O_T_VTOL_02_vehicle_dynamicLoadout_F"

	],
	
	// Level 4
	[
	
		"B_AFV_Wheeled_01_cannon_F",
		"B_AFV_Wheeled_01_up_cannon_F",
		"B_T_AFV_Wheeled_01_cannon_F",
		"B_T_AFV_Wheeled_01_up_cannon_F",
		"B_MRAP_01_gmg_F",
		"B_D_MRAP_01_gmg_lxWS",
		"B_T_MRAP_01_gmg_F",
		"O_MRAP_02_gmg_F",
		"O_T_MRAP_02_gmg_ghex_F",
		"I_MRAP_03_gmg_F",
		"B_Plane_Fighter_01_Stealth_F",
		"O_Plane_Fighter_02_Stealth_F",
		"I_Plane_Fighter_03_Cluster_F"
		
	],
	
	// Level 5
	[
		
		"B_T_APC_Tracked_01_rcws_F",
		"B_D_APC_Tracked_01_rcws_lxWS",
		"B_APC_Tracked_01_rcws_F",
		"O_APC_Tracked_02_cannon_F",
		"O_T_APC_Tracked_02_cannon_ghex_F",
		"I_APC_tracked_03_cannon_F",
		"I_E_APC_tracked_03_cannon_F",
		"B_Plane_Fighter_01_F",
		"O_Plane_Fighter_02_F",
		"I_Plane_Fighter_04_F"
		
	],
	
	// Level 6
	[
		
		"O_APC_Tracked_02_AA_F",
		"O_T_APC_Tracked_02_AA_ghex_F",
		"B_APC_Tracked_01_AA_F",
		"B_D_APC_Tracked_01_aa_lxWS",
		"B_T_APC_Tracked_01_AA_F",
		"B_Plane_Fighter_01_Cluster_F",
		"O_Plane_Fighter_02_Cluster_F",
		"I_Plane_Fighter_04_Cluster_F"
		
	],
	
	// Level 7
	[
			
		"B_T_MBT_01_cannon_F",
		"B_T_MBT_01_TUSK_F",
		"B_D_MBT_01_cannon_lxWS",
		"B_D_MBT_01_TUSK_lxWS",
		"B_MBT_01_cannon_F",
		"B_MBT_01_TUSK_F",
		"O_MBT_02_cannon_F",
		"O_MBT_04_cannon_F",
		"O_MBT_04_command_F",
		"O_T_MBT_02_cannon_ghex_F",
		"O_T_MBT_04_cannon_F",
		"O_T_MBT_04_command_F",
		"I_MBT_03_cannon_F",
		"B_Plane_CAS_01_dynamicLoadout_F",
		"O_Plane_CAS_02_dynamicLoadout_F"
		
	],
	
	// Level 8
	[
		
		"B_Heli_Attack_01_dynamicLoadout_F",
		"O_Heli_Attack_02_dynamicLoadout_F",
		"B_T_VTOL_01_armed_F",
		"B_MBT_01_arty_F",
		"B_MBT_01_mlrs_F",
		"B_T_MBT_01_mlrs_F",
		"B_T_MBT_01_arty_F",
		"B_D_MBT_01_arty_lxWS",
		"B_D_MBT_01_mlrs_lxWS",
		"O_MBT_02_arty_F",
		"O_T_MBT_02_arty_ghex_F",
		"I_Truck_02_MRL_F",
		"I_E_Truck_02_MRL_F"
	
	]

];

_allLevels