		
	// Black Listed Selections List
		
		_selections = [

			"mala vrtule blur",
			"velka vrtule blur",
			"vrtule blur",
			"clan",
			"insignia",
			"muzzleflash",
			"zasleh",
			"zasleh1",
			"zasleh2",
			"zasleh3",
			"zasleh4",
			"zasleh5",
			"zasleh_1",
			"zasleh_2",	
			"zasleh_3",		
			"zaslehcoax",
			"l111a1_zasleh",
			"decal_wing",
			"decal_tail",
			"decal_nose",
			"num_1",
			"num_2",
			"num_3",
			"light",
			"lights",
			"light_bo",
			"light_brake_visible",
			"light_brake_bo",
			"light_brake",
			"light_l",
			"light_r",
			"light_g",
			"lights_drive",
			"light_hd_1",
			"light_hd_2",
			'light_l_1',
			'light_r_1',
			'light_r_2',
			'light_l_2',
			'light_back',
			'svetlo',
			"l svetlo",
			"p svetlo",
			"brzdove svetlo",
			"zadni svetlo",
			"t svetlo",
			"lights_front_left",
			"lights_reverse",
			"lights_hide",
			"lights_front_right",
			"lights_front_cone",
			"lights_brake",
			"engine_blur",
			"main rotor blur",
			"tail rotor blur",
			"mainrotorblurred",
			"tailrotorblurred",
			"l7a2_1_zasleh",
			"l7a2_2_zasleh",
			"l7a2_3_zasleh",
			"l7a2_zasleh",
			'cannon_muzzleflash',
			'mainturret_muzzleflash_1_1',
			'mainturret_muzzleflash_1_2',
			'mainturret_muzzleflash',
			'lightfl',
			'lightfr',
			'gun_fir',
			'light_fr',
			'light_fl',
			'light_frr',
			'light_fll',
			'zasleh_i',
			'zasleh_d',
			'back_lights',
			'light_left',
			'light_right',
			'muzzleflash_m2',
			'muzzleflash_gmw',
			'landleft',
			'landright',
			'brzdove_svetlo',
			'l_svetlo',
			'p_svetlo',
			'mg1_zasleh',
			'mg2_zasleh',
			'zadni_svetlo',
			'mg1_light_1',
			'searchlight',
			'mg2_light_1',
			'p svetlo 2',
			'l svetlo 2',
			'zasleh_1',
			'zasleh_twin',
			'com svetlo',
			'mg3_zasleh',
			'mg3_light_1',
			'mg1_zasleh_1',
			'mg1_zasleh_3',
			'mg1_zasleh_2',
			'mg1_zasleh_4',
			'mg1_zasleh_all',
			'mg1_searchlights',
			'mg1_light_1',
			'mg1_light_2',
			'mg1_svetlo',
			'mg2_svetlo',
			'light_front_left',
			'light_front_right',
			'l134a1_zasleh',
			'mr_blur',
			'hdam_tr',
			'hdam_rtr',
			"muzzleflash_cannons",
			'gun_1_muzzleflash',
			'gun_2_muzzleflash',
			"zasleh_kursmg",
			'muzzleflash_dorsal',
			'muzzleflash_front',
			'muzzleflash_tail',
			'muzzleflash',
			'zasleh_back_mg',
			'light_s',
			's svetlo',
			'mainheadlight',
			'muzzleflash03',
			'_truckfuel',
			'muzzleflash_front', 
			'muzzleflash_dorsal', 
			'muzzleflash_belly', 
			'muzzleflash_dorsal2',
			'd_decal_01',
			'd_decal_02',
			'd_decal_03',
			'decals',
			'canopy',
			'mg3_svetlo',
			'muzzleflash_front',
			'muzzleflash_dorsal',
			'muzzleflash_frontright',
			'muzzleflash_frontleft',
			'muzzleflash_tail',
			'muzzleflash_right',
			'muzzleflash_left',
			'muzzleflash_guns',
			'muzzleflash_dorsal_2',
			'muzzleflash_chin',
			'brzdove svetlo',
			'p svetlo',
			'l svetlo',
			'c svetlo',
			'reverse_light',
			'zadni svetlo',
			'searchlight',
			'lights',		
			'light_l',
			'light_fg125',
			'zadni svetlo',
			'brzdove svetlo',
			'light_f_source',
			'light_r_source',
			'light_l_source',
			'light_f',
			'light_l',
			'light_r'

		];
			
		_selections